const {randomUUID}=require('crypto');const {command}=require('./commands');const {optional}=require('./domain');const {validDay}=require('./public/reports');const {moneyCents}=require('./money');const {splitCents}=require('./public/payables-core');const {receiptList,paymentBalance}=require('./public/payments');const {receivableRows,allocationPreview}=require('./public/accounts-core');const {linkReceipt,assertCashState}=require('./cash');
function accountAction(state,action,input){return command(state,'accounts',action,input,(next,date)=>{
 const s=next.sales.find(s=>s.id===input.saleId);if(!s||s.cancelledAt)throw Error('Selecione uma venda válida.');s.receipts=receiptList(s);const balance=paymentBalance(s);if(!balance.known)throw Error('Esta venda não tem saldo conhecido.');if((s.accountVersion||0)!==input.expectedVersion||(s.returnVersion||0)!==input.expectedReturnVersion)throw Error('O saldo ou plano da venda mudou. Confira e revise novamente.');
 if(s.activeAgreementId&&action!=='forgive')throw Error('Saldo transferido para acordo. Receba pelo acordo e preserve as alocações originais.');
 if(action==='plan'){
  if(receiptList(s).length||(s.returns||[]).length||s.forgivenCents)throw Error('Altere o plano somente antes de pagamentos, devoluções ou perdão de saldo.');
  const dates=input.dueDates;if(!Array.isArray(dates)||!dates.length||dates.length>60||dates.some(d=>d&&!validDay(d)))throw Error('Informe de 1 a 60 vencimentos reais ou sem data.');const amounts=splitCents(s.totalCents,dates.length);s.planHistory||=[];if(s.receivablePlan)s.planHistory.push({date,plan:structuredClone(s.receivablePlan)});s.receivablePlan=dates.map((dueDate,index)=>({id:randomUUID(),number:index+1,amountCents:amounts[index],dueDate:dueDate||null}));
 }else if(action==='receive'||action==='allocate'){
  const amountCents=moneyCents(input.value),method=input.paymentMethod;if(!['cash','pix','debit','credit','other'].includes(method))throw Error('Selecione a forma efetiva.');if(input.expectedRemainingCents!==balance.remainingCents)throw Error('O saldo mudou.');assertCashState(next,input.expectedCashSessionId);let allocations;
  if(action==='receive'){const part=receivableRows(s).find(i=>i.id===input.installmentId);if(!part||amountCents>part.remainingCents)throw Error('Recebimento acima do saldo da parcela.');allocations=[{installmentId:part.id,amountCents}];}else{allocations=allocationPreview(s,amountCents);if(JSON.stringify(input.expectedAllocations)!==JSON.stringify(allocations))throw Error('A distribuição mudou. Revise a alocação nas parcelas.');}
  s.receipts=receiptList(s);const receipt={id:randomUUID(),saleId:s.id,requestId:input.requestId,amountCents,paymentMethod:method,date,cashSessionId:null,allocations};s.receipts.push(receipt);linkReceipt(next,s,receipt);const remaining=paymentBalance(s).remainingCents;s.paymentStatus=remaining===0?'received':'partial';s.receivedAt=remaining===0?date:null;
 }else if(action==='forgive'){
  const amountCents=moneyCents(input.value),reason=optional(input.reason,1000);if(!reason)throw Error('Informe por que o saldo será perdoado.');if(amountCents>balance.remainingCents||input.expectedRemainingCents!==balance.remainingCents)throw Error('Valor acima do saldo ou saldo alterado.');let remaining=amountCents;const allocations=[];for(const part of [...receivableRows(s,true)].reverse()){const value=Math.min(part.remainingCents,remaining);if(value){allocations.push({installmentId:part.id,amountCents:value});remaining-=value;}}s.forgivenCents=(s.forgivenCents||0)+amountCents;s.forgiveness||=[];s.forgiveness.push({date,amountCents,allocations,reason,responsible:optional(input.responsible,120)});s.paymentStatus=paymentBalance(s).remainingCents===0?'received':balance.receivedCents>0?'partial':'pending';
 }else throw Error('Ação de recebimento inválida.');s.accountVersion=(s.accountVersion||0)+1;
});}
module.exports={accountAction};
