const {randomUUID}=require('crypto');const {run,record,expected,text,reason,baseRecord,touch,cents,safe,dateOnly}=require('./advanced-common');const {paymentBalance,receiptList}=require('./public/payments');const {receivableRows}=require('./public/accounts-core');const {payableBalance,installmentPaid,splitCents}=require('./public/payables-core');const {agreementPosition,agreementToken}=require('./public/agreements-core');const {linkReceipt,linkExpense,assertCashState}=require('./cash');const {calendarDay}=require('./public/reports');
function originState(state,side,id){const r=record(state,side==='receive'?'sales':'payables',id),balance=side==='receive'?paymentBalance(r):payableBalance(r);if(r.cancelledAt||side==='receive'&&(!r.customerId||!balance.known))throw Error('Selecione origem identificada com saldo conhecido.');return {row:r,balance};}
function agreementAction(state,action,input){return run(state,'agreements',action,input,(next,date)=>{
 if(action==='create'){
  const side=input.side;if(!['receive','pay'].includes(side))throw Error('Escolha receber ou pagar.');if(!Array.isArray(input.originIds)||!input.originIds.length||input.originIds.length>60||new Set(input.originIds).size!==input.originIds.length)throw Error('Escolha de 1 a 60 origens distintas.');let counterparty=null;const origins=input.originIds.map(id=>{const {row:r,balance:b}=originState(next,side,id),party=side==='receive'?r.customerId:r.supplierId;if(!party||counterparty&&counterparty!==party)throw Error('Origens devem ser da mesma contraparte identificada.');counterparty=party;if(r.activeAgreementId||b.remainingCents<1)throw Error('Origem já renegociada ou sem saldo.');const token=JSON.stringify({version:r.version||0,accountVersion:r.accountVersion||0,returnVersion:r.returnVersion||0,remaining:b.remainingCents});if(input.expectedOrigins?.[id]!==token)throw Error('Origem mudou. Confira pagamentos e devoluções.');return {id:r.id,name:side==='receive'?r.customerName:r.description,amountCents:b.remainingCents,totalCents:r.totalCents,paidCentsAtAgreement:b.receivedCents??b.paidCents,internalCents:r.storeCreditCents||0,returnedCents:(r.returns||[]).reduce((n,x)=>n+x.totalCents,0),forgivenCents:r.forgivenCents||0,originalInstallments:structuredClone(side==='receive'?receivableRows(r,true):r.installments),expenseCenterId:r.expenseCenterId||null,category:r.expenseCategory||''};});
  const totalCents=safe(origins.reduce((n,o)=>safe(n+o.amountCents),0));if(!Array.isArray(input.dueDates)||!input.dueDates.length||input.dueDates.length>60)throw Error('Defina de 1 a 60 parcelas.');const amounts=splitCents(totalCents,input.dueDates.length),installments=input.dueDates.map((d,i)=>({id:randomUUID(),number:i+1,dueDate:dateOnly(d,'Vencimento'),amountCents:amounts[i]})),party=record(next,side==='receive'?'customers':'suppliers',counterparty),a=baseRecord(next,'agreements',date,input,{side,counterpartyId:party.id,counterpartyName:party.name,origins,totalCents,installments,payments:[],reason:reason(input)});next.agreements.push(a);for(const o of origins){const r=originState(next,side,o.id).row;r.activeAgreementId=a.id;r.agreementHistory||=[];r.agreementHistory.push({date,agreementId:a.id,amountCents:o.amountCents});if(side==='receive')r.accountVersion=(r.accountVersion||0)+1;else r.version++;}return;
 }
 const a=record(next,'agreements',input.id);expected(a,input);if(a.cancelledAt)throw Error('Acordo cancelado conserva seu histórico.');if(input.expectedOriginToken!==agreementToken(next,a))throw Error('Saldo das origens mudou. Revise a evolução do acordo.');
 if(action==='cancel'){if(a.payments.length)throw Error('Acordo com recebimento ou pagamento não aceita cancelamento simples.');for(const o of a.origins){const r=record(next,a.side==='receive'?'sales':'payables',o.id);if(r.activeAgreementId===a.id)delete r.activeAgreementId;if(a.side==='receive')r.accountVersion=(r.accountVersion||0)+1;else r.version++;}a.cancelledAt=date;touch(a,date,action,{...input,reason:reason(input)});return;}
 if(action!=='settle')throw Error('Ação de acordo inválida.');const position=agreementPosition(next,a),part=position.installments.find(i=>i.id===input.installmentId),amountCents=cents(input.value);if(!part||amountCents>part.remainingCents||input.expectedRemainingCents!==position.remainingCents)throw Error('Valor acima do saldo ou parcela alterada.');if(!['cash','pix','debit','credit','other'].includes(input.paymentMethod))throw Error('Forma efetiva inválida.');assertCashState(next,input.expectedCashSessionId);let remaining=amountCents;const allocations=[];
 for(const origin of position.origins){let originAmount=Math.min(remaining,origin.remainingCents);if(!originAmount)continue;const r=origin.current;const rows=a.side==='receive'?receivableRows(r,true):r.installments.map(i=>({...i,remainingCents:i.amountCents-installmentPaid(r,i.id)}));for(const i of rows.sort((x,y)=>(x.dueDate||'9999').localeCompare(y.dueDate||'9999')||x.number-y.number)){const value=Math.min(originAmount,i.remainingCents);if(value){allocations.push({originId:r.id,installmentId:i.id,amountCents:value,expenseCenterId:origin.expenseCenterId,category:origin.category});originAmount-=value;remaining-=value;}if(!originAmount)break;}if(originAmount)throw Error('Mapa de origem não reconciliado.');if(!remaining)break;}if(remaining)throw Error('Saldos de origem insuficientes.');
 const event={id:randomUUID(),date,installmentId:part.id,amountCents,paymentMethod:input.paymentMethod,allocations,responsible:text(input.responsible,120,'Responsável')};
 if(a.side==='receive'){
  for(const origin of position.origins){const assigned=allocations.filter(x=>x.originId===origin.id);if(!assigned.length)continue;const s=origin.current;s.receipts=receiptList(s);const receipt={id:randomUUID(),saleId:s.id,requestId:null,date,amountCents:safe(assigned.reduce((n,x)=>n+x.amountCents,0)),paymentMethod:input.paymentMethod,cashSessionId:null,agreementId:a.id,agreementPaymentId:event.id,allocations:assigned.map(x=>({installmentId:x.installmentId,amountCents:x.amountCents}))};s.receipts.push(receipt);linkReceipt(next,s,receipt);s.accountVersion=(s.accountVersion||0)+1;const b=paymentBalance(s);s.paymentStatus=b.remainingCents?'partial':'received';s.receivedAt=b.remainingCents?null:date;}
 }else{
  const paidDate=dateOnly(input.paidDate,'Data paga',true);if(paidDate>calendarDay())throw Error('Pagamento não pode ser futuro.');const e={id:randomUUID(),createdAt:date,paidDate,amountCents,paymentMethod:input.paymentMethod,description:'Pagamento acordo ACD-'+a.number+' · '+a.counterpartyName,category:'',expenseCenterId:null,cashSessionId:null,version:1,note:text(input.note,500,'Observação'),agreementId:a.id,payableAllocations:allocations.map(x=>({...x,payableId:x.originId,paymentId:randomUUID()}))};
  const groups=new Map();for(const x of e.payableAllocations){const key=JSON.stringify([x.expenseCenterId||'',x.category]);groups.set(key,{expenseCenterId:x.expenseCenterId,category:x.category,amountCents:safe((groups.get(key)?.amountCents||0)+x.amountCents)});}for(const [key,g] of groups){const check={...g,paidDate};require('./budgets').expenseBudgetFields(next,check,{expenseCenterId:g.expenseCenterId,budgetExcessReason:input.budgetExcessReasons?.[key],expectedBudgetVersion:input.budgetVersions?.[key]},g.expenseCenterId);for(const x of e.payableAllocations)if(JSON.stringify([x.expenseCenterId||'',x.category])===key)x.budgetExcessReason=check.budgetExcessReason||'';}
  next.expenses||=[];next.expenses.push(e);linkExpense(next,e,input);for(const x of e.payableAllocations){const p=record(next,'payables',x.payableId);p.payments.push({id:x.paymentId,installmentId:x.installmentId,amountCents:x.amountCents,expenseId:e.id,date,paidDate,paymentMethod:input.paymentMethod,cashSessionId:e.cashSessionId,agreementId:a.id,agreementPaymentId:event.id});p.version++;p.updatedAt=date;}event.expenseId=e.id;event.paidDate=paidDate;
 }
 a.payments.push(event);touch(a,date,action,input);
 });}
function reconcileAgreements(previous,next){for(const a of next.agreements||[]){if(a.cancelledAt)continue;const old=previous.agreements?.find(x=>x.id===a.id);if(!old)continue;const before=agreementPosition(previous,old),after=agreementPosition(next,a);if(after.adjustedCents>before.adjustedCents){a.adjustments||=[];for(const o of after.origins){const prior=before.origins.find(x=>x.id===o.id);const value=(o.amountCents-o.paidCents-o.remainingCents)-(prior.amountCents-prior.paidCents-prior.remainingCents);if(value>0)a.adjustments.push({date:new Date().toISOString(),originId:o.id,amountCents:value,returnId:o.current?.returns?.at(-1)?.id||null,reason:o.current?.cancelledAt?'Origem cancelada':'Redução comercial da origem'});}a.version++;a.updatedAt=new Date().toISOString();}}return next;}
module.exports={agreementAction,reconcileAgreements};
