const {test}=require('node:test'),assert=require('node:assert/strict');
const {validateProductIdentifiers,lookupProduct,addProductToCart}=require('./public/product-lookup');
const {productFields}=require('./domain');const {exportCsv}=require('./export');
const products=[{id:'p',name:'Produto',code:'CAM-01',barcode:'0012345678905',stock:2,priceCents:1990},{id:'q',name:'Outra etiqueta',code:'00123456789050',stock:4,priceCents:100},{id:'off',name:'Inativo',barcode:'OFF-1',active:false,stock:5,priceCents:200},{id:'zero',name:'Zerado',barcode:'00001',stock:0,priceCents:300}];
test('código de barras é texto, preserva zeros e cadastro antigo permanece compatível',()=>{const p={id:'new'};productFields({products},p,{barcode:' 000123 ',code:'NEW'});assert.equal(p.barcode,'000123');productFields({products},p,{category:'Nova'});assert.equal(p.barcode,'000123');assert.equal(validateProductIdentifiers([],{},{}).barcode,'');assert.throws(()=>validateProductIdentifiers([],{}, {barcode:123}),/texto/);});
test('códigos internos e de barras não podem identificar outro produto, inclusive inativo',()=>{for(const input of [{barcode:'0012345678905'},{code:'0012345678905'},{barcode:'cam-01'},{barcode:'OFF-1'}])assert.throws(()=>validateProductIdentifiers(products,{id:'new'},input),/Já existe/);assert.equal(validateProductIdentifiers(products,products[0],{barcode:products[0].barcode,code:'CAM-01'}).barcode,products[0].barcode);for(const barcode of ['x'.repeat(65),'12 34','12\n34'])assert.throws(()=>validateProductIdentifiers([],{}, {barcode}));});
test('leitura usa código inteiro e nunca substitui por resultado parcial de outro produto',()=>{assert.equal(lookupProduct(products,'0012345678905').product.id,'p');assert.equal(lookupProduct(products,'CAM-01').product.id,'p');assert.equal(lookupProduct(products,'001234').status,'missing');assert.equal(lookupProduct(products,'12345678905').status,'missing');assert.equal(lookupProduct(products,' ').status,'empty');assert.equal(lookupProduct([{id:'1',code:'A'},{id:'2',barcode:'A'}],'A').status,'ambiguous');assert.equal(lookupProduct(products,'OFF-1').product.active,false);});
test('leituras sucessivas somam uma unidade, sem reservar estoque e sem exceder saldo',()=>{let cart=[];cart=addProductToCart(products,cart,'p');cart=addProductToCart(products,cart,'p');assert.deepEqual(cart,[{productId:'p',quantity:2}]);assert.equal(products[0].stock,2);const before=structuredClone(cart);assert.throws(()=>addProductToCart(products,cart,'p'),/estoque/);assert.deepEqual(cart,before);assert.throws(()=>addProductToCart(products,cart,'off'),/inativo/);assert.throws(()=>addProductToCart(products,cart,'zero'),/estoque/);assert.throws(()=>addProductToCart(products,cart,'missing'),/não encontrado/);});
test('seleção manual usa mesmas regras com quantidade inteira e CSV conserva código de barras',()=>{assert.deepEqual(addProductToCart(products,[],'q',3),[{productId:'q',quantity:3}]);assert.throws(()=>addProductToCart(products,[],'q',1.5),/inteira/);const csv=exportCsv({products},'products',['p']);assert.ok(csv.body.includes('Código de barras'));assert.ok(csv.body.includes('0012345678905'));assert.ok(!csv.body.includes('Outra etiqueta'));});
