const A=require('./advanced-common'),{budgetPosition}=require('./public/budget-core');
function validMonth(value){const m=A.text(value,7,'Mês',true);if(!/^\d{4}-\d{2}$/.test(m))throw Error('Informe mês real.');A.dateOnly(m+'-01','Mês',true);return m;}
function center(state,id,existing=null){if(!id)return null;const c=A.record(state,'expenseCenters',id);if(c.active===false&&id!==existing)throw Error('Centro inativo para nova classificação.');return c.id;}
function budgetAction(state,kind,action,input){return A.run(state,kind,action,input,(next,date)=>{
 if(kind==='expenseCenters'){
  if(action==='create'){const name=A.text(input.name,120,'Nome do centro',true);if(next.expenseCenters.some(c=>c.name.toLocaleLowerCase()===name.toLocaleLowerCase()))throw Error('Centro já cadastrado.');next.expenseCenters.push(A.baseRecord(next,kind,date,input,{name,active:true}));return;}
  const c=A.record(next,kind,input.id);A.expected(c,input);if(action==='active'){if(typeof input.active!=='boolean')throw Error('Situação inválida.');c.active=input.active;}else if(action==='edit'){c.name=A.text(input.name,120,'Nome do centro',true);if(next.expenseCenters.some(x=>x.id!==c.id&&x.name.toLocaleLowerCase()===c.name.toLocaleLowerCase()))throw Error('Centro já cadastrado.');}else throw Error('Ação de centro inválida.');A.touch(c,date,action,input,{reason:A.reason(input)});return;
 }
 if(action==='classify'){
  if(!['expenses','payables'].includes(input.kind))throw Error('Registro de classificação inválido.');const r=A.record(next,input.kind,input.id);if(r.payableAllocations?.length)throw Error('Despesa de acordo conserva a classificação de cada origem. Consulte o acordo.');if((r.version||0)!==input.expectedVersion)throw Error('Classificação mudou.');const previous={centerId:r.expenseCenterId||null,category:input.kind==='expenses'?r.category:r.expenseCategory};r.expenseCenterId=center(next,input.centerId,r.expenseCenterId);const category=A.text(input.category,60,'Categoria');if(input.kind==='expenses')r.category=category;else r.expenseCategory=category;r.version||=0;A.touch(r,date,'classify',input,{reason:A.reason(input),previous});return;
 }
 const original=action==='create'?null:A.record(next,'expenseBudgets',input.id);if(original)A.expected(original,input);if(!['create','edit','duplicate'].includes(action))throw Error('Ação de orçamento inválida.');const month=validMonth(input.month);if(action==='duplicate'&&month<=original.month)throw Error('Duplicação exige mês futuro à origem.');const centerId=center(next,input.centerId??original?.centerId),category=A.text(input.category??original?.category,60,'Categoria'),limitCents=action==='duplicate'&&input.value===undefined?original.limitCents:A.cents(input.value);if((next.expenseBudgets||[]).some(b=>b.id!==(action==='edit'?original.id:null)&&b.month===month&&(b.centerId||'')===(centerId||'')&&b.category===category))throw Error('Já existe limite para este mês, centro e categoria.');const fields={month,centerId,category,limitCents,responsible:A.text(input.responsible,120,'Responsável')};if(action==='edit'){const previous=structuredClone(original);Object.assign(original,fields);A.touch(original,date,action,input,{reason:A.reason(input),previous});}else next.expenseBudgets.push(A.baseRecord(next,'expenseBudgets',date,input,{...fields,sourceId:original?.id||null}));
});}
function expenseBudgetFields(state,e,input,existingCenter=null){e.expenseCenterId=center(state,input.expenseCenterId,existingCenter);const p=budgetPosition(state,e.paidDate.slice(0,7),e.expenseCenterId,e.category);if(input.expectedBudgetVersion!==undefined&&input.expectedBudgetVersion!==(p.budget?.version??null))throw Error('O limite mudou. Revise a despesa novamente.');const projected=require('./commands').safe(p.spentCents+e.amountCents,'Gasto mensal');if(p.limitCents!==null&&projected>p.limitCents){e.budgetExcessReason=A.text(input.budgetExcessReason,1000,'Justificativa acima do limite',true);e.budgetLimitCents=p.limitCents;e.budgetVersion=p.budget.version;}e.version=1;}
module.exports={budgetAction,expenseBudgetFields,validMonth};
