const test=require('node:test'),assert=require('node:assert/strict');
const {cashAction}=require('./cash'),{cashSummary}=require('./public/cash-core'),{sale}=require('./server'),{receive}=require('./payments');
const {expense,cancelExpense}=require('./domain'),{change}=require('./server'),{calendarDay,movementSummary}=require('./public/reports'),{cashReport}=require('./cash-report');
const initial=()=>({products:[{id:'p',name:'P',stock:5,priceCents:1000}],customers:[],sales:[]});
const opened=()=>cashAction(initial(),'open',{openingValue:'20',responsible:'Pessoa',requestId:'open'});
test('abertura única, replay exato e suprimento/sangria sem duplicar',()=>{
 const state=opened(),id=state.cashSessions[0].id;assert.equal(cashAction(state,'open',{openingValue:'20',responsible:'Pessoa',requestId:'open'}).cashSessions.length,1);assert.throws(()=>cashAction(state,'open',{openingValue:0,responsible:'Outro'}));
 const payload={sessionId:id,value:5,note:'Troco',requestId:'supply'};const added=cashAction(state,'supply',payload);assert.equal(cashSummary(added.cashSessions[0]).expectedCents,2500);assert.deepEqual(cashAction(added,'supply',payload),added);assert.throws(()=>cashAction(added,'withdraw',{...payload,value:26,requestId:'too-much'}));assert.equal(cashSummary(cashAction(added,'withdraw',{...payload,requestId:'withdraw'}).cashSessions[0]).expectedCents,2000);
});
test('recebimentos novos vinculam; Pix não aumenta dinheiro, anteriores ficam sem vínculo',()=>{
 let state=sale(initial(),{items:[{productId:'p',quantity:1}],paymentMethod:'cash',paymentStatus:'received'});const old=state.sales[0].receipts[0];state=cashAction(state,'open',{openingValue:20,responsible:'Pessoa'});assert.equal(state.sales[0].receipts[0].cashSessionId,null);state=sale(state,{items:[{productId:'p',quantity:1}],paymentMethod:'pix',paymentStatus:'received'});assert.equal(cashSummary(state.cashSessions[0]).expectedCents,2000);assert.equal(cashSummary(state.cashSessions[0]).totals.pix,1000);state=sale(state,{items:[{productId:'p',quantity:1}],paymentMethod:'cash',paymentStatus:'pending'});state=receive(state,{id:state.sales.at(-1).id,value:3,paymentMethod:'cash'});assert.equal(cashSummary(state.cashSessions[0]).expectedCents,2300);assert.equal(state.sales[0].receipts[0].id,old.id);
});
test('despesa exige forma, vínculo explícito e saldo; cancelamento preserva dinheiro',()=>{
 const state=opened(),id=state.cashSessions[0].id,payload={description:'Pago',value:5,paidDate:calendarDay(),paymentMethod:'cash',cashSessionId:id,requestId:'expense'};
 const saved=expense(state,payload);assert.equal(cashSummary(saved.cashSessions[0]).expectedCents,1500);assert.deepEqual(expense(saved,payload),saved);assert.throws(()=>expense(state,{...payload,paymentMethod:'pix'}));assert.throws(()=>expense(state,{...payload,paymentMethod:undefined}));assert.throws(()=>expense(state,{...payload,value:21}));const cancelled=cancelExpense(saved,saved.expenses[0].id);assert.equal(cashSummary(cancelled.cashSessions[0]).expectedCents,1500);assert.equal(movementSummary([],cancelled.expenses).expenseCents,500);
});
test('conferência divergente exige motivo, fecha definitivamente e mantém primeiro resultado no replay',()=>{
 const state=opened(),sessionId=state.cashSessions[0].id;const input={sessionId,countedValue:19,expectedCents:2000,responsible:'Pessoa',requestId:'close'};assert.throws(()=>cashAction(state,'close',input),/Explique/);const closed=cashAction(state,'close',{...input,note:'Faltou um real'});assert.equal(closed.cashSessions[0].closing.differenceCents,-100);assert.deepEqual(cashAction(closed,'close',{...input,note:'Faltou um real'}),closed);assert.throws(()=>cashAction(closed,'close',{...input,note:'Outro'}),/outros dados/);for(const route of ['supply','withdraw','refund'])assert.throws(()=>cashAction(closed,route,{sessionId,value:1,note:'Depois de fechar'}),/fechado/);assert.throws(()=>cashAction(state,'close',{...input,expectedCents:1900,note:'Diferença'}),/mudou/);
 const newSession=cashAction(closed,'open',{openingValue:10,responsible:'Outra pessoa',requestId:'open2'});assert.deepEqual(newSession.cashSessions[0],closed.cashSessions[0]);
});
test('devolução limitada ao dinheiro recebido; cancelar e receber após fechamento não reescreve sessão',()=>{
 const state=sale(opened(),{items:[{productId:'p',quantity:1}],paymentMethod:'cash',paymentStatus:'received'}),sessionId=state.cashSessions[0].id,saleId=state.sales[0].id;const closed=cashAction(state,'close',{sessionId,countedValue:30,responsible:'Pessoa',requestId:'close'}),before=structuredClone(closed.cashSessions[0]);let cancelled=change(closed,'/api/sales/cancel',{id:saleId});assert.deepEqual(cancelled.cashSessions[0],before);cancelled=cashAction(cancelled,'open',{openingValue:10,responsible:'Pessoa'});const refund={sessionId:cancelled.cashSessions[1].id,saleId,value:10,note:'=Devolução',requestId:'refund'};assert.throws(()=>cashAction(cancelled,'refund',{...refund,value:11}));const refunded=cashAction(cancelled,'refund',refund);assert.deepEqual(cashAction(refunded,'refund',refund),refunded);assert.deepEqual(refunded.cashSessions[0],before);assert.equal(movementSummary(refunded.sales,[]).differenceCents,0);assert.ok(cashReport(refunded.cashSessions[1]).includes("'=Devolução"));
});
test('precisão monetária vale para todas as operações de Caixa',()=>{
 for(const invalid of ['1.999','',null,[],true]){assert.throws(()=>cashAction(initial(),'open',{openingValue:invalid,responsible:'Pessoa'}));for(const route of ['supply','withdraw','close','refund'])assert.throws(()=>cashAction(opened(),route,{sessionId:'missing',value:invalid,countedValue:invalid,note:'Motivo',responsible:'Pessoa'}));}
});
