const {command,safe}=require('./commands');const {optional}=require('./domain');const {catalogVersion,audit}=require('./audit');
function tags(value){if(!Array.isArray(value)||value.length>20)throw Error('Use até 20 etiquetas.');const seen=new Set();return value.map(v=>optional(v,40)).filter(v=>v&&!seen.has(v.toLowerCase())&&seen.add(v.toLowerCase()));}
function catalogAction(state,action,input){return command(state,'catalog',action,input,(next,date)=>{
 const kind=input.kind;if(!['products','customers','suppliers'].includes(kind))throw Error('Tipo de cadastro inválido.');const records=next[kind]||[];
 if(action==='metadata'){
  const r=records.find(r=>r.id===input.id);if(!r)throw Error('Cadastro não encontrado.');catalogVersion(r,input);const before=structuredClone(r);
  const fields=kind==='products'?{unit:optional(input.unit,20),brand:optional(input.brand,80),location:optional(input.location,120),internalNote:optional(input.internalNote,1000)}:{address:optional(input.address,400),contactName:optional(input.contactName,120),commercialId:optional(input.commercialId,80)};
  if(fields.commercialId&&records.some(other=>other.id!==r.id&&(other.commercialId||'').toLowerCase()===fields.commercialId.toLowerCase())&&input.acknowledgeDuplicate!==true)throw Error('Outro cadastro usa este identificador comercial. Confira e reconheça a possível duplicidade.');Object.assign(r,fields,{tags:tags(input.tags||[])});r.version=(r.version||0)+1;r.updatedAt=date;audit(next,kind,r,before,input,date);
 }else if(action==='bulk'){
  if(!Array.isArray(input.items)||!input.items.length||input.items.length>500||new Set(input.items.map(i=>i.id)).size!==input.items.length)throw Error('Selecione até 500 cadastros sem repetir.');const label=optional(input.tag,40);if(input.tagMode&&!['add','remove'].includes(input.tagMode)||input.tagMode&&!label)throw Error('Informe etiqueta e operação.');if(kind!=='products'&&(input.category!==undefined||input.location!==undefined))throw Error('Categoria e localização pertencem aos produtos.');
  for(const i of input.items){const r=records.find(r=>r.id===i.id);if(!r)throw Error('Cadastro não encontrado.');catalogVersion(r,{expectedVersion:i.expectedVersion});const before=structuredClone(r);if(input.category!==undefined)r.category=optional(input.category,60);if(input.location!==undefined)r.location=optional(input.location,120);if(input.tagMode==='add')r.tags=tags([...(r.tags||[]),label]);if(input.tagMode==='remove')r.tags=(r.tags||[]).filter(t=>t.toLowerCase()!==label.toLowerCase());r.version=(r.version||0)+1;r.updatedAt=date;audit(next,kind,r,before,input,date);}
 }else throw Error('Ação de cadastro inválida.');
});}
function duplicateContacts(rows){const issues=[];for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++){const a=rows[i],b=rows[j],phone=String(a.phone||'').replace(/\D/g,''),email=String(a.email||'').trim().toLowerCase();if(phone.length>=6&&phone===String(b.phone||'').replace(/\D/g,'')||email&&email===String(b.email||'').trim().toLowerCase())issues.push({firstId:a.id,secondId:b.id,firstName:a.name,secondName:b.name});}return issues;}
module.exports={catalogAction,duplicateContacts,tags};
