const {randomUUID}=require('crypto');
const {run,record,expected,text,integer,reason,baseRecord,touch}=require('./advanced-common');
const {audit}=require('./audit');
function allCodes(state){return state.products.flatMap(p=>[{productId:p.id,name:p.name,code:p.code,kind:'Código interno'},{productId:p.id,name:p.name,code:p.barcode,kind:'Código de barras'},...(p.aliases||[]).map(a=>({...a,productId:p.id,name:p.name,kind:'Identificador'})),...(p.packages||[]).map(a=>({...a,productId:p.id,name:p.name,kind:'Embalagem'}))]).filter(a=>a.code);}
function exclusiveCode(state,code,ignoredId){if(!code||code.length>64||!/^[!-~]+$/.test(code))throw Error('Use um código textual sem espaços, até 64 caracteres.');const conflict=allCodes(state).find(c=>c.id!==ignoredId&&c.code.toLowerCase()===code.toLowerCase());if(conflict)throw Error('Código reservado: '+conflict.name+' · '+conflict.kind+'. Inclui inativos.');}
function catalogueNext(state,kind,action,input){return run(state,kind,action,input,(next,date)=>{
 if(kind==='packages'||kind==='aliases'){
  const p=record(next,'products',input.productId);expected(p,input);const before=structuredClone(p);p[kind]||=[];const r=action==='create'?null:p[kind].find(a=>a.id===input.id);if(action!=='create'&&!r)throw Error('Identificador não encontrado.');
  if(action==='active'||action==='remove'){if(typeof input.active!=='boolean'&&action!=='remove')throw Error('Escolha a situação.');r.active=action==='remove'?false:input.active;r.version++;r.history.push({date,action,reason:reason(input),responsible:text(input.responsible,120,'Responsável')});}
  else if(action==='create'||action==='edit'){const name=text(input.name,120,'Nome',true),code=text(input.code,64,'Código',kind==='aliases');if(code)exclusiveCode(next,code,r?.id);const fields={name,code,active:r?.active??true,...(kind==='packages'?{factor:integer(input.factor,'Unidades-base',1,1000000),unit:'unidade'}:{})};if(kind==='packages'&&!Number.isSafeInteger(p.priceCents*fields.factor))throw Error('Preço derivado da embalagem fora do limite.');if(r){if(r.code&&r.code!==code)throw Error('Conserve o código reservado. Desative e crie outro identificador.');const previous=structuredClone(r);Object.assign(r,fields);r.version++;r.history.push({date,action,previous,reason:reason(input)});}else p[kind].push({id:randomUUID(),version:1,date,history:[{date,action,responsible:text(input.responsible,120,'Responsável')}],...fields});}
  else throw Error('Ação de identificador inválida.');p.version=(p.version||0)+1;p.updatedAt=date;audit(next,'products',p,before,input,date);return;
 }
 if(kind!=='families')throw Error('Cadastro inválido.');let r=action==='create'?null:record(next,'families',input.id);if(r)expected(r,input);
 if(action==='create'||action==='edit'){
  const attributes=input.attributes||[];if(!Array.isArray(attributes)||attributes.length>8||new Set(attributes.map(a=>String(a).trim().toLowerCase())).size!==attributes.length)throw Error('Use até 8 atributos com nomes diferentes.');const fields={name:text(input.name,120,'Família',true),description:text(input.description,1000,'Descrição'),attributes:attributes.map(a=>text(a,40,'Atributo',true)),active:r?.active??true};if(r){Object.assign(r,fields);touch(r,date,action,{...input,reason:reason(input)});}else next.families.push(baseRecord(next,'families',date,input,fields));
 }else if(action==='active'){if(typeof input.active!=='boolean')throw Error('Escolha a situação.');r.active=input.active;touch(r,date,action,{...input,reason:reason(input)});}
 else if(action==='members'){
  if(!r.active)throw Error('Reative a família.');if(!Array.isArray(input.items)||!input.items.length||input.items.length>500||new Set(input.items.map(i=>i.productId)).size!==input.items.length)throw Error('Selecione de 1 a 500 SKUs distintos.');
  for(const i of input.items){const p=record(next,'products',i.productId);if((p.version||0)!==i.expectedVersion)throw Error('SKU mudou: '+p.name);const before=structuredClone(p);p.familyId=r.id;p.familyAttributes=Object.fromEntries(r.attributes.map(name=>[name,text(i.attributes?.[name],80,'Valor do atributo')]));const signature=JSON.stringify(p.familyAttributes);if(Object.values(p.familyAttributes).some(Boolean)&&next.products.some(o=>o.id!==p.id&&o.familyId===r.id&&JSON.stringify(Object.fromEntries(r.attributes.map(a=>[a,o.familyAttributes?.[a]||''])))===signature)&&input.acknowledgeDuplicate!==true)throw Error('Combinação repetida de atributos. Reconheça para manter SKUs distintos.');p.version=(p.version||0)+1;audit(next,'products',p,before,input,date);}touch(r,date,action,input);
 }else if(action==='remove'){const p=record(next,'products',input.productId);if(p.familyId!==r.id||(p.version||0)!==input.productVersion)throw Error('Vínculo do produto mudou.');delete p.familyId;delete p.familyAttributes;p.version=(p.version||0)+1;touch(r,date,action,{...input,reason:reason(input)});}
 else if(action==='substitute'){
  const p=record(next,'products',input.productId),other=record(next,'products',input.substituteId);if(p.id===other.id)throw Error('Escolha outro SKU.');if((p.version||0)!==input.productVersion)throw Error('Produto mudou.');p.substitutes||=[];if(input.remove){p.substitutes=p.substitutes.filter(a=>a.productId!==other.id);reason(input);}else{if(p.substitutes.some(a=>a.productId===other.id))throw Error('Alternativa já cadastrada.');p.substitutes.push({productId:other.id,note:text(input.note,500,'Observação'),date});}p.version=(p.version||0)+1;touch(r,date,action,input);
 }else throw Error('Ação de família inválida.');
 });}
function packagingSnapshot(p,item,historical=false){
 const entries=item.packages||[];if(!Array.isArray(entries)||entries.length>100)throw Error('Embalagens inválidas.');let units=0;return entries.map(i=>{const pack=(p.packages||[]).find(a=>a.id===i.packageId);if(!historical&&(!pack||pack.active===false||pack.version!==i.version||pack.factor!==i.factor))throw Error('Embalagem mudou. Confira a equivalência antes de confirmar: '+p.name);const factor=integer(i.factor,'Equivalência'),count=integer(i.count,'Embalagens'),quantity=factor*count;if(!Number.isSafeInteger(quantity)||!Number.isSafeInteger(units+=quantity)||units>item.quantity)throw Error('Equivalência acima da quantidade-base.');return {packageId:i.packageId,name:historical?text(i.name,120,'Nome',true):pack.name,factor,count,version:i.version};});
}
function catalogueReference(state,id){const p=record(state,'products',typeof id==='object'?id.id:id);return {id:p.id,name:p.name,code:p.code||''};}
module.exports={catalogueNext,allCodes,exclusiveCode,packagingSnapshot,catalogueReference};
