const {randomUUID}=require('crypto');
const {run,record,expected,text,integer,reason,baseRecord,touch,safe}=require('./advanced-common');
const {distribution,positionQuantity,positionToken,consumption}=require('./public/positions-core');
function validPosition(state,id){if(id==='')return {id:'',name:'Não distribuído'};const r=record(state,'positions',id,true);return r;}
function transferBalances(state,items,from,to,date,referenceId,why){validPosition(state,from);validPosition(state,to);if(from===to)throw Error('Escolha posições diferentes.');for(const i of items){const p=record(state,'products',i.productId),q=integer(i.quantity,'Quantidade');if(positionToken(p)!==i.expectedPositionToken)throw Error('Distribuição mudou: '+p.name+'. Reabra a revisão.');if(q>positionQuantity(state,p,from))throw Error('Saldo insuficiente na origem: '+p.name);p.positionBalances||={};if(from)p.positionBalances[from]=(p.positionBalances[from]||0)-q;if(to)p.positionBalances[to]=safe((p.positionBalances[to]||0)+q,'Distribuição');distribution(state,p);state.positionMovements||=[];state.positionMovements.push({id:randomUUID(),date,productId:p.id,productName:p.name,from,to,fromName:validPosition(state,from).name,toName:validPosition(state,to).name,quantity:q,referenceId,reason:why,type:'transfer'});}}
function positionAction(state,kind,action,input){return run(state,kind,action,input,(next,date)=>{
 const r=action==='create'?null:record(next,kind,input.id);if(r)expected(r,input);
 if(kind==='positions'){
  if(action==='create'||action==='edit'){const code=text(input.code,40,'Código',true),name=text(input.name,120,'Nome',true);if(next.positions.some(p=>p.id!==r?.id&&p.code.toLowerCase()===code.toLowerCase()))throw Error('Código de posição já reservado, incluindo inativos.');if(r){Object.assign(r,{code,name});touch(r,date,action,{...input,reason:reason(input)});}else next.positions.push(baseRecord(next,'positions',date,input,{code,name,active:true}));}
  else if(action==='active'){if(typeof input.active!=='boolean')throw Error('Escolha a situação.');if(!input.active&&next.products.some(p=>(p.positionBalances?.[r.id]||0)>0))throw Error('Esvazie a posição antes de desativá-la.');r.active=input.active;touch(r,date,action,{...input,reason:reason(input)});}else throw Error('Ação de posição inválida.');return;
 }
 if(kind!=='transfers')throw Error('Operação física inválida.');
 if(action==='create'||action==='edit'){
  if(r&&(r.confirmedAt||r.cancelledAt))throw Error('Transferência concluída não pode ser editada.');validPosition(next,input.from);validPosition(next,input.to);if(input.from===input.to)throw Error('Escolha origem e destino diferentes.');if(!Array.isArray(input.items)||!input.items.length||input.items.length>500||new Set(input.items.map(i=>i.productId)).size!==input.items.length)throw Error('Selecione produtos distintos.');const fields={from:input.from,to:input.to,fromName:validPosition(next,input.from).name,toName:validPosition(next,input.to).name,items:input.items.map(i=>({productId:record(next,'products',i.productId).id,name:record(next,'products',i.productId).name,quantity:integer(i.quantity,'Quantidade')})),reason:reason(input)};if(r){Object.assign(r,fields);touch(r,date,action,input);}else next.transfers.push(baseRecord(next,'transfers',date,input,fields));
 }else if(action==='confirm'){if(r.confirmedAt||r.cancelledAt)throw Error('Transferência já encerrada.');transferBalances(next,r.items.map(i=>({...i,expectedPositionToken:input.expectedPositions?.[i.productId]})),r.from,r.to,date,r.id,r.reason);r.confirmedAt=date;touch(r,date,action,input);}
 else if(action==='cancel'){if(r.confirmedAt||r.cancelledAt)throw Error('Use compensação para uma transferência confirmada.');r.cancelledAt=date;touch(r,date,action,{...input,reason:reason(input)});}
 else if(action==='reverse'){if(!r.confirmedAt||r.reversedAt)throw Error('Selecione transferência confirmada ainda não revertida.');const why=reason(input),comp=baseRecord(next,'transfers',date,input,{from:r.to,to:r.from,fromName:r.toName,toName:r.fromName,items:structuredClone(r.items),reason:why,reversalOf:r.id,confirmedAt:date});transferBalances(next,comp.items.map(i=>({...i,expectedPositionToken:input.expectedPositions?.[i.productId]})),comp.from,comp.to,date,comp.id,why);next.transfers.push(comp);r.reversedAt=date;r.reversalId=comp.id;touch(r,date,action,input);}else throw Error('Ação de transferência inválida.');
 });}
function reconcilePositions(previous,next,input={}){
 if(!(next.positions||[]).length)return next;const oldIds=new Set((previous.stockMovements||[]).map(m=>m.id)),stocks=new Map(previous.products.map(p=>[p.id,p.stock]));next.positionMovements||=[];
 for(const m of (next.stockMovements||[]).filter(m=>!oldIds.has(m.id))){const p=record(next,'products',m.productId),before=stocks.get(p.id)||0,q=m.quantity;if(!q){stocks.set(p.id,before);continue;}if(m.positionHandled){stocks.set(p.id,safe(before+q,'Estoque'));continue;}const temp={...p,stock:before};p.positionBalances||={};const selected=(input.items||[]).find(i=>i.productId===p.id)||{};let allocations=[];
  if(q<0){const held=m.type==='quarantine'?next.quarantineEntries?.find(r=>r.id===m.referenceId):null;const receiptHeld=held?.origin?.kind==='purchases';const source=receiptHeld?'':selected.sourcePositionId??input.sourcePositionId;if(source!==undefined){if(!receiptHeld&&input.expectedPositions?.[p.id]!==positionToken(temp))throw Error('Distribuição mudou. Confira a origem física.');validPosition(next,source);}allocations=consumption(next,temp,-q,source);for(const a of allocations)if(a.positionId)p.positionBalances[a.positionId]=(p.positionBalances[a.positionId]||0)-a.quantity;}
  else if(m.type==='cancel'){
   const sale=next.sales.find(s=>s.id===m.referenceId),original=sale?.items.find(i=>i.productId===p.id)?.stockSources;let remaining=q;for(const a of original||[]){const qty=Math.min(a.quantity,remaining),active=!a.positionId||(next.positions||[]).some(r=>r.id===a.positionId&&r.active!==false),destination=active?a.positionId:'';if(qty){allocations.push({positionId:destination,name:active?a.name:'Não distribuído (origem desativada)',quantity:qty});if(destination)p.positionBalances[destination]=safe((p.positionBalances[destination]||0)+qty);remaining-=qty;}}if(remaining)allocations.push({positionId:'',name:'Não distribuído',quantity:remaining});
  }else{
   const destination=m.destinationPositionId??selected.destinationPositionId??input.destinationPositionId??'';const dest=validPosition(next,destination);const receipt=m.type==='purchase'?next.purchases?.flatMap(r=>r.receipts).find(r=>r.id===m.referenceId):null;const held=receipt?.items.find(i=>i.productId===p.id)?.quarantineQuantity||0;allocations=[...(q-held?[{positionId:destination,name:dest.name,quantity:q-held}]:[]),...(held?[{positionId:'',name:'Não distribuído (antes da retenção)',quantity:held}]:[])];if(destination)p.positionBalances[destination]=safe((p.positionBalances[destination]||0)+q-held);
  }
  stocks.set(p.id,safe(before+q,'Estoque'));m.positionAllocations=allocations;for(const a of allocations)next.positionMovements.push({id:randomUUID(),date:m.date,productId:p.id,productName:p.name,from:q<0?a.positionId:null,to:q>0?a.positionId:null,fromName:q<0?a.name:null,toName:q>0?a.name:null,quantity:a.quantity,referenceId:m.referenceId,stockMovementId:m.id,reason:m.note||'',type:m.type});
  if(m.type==='sale'){const line=next.sales.find(s=>s.id===m.referenceId)?.items.find(i=>i.productId===p.id);if(line)line.stockSources=allocations;}
 }
 for(const p of next.products){distribution(next,p);if(stocks.has(p.id)&&stocks.get(p.id)!==p.stock)throw Error('Movimentações físicas não reconciliadas: '+p.name);}
 return next;
}
module.exports={positionAction,reconcilePositions,transferBalances,validPosition};
