const {run,record,expected,text,reason,baseRecord,touch,cents,safe}=require('./advanced-common');const {priceReference,priceReviewRows,proposedPrice}=require('./public/price-review-core');const {audit}=require('./audit');
function priceReviewAction(state,action,input){return run(state,'priceReviews',action,input,(next,date)=>{
 let r=action==='create'?null:record(next,'priceReviews',input.id);if(r)expected(r,input);
 if(action==='create'){
  if(!['standard','list'].includes(input.target))throw Error('Escolha padrão ou lista.');const listId=input.target==='list'?input.listId:null;if(!Array.isArray(input.productIds)||!input.productIds.length||input.productIds.length>500||new Set(input.productIds).size!==input.productIds.length)throw Error('Selecione até 500 produtos distintos.');const items=input.productIds.map(id=>{const p=record(next,'products',id,true),ref=priceReference(next,input.target,listId,p);return {...ref,proposedPriceCents:ref.basePriceCents,reductionReason:''};});next.priceReviews.push(baseRecord(next,'priceReviews',date,input,{name:text(input.name,120,'Nome da proposta',true),target:input.target,listId,listName:listId?record(next,'priceLists',listId).name:null,items,reason:text(input.reason,1000,'Motivo')}));return;
 }
 if(action==='reverse'){
  if(!r.appliedAt)throw Error('Reversão exige lote aplicado.');const rows=priceReviewRows(next,r);const changed=rows.some(i=>{const applied=r.appliedSnapshots.find(a=>a.productId===i.productId);return i.current.basePriceCents!==applied.appliedPriceCents||i.current.productVersion!==applied.productVersionAfter||i.current.targetVersion!==applied.targetVersionAfter;});if(changed&&input.acknowledgeChanged!==true)throw Error('Houve alterações posteriores. Reconheça e confira as novas referências antes de propor a reversão.');const items=r.appliedSnapshots.map(i=>{const p=record(next,'products',i.productId,true),ref=priceReference(next,r.target,r.listId,p);return {...ref,proposedPriceCents:i.wasAbsent?p.priceCents:i.previousPriceCents,restoreAbsence:i.wasAbsent,reductionReason:reason(input)};});next.priceReviews.push(baseRecord(next,'priceReviews',date,input,{name:'Reversão de '+r.name,target:r.target,listId:r.listId,listName:r.listName,items,reversalOf:r.id,reason:reason(input)}));return;
 }
 if(r.appliedAt||r.cancelledAt)throw Error('Proposta aplicada ou cancelada conserva seu histórico.');
 if(action==='edit'||action==='simulate'){
  if(!Array.isArray(input.items)||!input.items.length||new Set(input.items.map(i=>i.productId)).size!==input.items.length)throw Error('Escolha itens distintos da proposta.');const changes=[];for(const entry of input.items){const i=r.items.find(a=>a.productId===entry.productId);if(!i)throw Error('Produto fora da proposta.');const before=i.proposedPriceCents,computed=action==='simulate'?proposedPrice(i.proposedPriceCents,input.mode,input.value,Number(input.rounding||1)):{priceCents:cents(entry.value,true),roundingDifferenceCents:0,rawCents:cents(entry.value,true)},p=record(next,'products',i.productId);if(p.minimumPriceCents!==undefined&&computed.priceCents<p.minimumPriceCents)throw Error('Proposta abaixo do mínimo informativo: '+p.name+'.');i.proposedPriceCents=computed.priceCents;i.reductionReason=text(entry.reductionReason??input.reason??i.reductionReason,1000,'Motivo da redução');i.roundingDifferenceCents=computed.roundingDifferenceCents;i.rawProposedCents=computed.rawCents;delete i.restoreAbsence;changes.push({productId:i.productId,before,after:i.proposedPriceCents});}touch(r,date,action,input,{changes});
 }else if(action==='remove'){const i=r.items.find(a=>a.productId===input.productId);if(!i)throw Error('Produto fora da proposta.');if(r.items.length===1)throw Error('Mantenha pelo menos um item ou cancele a proposta.');r.items=r.items.filter(a=>a!==i);touch(r,date,action,{...input,reason:reason(input)},{removed:i});}
 else if(action==='add'){if(!Array.isArray(input.productIds)||!input.productIds.length||r.items.length+input.productIds.length>500||new Set(input.productIds).size!==input.productIds.length)throw Error('Escolha produtos distintos, até 500 no lote.');if(r.target==='list'&&record(next,'priceLists',r.listId).version!==r.items[0].targetVersion)throw Error('Lista mudou. Atualize referências antes de acrescentar.');for(const id of input.productIds){if(r.items.some(i=>i.productId===id))throw Error('Produto já na proposta.');const ref=priceReference(next,r.target,r.listId,record(next,'products',id,true));r.items.push({...ref,proposedPriceCents:ref.basePriceCents,reductionReason:''});}touch(r,date,action,input);}
 else if(action==='refresh'){const previous=structuredClone(r.items);for(const i of r.items){const ref=priceReference(next,r.target,r.listId,record(next,'products',i.productId,true));Object.assign(i,ref);}touch(r,date,action,{...input,reason:reason(input)},{previous});}
 else if(action==='apply'){
  const rows=priceReviewRows(next,r);if(rows.some(i=>i.conflict))throw Error('Produtos ou lista mudaram. Atualize referências explicitamente e revise valores propostos.');if(rows.some(i=>i.minimumConflict))throw Error('Proposta abaixo do mínimo. Revise o conjunto.');if(rows.some(i=>i.proposedPriceCents<i.basePriceCents&&!i.reductionReason.trim()))throw Error('Justifique cada redução de preço.');const why=reason(input),list=r.target==='list'?record(next,'priceLists',r.listId,true):null;r.appliedSnapshots=[];
  for(const i of rows){const p=record(next,'products',i.productId,true),before=structuredClone(p);if(list){const line=list.items.find(a=>a.productId===p.id);if(i.restoreAbsence)list.items=list.items.filter(a=>a.productId!==p.id);else if(line)line.priceCents=i.proposedPriceCents;else list.items.push({productId:p.id,name:p.name,priceCents:i.proposedPriceCents});}else{p.priceCents=i.proposedPriceCents;p.version=(p.version||0)+1;p.updatedAt=date;audit(next,'products',p,before,{...input,reason:why},date);}r.appliedSnapshots.push({productId:p.id,name:p.name,previousPriceCents:i.basePriceCents,appliedPriceCents:i.proposedPriceCents,wasAbsent:i.wasAbsent,productVersionAfter:p.version||0,targetVersionAfter:list?list.version+1:null});}if(list)touch(list,date,'review',input,{reviewId:r.id,reason:why});r.appliedAt=date;r.applyReason=why;touch(r,date,action,input);
 }else if(action==='cancel'){r.cancelledAt=date;touch(r,date,action,{...input,reason:reason(input)});}else throw Error('Ação de revisão de preço inválida.');
 });}
module.exports={priceReviewAction};
