const {randomUUID}=require('crypto');const {run,record,expected,text,reason,baseRecord,touch,dateOnly}=require('./advanced-common');
const pages=['sales','products','customers','suppliers','purchases','payables','cashPage','inventories','quarantinePage','deliveriesPage','accountsPage','tasksPage','agreementsPage','recurringPage'];
function internalLink(state,value,allowed=['purchases','inventories','deliveries','cashSessions','sales','payables','tasks','quotes']){if(!value)return null;if(!allowed.includes(value.kind))throw Error('Tipo de referência interna inválido.');record(state,value.kind,value.id);return {kind:value.kind,id:value.id};}
function procedureAction(state,kind,action,input){return run(state,kind,action,input,(next,date)=>{
 const r=action==='create'?null:record(next,kind,input.id);if(r)expected(r,input);
 if(kind==='procedures'){
  if(action==='create'||action==='edit'){if(!Array.isArray(input.steps)||!input.steps.length||input.steps.length>30)throw Error('Use de 1 a 30 etapas ordenadas.');const steps=input.steps.map((s,i)=>{if(typeof s.required!=='boolean'||typeof s.requireReference!=='boolean')throw Error('Defina obrigatoriedade e referência da etapa.');if(s.page&&!pages.includes(s.page))throw Error('Rotina não disponível.');return {id:s.id||randomUUID(),number:i+1,name:text(s.name,120,'Etapa',true),guidance:text(s.guidance,1000,'Orientação'),suggestedOwner:text(s.suggestedOwner,120,'Responsável sugerido'),required:s.required,requireReference:s.requireReference,page:s.page||null};});if(new Set(steps.map(s=>s.id)).size!==steps.length)throw Error('Etapas repetidas.');const fields={name:text(input.name,120,'Nome',true),purpose:text(input.purpose,1000,'Finalidade'),steps};if(r){const previous={revision:r.revision,name:r.name,purpose:r.purpose,steps:structuredClone(r.steps)};r.revisions.push(previous);Object.assign(r,fields);r.revision++;touch(r,date,action,{...input,reason:reason(input)});}else next.procedures.push(baseRecord(next,kind,date,input,{...fields,revision:1,revisions:[],active:true}));}
  else if(action==='active'){if(typeof input.active!=='boolean')throw Error('Escolha a situação.');r.active=input.active;touch(r,date,action,{...input,reason:reason(input)});}else throw Error('Ação de procedimento inválida.');return;
 }
 if(kind!=='procedureExecutions')throw Error('Execução inválida.');
 if(action==='create'){const p=record(next,'procedures',input.procedureId,true);if(p.version!==input.expectedProcedureVersion)throw Error('Procedimento mudou. Confira a revisão.');next.procedureExecutions.push(baseRecord(next,kind,date,input,{procedureId:p.id,procedureName:p.name,procedureRevision:p.revision,purpose:p.purpose,targetDate:dateOnly(input.targetDate,'Data-alvo'),responsible:text(input.responsible,120,'Responsável',true),link:internalLink(next,input.link,['purchases','inventories','deliveries','cashSessions']),steps:p.steps.map(s=>({...s,status:'pending',references:[],history:[]}))}));return;}
 if(r.completedAt||r.cancelledAt)throw Error('Execução encerrada conserva etapas e documentos. Inicie nova execução.');
 if(action==='complete'){if(r.steps.some(s=>s.required&&s.status!=='completed'))throw Error('Conclua todas as etapas obrigatórias. Etapas opcionais pendentes serão declaradas no termo.');r.completedAt=date;touch(r,date,action,input);return;}
 if(action==='cancel'){r.cancelledAt=date;touch(r,date,action,{...input,reason:reason(input)});return;}
 const step=r.steps.find(s=>s.id===input.stepId);if(!step)throw Error('Etapa não encontrada.');const previous=step.status;
 if(action==='finish'){if(step.status==='blocked'||step.status==='completed')throw Error('Retome uma etapa impedida antes de concluí-la.');if(step.requireReference&&!step.references.length)throw Error('Esta etapa exige documento interno existente.');step.status='completed';step.completedAt=date;step.note=text(input.note,1000,'Observação');step.owner=text(input.owner,120,'Responsável',true);}
 else if(action==='block'){if(step.status==='completed')throw Error('Reabra a etapa concluída antes de declarar impedimento.');step.status='blocked';step.blockReason=reason(input);}
 else if(action==='resume'){if(step.status!=='blocked')throw Error('Etapa não está impedida.');step.status='pending';step.blockReason='';reason(input);}
 else if(action==='skip'){if(step.required)throw Error('Etapa obrigatória não pode ser pulada.');step.status='skipped';step.skipReason=reason(input);}
 else if(action==='reopen'){if(!['completed','skipped'].includes(step.status))throw Error('Etapa já está aberta.');step.status='pending';reason(input);}
 else if(action==='reference'){const link=internalLink(next,input.link);if(!link)throw Error('Selecione referência existente.');if(step.references.length>=20)throw Error('Use até 20 referências por etapa.');if(step.references.some(r=>r.kind===link.kind&&r.id===link.id))throw Error('Referência já vinculada.');step.references.push({...link,date});}
 else if(action==='task'){if(step.status!=='blocked'||step.taskId)throw Error('Crie acompanhamento para etapa impedida ainda sem tarefa.');next.tasks||=[];const task={id:randomUUID(),number:require('./commands').nextNumber(next.tasks),date,updatedAt:date,version:1,title:text(input.title,160,'Título',true),responsible:text(input.responsible,120,'Responsável'),dueDate:dateOnly(input.dueDate,'Prazo'),note:step.blockReason,priority:'normal',link:{kind:'procedureExecutions',id:r.id},history:[{date,action:'create'}]};next.tasks.push(task);step.taskId=task.id;}else throw Error('Ação de etapa inválida.');
 step.history.push({date,action,previous,status:step.status,reason:input.reason?reason(input):'',responsible:text(input.owner||input.responsible,120,'Responsável'),note:step.note||'',reference:action==='reference'?structuredClone(step.references.at(-1)):null});touch(r,date,action,input,{stepId:step.id});
 });}
module.exports={procedureAction,internalLink,pages};
