const {test}=require('node:test'),assert=require('node:assert/strict');
const {supplierAction,purchaseAction}=require('./purchases');
const {purchasedQuantity,purchaseSummary,purchaseStatus,purchaseLate,latestPurchaseCosts}=require('./public/purchases-core');
const {sale,change}=require('./server'),{activeAction}=require('./quotes'),{exportCsv}=require('./export'),{cashAction}=require('./cash');
const initial=()=>({products:[{id:'p',name:'Camisa',stock:2,priceCents:5000},{id:'b',name:'Bolsa',stock:0,priceCents:8000}],customers:[],sales:[],suppliers:[{id:'f',name:'Fornecedor original'}]});
const create=(db,input={})=>purchaseAction(db,'create',{supplierId:'f',items:[{productId:'p',quantity:4,unitCost:'19.90'},{productId:'b',quantity:2,unitCost:'30.00'}],...input});
const act=(db,action,input={})=>purchaseAction(db,action,{id:db.purchases[0].id,expectedVersion:db.purchases[0].version,...input});
test('fornecedor valida contatos, persiste snapshots e protege reenvio de cadastro',()=>{
 const db=initial(),input={name:'Fabricante',phone:'123',email:'loja@exemplo.com',notes:'Contato',requestId:'supplier'};const next=supplierAction(db,'create',input);assert.equal(next.suppliers.length,2);assert.deepEqual(supplierAction(next,'create',input),next);assert.throws(()=>supplierAction(next,'create',{...input,name:'Outro'}),/outros dados/);for(const data of [{name:''},{name:'a'.repeat(121)},{name:'Teste',email:'invalido'},{name:'Teste',phone:'1'.repeat(41)}])assert.throws(()=>supplierAction(db,'create',data));
 const ordered=create(db),edited=supplierAction(ordered,'edit',{id:'f',name:'Nome alterado',expectedVersion:0});assert.equal(edited.purchases[0].supplierName,'Fornecedor original');assert.equal(edited.suppliers[0].name,'Nome alterado');
});
test('preparar e confirmar pedido não altera estoque, despesas, dinheiro ou preço de venda',()=>{
 const db=initial(),next=create(db,{requestId:'create'});assert.equal(next.purchases[0].totalCents,13960);assert.equal(purchaseStatus(next.purchases[0]),'draft');assert.deepEqual(next.products,db.products);assert.deepEqual(next.sales,[]);assert.equal(next.cashSessions,undefined);assert.equal(next.expenses,undefined);assert.deepEqual(create(next,{requestId:'create'}),next);assert.equal(db.purchases,undefined);
 const confirmed=act(next,'confirm',{requestId:'confirm'});assert.equal(purchaseStatus(confirmed.purchases[0]),'pending');assert.deepEqual(confirmed.products,db.products);assert.deepEqual(purchaseAction(confirmed,'confirm',{id:confirmed.purchases[0].id,expectedVersion:1,requestId:'confirm'}),confirmed);assert.throws(()=>act(confirmed,'edit',{supplierId:'f',items:[{productId:'p',quantity:1,unitCost:'1.00'}]}));
});
test('edição de preparação atualiza custos e previsão mantendo criação; versão velha recusada',()=>{
 const db=create(initial()),date=db.purchases[0].date,next=act(db,'edit',{supplierId:'f',items:[{productId:'p',quantity:3,unitCost:'10.01'}],expectedDate:'2027-01-01',note:'Novo prazo'});assert.equal(next.purchases[0].date,date);assert.equal(next.purchases[0].version,2);assert.equal(next.purchases[0].totalCents,3003);assert.throws(()=>act(next,'edit',{expectedVersion:1,supplierId:'f',items:[{productId:'p',quantity:1,unitCost:'1.00'}]}),/outra janela/);assert.equal(db.purchases[0].version,1);
});
test('produto e fornecedor inativos impedem novo pedido e confirmação, mas não entrega de confirmado',()=>{
 const db=create(initial()),inactive=supplierAction(db,'active',{id:'f',active:false,expectedVersion:0});assert.throws(()=>create(inactive),/ativo/);assert.throws(()=>act(inactive,'confirm'),/Reative/);assert.throws(()=>create(activeAction(initial(),'products',{id:'p',active:false,expectedVersion:0})),/ativos/);
 let confirmed=act(db,'confirm');confirmed=activeAction(confirmed,'products',{id:'p',active:false,expectedVersion:0});confirmed=supplierAction(confirmed,'active',{id:'f',active:false,expectedVersion:0});const received=act(confirmed,'receive',{items:[{productId:'p',quantity:1}]});assert.equal(received.products[0].stock,3);assert.equal(received.suppliers[0].active,false);assert.equal(received.products[0].active,false);
});
test('recebimento parcial e integral calcula saldo e histórico sem movimentar financeiro',()=>{
 const ordered=act(create(initial()),'confirm'),partial=act(ordered,'receive',{items:[{productId:'p',quantity:2},{productId:'b',quantity:1}],note:'Primeira entrega',requestId:'receive'});const p=partial.purchases[0];assert.equal(purchaseStatus(p),'partial');assert.equal(partial.products[0].stock,4);assert.equal(partial.products[1].stock,1);assert.equal(p.receipts.length,1);assert.equal(purchasedQuantity(p,'p'),2);assert.equal(purchaseSummary(p).receivedCents,6980);assert.equal(purchaseSummary(p).pendingCents,6980);assert.equal(partial.stockMovements.length,2);assert.equal(partial.stockMovements[0].stockAfter,4);assert.equal(partial.stockMovements[0].purchaseId,p.id);assert.equal(partial.cashSessions,undefined);assert.equal(partial.expenses,undefined);assert.deepEqual(partial.sales,[]);
 const full=act(partial,'receive',{items:[{productId:'p',quantity:2},{productId:'b',quantity:1}],requestId:'receive2'});assert.equal(purchaseStatus(full.purchases[0]),'received');assert.equal(purchaseSummary(full.purchases[0]).pendingCents,0);assert.equal(full.products[0].priceCents,5000);assert.throws(()=>act(full,'receive',{items:[{productId:'p',quantity:1}]}));
});
test('recebimento idempotente e versão impedem duplicação e excesso; falhas são atômicas',()=>{
 const db=act(create(initial()),'confirm'),input={id:db.purchases[0].id,expectedVersion:2,items:[{productId:'p',quantity:1}],note:'Nota',requestId:'receive'};const next=purchaseAction(db,'receive',input);assert.deepEqual(purchaseAction(next,'receive',input),next);assert.throws(()=>purchaseAction(next,'receive',{...input,items:[{productId:'p',quantity:2}]}),/outros dados/);assert.throws(()=>act(next,'receive',{expectedVersion:2,items:[{productId:'p',quantity:1}]}),/outra janela/);
 for(const items of [[],[{productId:'p',quantity:5}],[{productId:'p',quantity:0}],[{productId:'p',quantity:1.5}],[{productId:'p',quantity:1},{productId:'b',quantity:3}],[{productId:'p',quantity:1},{productId:'p',quantity:1}],[{productId:'other',quantity:1}]]){const before=structuredClone(db);assert.throws(()=>act(db,'receive',{items}));assert.deepEqual(db,before);}
 const overflow=structuredClone(db);overflow.products[0].stock=Number.MAX_SAFE_INTEGER;assert.throws(()=>act(overflow,'receive',{items:[{productId:'p',quantity:1}]}),/Estoque/);assert.equal(overflow.purchases[0].receipts.length,0);
});
test('encerrar saldo preserva recebido e motivo; cancelar sem entrega não cria movimento',()=>{
 const db=act(create(initial()),'confirm'),partial=act(db,'receive',{items:[{productId:'p',quantity:1}]}),closed=act(partial,'close',{reason:'Fornecedor não entregará restante',requestId:'close'});assert.equal(purchaseStatus(closed.purchases[0]),'closed');assert.equal(closed.products[0].stock,3);assert.equal(closed.purchases[0].closedPendingQuantity,5);assert.equal(closed.purchases[0].closedPendingCents,11970);assert.equal(closed.purchases[0].receipts.length,1);assert.throws(()=>act(closed,'receive',{items:[{productId:'p',quantity:1}]}));assert.deepEqual(purchaseAction(closed,'close',{id:closed.purchases[0].id,expectedVersion:partial.purchases[0].version,reason:'Fornecedor não entregará restante',requestId:'close'}),closed);
 const cancelled=act(db,'close',{reason:'Cancelamento acordado'});assert.equal(purchaseStatus(cancelled.purchases[0]),'cancelled');assert.deepEqual(cancelled.products,db.products);assert.equal(cancelled.stockMovements,undefined);assert.throws(()=>act(db,'close',{reason:' '}));
});
test('duplicação começa em preparação sem entregas; último custo considera só compras recebidas',()=>{
 let db=act(create(initial()),'confirm');db=act(db,'receive',{items:[{productId:'p',quantity:1}]});const source=db.purchases[0],copy=create(db,{sourceId:source.id,items:source.items.map(i=>({productId:i.productId,quantity:i.quantity,unitCost:(i.unitCostCents/100).toFixed(2)}))});assert.equal(copy.purchases[1].number,2);assert.equal(copy.purchases[1].confirmedAt,undefined);assert.deepEqual(copy.purchases[1].receipts,[]);assert.equal(copy.purchases[1].sourceId,source.id);assert.equal(purchaseStatus(copy.purchases[1]),'draft');assert.deepEqual(latestPurchaseCosts(copy.purchases).map(c=>[c.productId,c.unitCostCents,c.supplierName]),[['p',1990,'Fornecedor original']]);
});
test('previsão de hoje não está vencida; compras encerradas e preparação não aguardam entrega',()=>{
 const db=act(create(initial(),{expectedDate:'2026-09-30'}),'confirm');assert.equal(purchaseLate(db.purchases[0],'2026-09-30'),false);assert.equal(purchaseLate(db.purchases[0],'2026-10-01'),true);assert.equal(purchaseLate(act(db,'close',{reason:'Encerrado'}).purchases[0],'2026-10-01'),false);assert.equal(purchaseLate(create(initial(),{expectedDate:'2000-01-01'}).purchases[0]),false);
});
test('CSV distingue pedido recebido e não entregue, preserva seleção e protege fórmulas',()=>{
 const db=act(act(create(initial(),{note:'=HYPERLINK("x")'}),'confirm'),'receive',{items:[{productId:'p',quantity:1}]});const csv=exportCsv(db,'purchases',[db.purchases[0].id]).body;assert.ok(csv.startsWith('\uFEFF'));assert.ok(csv.includes('139,60'));assert.ok(csv.includes('19,90'));assert.ok(csv.includes('119,70'));assert.ok(csv.includes("'=HYPERLINK"));assert.ok(csv.includes('Parcialmente recebido'));assert.equal(exportCsv(db,'purchases',[]).body.includes('CMP-'),false);
});
test('entradas recebidas podem ser vendidas normalmente; cancelamento da venda não desfaz entrega',()=>{
 let db=cashAction(initial(),'open',{responsible:'Loja',openingValue:'50.00'});const beforeCash=structuredClone(db.cashSessions);db=act(act(create(db),'confirm'),'receive',{items:[{productId:'b',quantity:1}]});assert.deepEqual(db.cashSessions,beforeCash);const sold=sale(db,{items:[{productId:'b',quantity:1}],paymentMethod:'pix',paymentStatus:'pending'});assert.equal(sold.products[1].stock,0);const cancelled=change(sold,'/api/sales/cancel',{id:sold.sales[0].id});assert.equal(cancelled.products[1].stock,1);assert.equal(purchasedQuantity(cancelled.purchases[0],'b'),1);
});
test('datas e custos com precisão inválida ou totais inseguros são recusados',()=>{
 for(const input of [{expectedDate:'2026-02-30'},{items:[]},{items:[{productId:'p',quantity:1,unitCost:'1.001'}]},{items:[{productId:'p',quantity:1,unitCost:'-1'}]},{items:[{productId:'p',quantity:Number.MAX_SAFE_INTEGER,unitCost:'100.00'}]}])assert.throws(()=>create(initial(),input));assert.equal(create(initial(),{items:[{productId:'p',quantity:1,unitCost:'0.00'}]}).purchases[0].totalCents,0);
});
