const {randomUUID}=require('crypto');
const {run,record,expected,text,integer,reason,baseRecord,touch,cents,safe,dateOnly}=require('./advanced-common');
const {purchaseAction}=require('./purchases');const {purchaseStatus,purchasedQuantity}=require('./public/purchases-core');const {calendarDay}=require('./public/reports');
function pending(p,id){const line=p.items.find(i=>i.productId===id);return line?line.quantity-purchasedQuantity(p,id):0;}
function purchaseNext(state,kind,action,input){return run(state,kind,action,input,(next,date)=>{
 let r=action==='create'?null:record(next,kind,input.id);if(r)expected(r,input);
 if(kind==='purchaseAmendments'){
  const p=record(next,'purchases',r?.purchaseId||input.purchaseId);if(!['pending','partial'].includes(purchaseStatus(p)))throw Error('Aditamento exige compra confirmada aguardando entrega.');
  if(action==='create'){if(p.version!==input.expectedPurchaseVersion)throw Error('Compra mudou.');if(!Array.isArray(input.items)||!input.items.length||new Set(input.items.map(i=>i.productId)).size!==input.items.length)throw Error('Selecione itens distintos do pedido.');const items=input.items.map(i=>{const original=p.items.find(a=>a.productId===i.productId);if(!original)throw Error('Aditamento só amplia SKU existente.');const cost=cents(i.unitCost,true);if(cost!==original.unitCostCents)throw Error('Aditamento de quantidade conserva o custo pedido. Declare diferença efetiva ao conferir a entrega.');return {productId:i.productId,name:original.name,extraQuantity:integer(i.quantity,'Quantidade adicional'),unitCostCents:cost};});next.purchaseAmendments.push(baseRecord(next,kind,date,input,{purchaseId:p.id,purchaseNumber:p.number,supplierId:p.supplierId,supplierName:p.supplierName,basePurchaseVersion:p.version,reason:reason(input),items,totalCents:safe(items.reduce((n,i)=>safe(n+safe(i.extraQuantity*i.unitCostCents)),0))}));}
  else if(action==='confirm'){if(r.confirmedAt||r.cancelledAt||p.version!==r.basePurchaseVersion||p.version!==input.expectedPurchaseVersion)throw Error('Aditamento ou compra mudou. Prepare outro após conferir.');p.originalOrder||={date:p.date,items:structuredClone(p.items),totalCents:p.totalCents};for(const i of r.items){const line=p.items.find(a=>a.productId===i.productId);line.quantity=safe(line.quantity+i.extraQuantity,'Quantidade');}p.totalCents=safe(p.totalCents+r.totalCents);p.amendmentIds||=[];p.amendmentIds.push(r.id);p.version++;p.updatedAt=date;r.confirmedAt=date;touch(r,date,action,input);}
  else if(action==='cancel'){if(r.confirmedAt||r.cancelledAt)throw Error('Aditamento já encerrado.');r.cancelledAt=date;touch(r,date,action,{...input,reason:reason(input)});}else throw Error('Ação de aditamento inválida.');return;
 }
 if(kind==='purchaseConferences'){
  const p=record(next,'purchases',r?.purchaseId||input.purchaseId);if(!['pending','partial'].includes(purchaseStatus(p)))throw Error('Compra não está aguardando entrega.');
  if(action==='create'){
   if(p.version!==input.expectedPurchaseVersion)throw Error('Compra mudou. Confira o saldo.');const declaredDate=dateOnly(input.declaredDate,'Data apresentada',true);if(declaredDate>calendarDay())throw Error('Entrega declarada não pode ser futura.');if(!Array.isArray(input.items)||!input.items.length||input.items.length>500||new Set(input.items.map(i=>i.productId)).size!==input.items.length)throw Error('Informe itens distintos do pedido.');
   const items=input.items.map(i=>{const original=p.items.find(a=>a.productId===i.productId);if(!original)throw Error('Registre produto diferente como ocorrência, sem entrada automática.');const presented=integer(i.presented,'Apresentada',0),sellable=integer(i.sellable,'Aceita vendável',0),held=integer(i.held,'Aceita retida',0),refused=integer(i.refused,'Recusada',0);if(safe(sellable+held+refused)!==presented)throw Error('Aceitas e recusadas precisam somar a quantidade apresentada.');if(held||refused)text(i.reason,1000,'Motivo por item',true);const unitCostCents=cents(i.unitCost,true);safe((sellable+held)*unitCostCents,'Custo aceito');if(unitCostCents!==original.unitCostCents)text(i.costReason,1000,'Diferença de custo',true);require('./positions').validPosition(next,i.destinationPositionId||'');return {productId:original.productId,name:original.name,presented,sellable,held,refused,originalUnitCostCents:original.unitCostCents,unitCostCents,costReason:text(i.costReason,1000,'Motivo do custo'),reason:text(i.reason,1000,'Motivo'),destinationPositionId:i.destinationPositionId||'',destinationPositionName:require('./positions').validPosition(next,i.destinationPositionId||'').name,pendingAtReview:pending(p,i.productId),missing:Math.max(0,pending(p,i.productId)-presented),excess:Math.max(0,presented-pending(p,i.productId))};});
   safe(items.reduce((n,i)=>safe(n+safe((i.sellable+i.held)*i.unitCostCents)),0),'Custo total aceito');const different=text(input.differentProduct,1000,'Produto diferente apresentado');if(!items.some(i=>i.presented)&&!different)throw Error('Informe mercadorias apresentadas ou ocorrência de produto diferente.');next.purchaseConferences.push(baseRecord(next,kind,date,input,{purchaseId:p.id,purchaseNumber:p.number,supplierId:p.supplierId,supplierName:p.supplierName,basePurchaseVersion:p.version,declaredDate,reference:text(input.reference,120,'Referência'),conferent:text(input.conferent,120,'Conferente',true),differentProduct:different,items}));
  }else if(action==='confirm'){
   if(r.confirmedAt||r.cancelledAt||p.version!==r.basePurchaseVersion||p.version!==input.expectedPurchaseVersion)throw Error('Compra ou conferência mudou. Preserve o preenchimento e prepare nova revisão.');for(const i of r.items)if(i.sellable+i.held>pending(p,i.productId))throw Error('Aceitação acima do saldo pedido. Confirme um aditamento e faça nova conferência.');const accepted=r.items.filter(i=>i.sellable+i.held>0).map(i=>({productId:i.productId,quantity:i.sellable+i.held,quarantineQuantity:i.held,destinationPositionId:i.destinationPositionId}));let receipt=null;
   if(accepted.length){const result=purchaseAction(next,'receive',{id:p.id,expectedVersion:p.version,items:accepted,note:r.reference,quarantineReason:r.items.filter(i=>i.held).map(i=>i.name+': '+i.reason).join(' / ').slice(0,1000),responsible:r.conferent});Object.assign(next,result);receipt=record(next,'purchases',p.id).receipts.at(-1);receipt.conferenceId=r.id;receipt.reference=r.reference;receipt.conferent=r.conferent;receipt.declaredDate=r.declaredDate;for(const line of receipt.items){const source=r.items.find(i=>i.productId===line.productId);line.originalUnitCostCents=line.unitCostCents;line.unitCostCents=source.unitCostCents;line.costReason=source.costReason;line.destinationPositionId=source.destinationPositionId;const mov=next.stockMovements?.find(m=>m.type==='purchase'&&m.referenceId===receipt.id&&m.productId===line.productId);if(mov)mov.destinationPositionId=source.destinationPositionId;}}
   r=record(next,kind,r.id);r.receiptId=receipt?.id||null;r.confirmedAt=date;touch(r,date,action,input);next.purchaseOccurrences||=[];for(const line of r.items){const types=[];if(line.refused)types.push('refusal');if(line.held)types.push('retention');if(line.missing)types.push('missing');if(line.excess)types.push('excess');for(const type of types)next.purchaseOccurrences.push(baseRecord(next,'purchaseOccurrences',date,input,{purchaseId:r.purchaseId,purchaseNumber:r.purchaseNumber,supplierId:r.supplierId,supplierName:r.supplierName,receiptId:r.receiptId,conferenceId:r.id,type,productId:line.productId,productName:line.name,description:line.reason||'Divergência declarada na conferência',quantity:line[type==='refusal'?'refused':type==='retention'?'held':type],active:true}));}if(r.differentProduct)next.purchaseOccurrences.push(baseRecord(next,'purchaseOccurrences',date,input,{purchaseId:r.purchaseId,purchaseNumber:r.purchaseNumber,supplierId:r.supplierId,supplierName:r.supplierName,receiptId:r.receiptId,conferenceId:r.id,type:'different',description:r.differentProduct,active:true}));
  }else if(action==='cancel'){if(r.confirmedAt)throw Error('Conferência já recebida. Registre ocorrência posterior.');r.cancelledAt=date;touch(r,date,action,{...input,reason:reason(input)});}else throw Error('Ação de conferência inválida.');return;
 }
 if(kind!=='purchaseOccurrences')throw Error('Divergência inválida.');
 if(action==='create'){const p=record(next,'purchases',input.purchaseId),receipt=p.receipts.find(a=>a.id===input.receiptId);if(!receipt)throw Error('Selecione entrega existente.');if(!['missing','excess','retention','refusal','different','other'].includes(input.type))throw Error('Tipo de ocorrência inválido.');next.purchaseOccurrences.push(baseRecord(next,kind,date,input,{purchaseId:p.id,purchaseNumber:p.number,supplierId:p.supplierId,supplierName:p.supplierName,receiptId:receipt.id,type:input.type,description:text(input.description,1000,'Descrição',true),dueDate:dateOnly(input.dueDate,'Prazo'),active:true}));}
 else if(action==='resolve'){if(r.resolvedAt)throw Error('Ocorrência já resolvida.');r.response=text(input.response,1000,'Resposta',true);r.result=text(input.result,500,'Resultado',true);r.resolvedAt=date;touch(r,date,action,input);}
 else if(action==='reopen'){if(!r.resolvedAt)throw Error('Ocorrência já aberta.');r.resolutions||=[];r.resolutions.push({date:r.resolvedAt,response:r.response,result:r.result});delete r.resolvedAt;delete r.response;delete r.result;touch(r,date,action,{...input,reason:reason(input)});}
 else if(action==='followup'){const dueDate=dateOnly(input.dueDate,'Prazo');if(r.taskId)throw Error('Acompanhamento já criado.');next.tasks||=[];const task={id:randomUUID(),number:require('./commands').nextNumber(next.tasks),version:1,date,updatedAt:date,title:text(input.title,120,'Título',true),dueDate,priority:'normal',responsible:text(input.responsible,120,'Responsável'),note:'Fornecedor: '+r.supplierName,link:{kind:'purchaseOccurrences',id:r.id},history:[{date,action:'create'}]};next.tasks.push(task);r.taskId=task.id;r.dueDate=dueDate;touch(r,date,action,input);}else throw Error('Ação de ocorrência inválida.');
 });}
module.exports={purchaseNext};
