const {text,integer,record,reason,baseRecord,touch,expected,run,safe}=require('./advanced-common');
const {movement}=require('./domain');const {availableQuantity}=require('./public/workflow-core');const {retainedQuantity,physicalPosition}=require('./public/quarantine-core');
function addRetention(state,productId,quantity,date,input,origin=null){const product=record(state,'products',productId);quantity=integer(quantity,'Quantidade retida');state.quarantineEntries||=[];const row=baseRecord(state,'quarantineEntries',date,input,{productId,productName:product.name,initialQuantity:quantity,remainingQuantity:quantity,reason:reason(input),origin,inspections:[],dispositions:[],counts:[]});state.quarantineEntries.push(row);physicalPosition(state,product);return row;}
function quarantineAction(state,action,input){return run(state,'quarantineEntries',action,input,(next,date)=>{
 if(action==='create'){const p=record(next,'products',input.productId,true),quantity=integer(input.quantity,'Quantidade');if(availableQuantity(next,p)<quantity)throw Error('Retenção acima do livre; preserve as reservas.');p.stock-=quantity;const row=addRetention(next,p.id,quantity,date,input);movement(next,p,-quantity,'quarantine',row.id,row.reason,date);return;}
 const row=record(next,'quarantineEntries',input.id);expected(row,input);const p=record(next,'products',row.productId);
 if(action==='inspect'){const conclusion=text(input.conclusion,120,'Conclusão',true),note=text(input.note,1000,'Observação');row.inspections.push({date,conclusion,note,responsible:text(input.responsible,120,'Responsável')});touch(row,date,action,input);return;}
 if(action==='count'){const quantity=integer(input.quantity,'Contagem',0);row.counts.push({date,quantity,referenceVersion:row.version+1,referenceQuantity:row.remainingQuantity,note:text(input.note,1000,'Observação'),responsible:text(input.responsible,120,'Responsável')});touch(row,date,action,input);return;}
 if(action==='adjust'){const counted=row.counts.at(-1);if(!counted||counted.appliedAt||counted.referenceVersion!==row.version||counted.referenceQuantity!==row.remainingQuantity||input.expectedQuantity!==row.remainingQuantity)throw Error('Saldo retido mudou; conte novamente.');const before=row.remainingQuantity;row.remainingQuantity=counted.quantity;counted.appliedAt=date;physicalPosition(next,p);row.dispositions.push({date,type:'adjust',quantity:counted.quantity-before,reason:reason(input),responsible:text(input.responsible,120,'Responsável')});touch(row,date,action,input);return;}
 if(!['release','discard'].includes(action))throw Error('Ação de quarentena inválida.');const quantity=integer(input.quantity,'Quantidade');if(quantity>row.remainingQuantity)throw Error('Quantidade acima do saldo retido.');if(action==='release'&&!row.inspections.length)throw Error('Declare a inspeção antes de liberar.');if(action==='release'&&p.active===false)throw Error('Reative o produto antes de liberar ao vendável.');const why=reason(input);row.remainingQuantity-=quantity;row.dispositions.push({date,type:action,quantity,reason:why,responsible:text(input.responsible,120,'Responsável')});if(action==='release'){p.stock=safe(p.stock+quantity,'Estoque');movement(next,p,quantity,'quarantineRelease',row.id,why,date);}touch(row,date,action,input);
 });}
function quarantineReceipt(state,purchase,receipt,input,date){for(const i of receipt.items){const selected=input.items.find(r=>r.productId===i.productId),quantity=integer(selected.quarantineQuantity??0,'Quantidade retida',0);if(quantity>i.quantity)throw Error('Destino retido acima da quantidade recebida.');i.quarantineQuantity=quantity;if(quantity){const p=record(state,'products',i.productId);p.stock-=quantity;const row=addRetention(state,p.id,quantity,date,{...input,reason:input.quarantineReason||input.note},{kind:'purchases',id:purchase.id,receiptId:receipt.id});i.quarantineEntryId=row.id;movement(state,p,-quantity,'quarantine',row.id,row.reason,date);}}}
function quarantineReturn(state,sale,returned,input,date){for(const i of returned.items){const selected=input.items.find(r=>r.productId===i.productId),quantity=integer(selected.quarantineQuantity??0,'Quantidade retida',0);if(quantity>i.quantity-i.restockQuantity)throw Error('Retido não pode incluir unidades revendáveis.');i.quarantineQuantity=quantity;if(quantity){const row=addRetention(state,i.productId,quantity,date,{...input,reason:input.reason},{kind:'sales',id:sale.id,returnId:returned.id});i.quarantineEntryId=row.id;}}}
module.exports={quarantineAction,addRetention,quarantineReceipt,quarantineReturn};
