const {run,record,expected,text,reason,baseRecord,touch,cents,dateOnly}=require('./advanced-common');const {calendarDay}=require('./public/reports');const {recurringSchedule}=require('./public/recurring-core');
function modelFields(next,input,revision){if(!['monthly','weekly'].includes(input.frequency))throw Error('Escolha mensal ou semanal.');if(input.frequency==='monthly'&&input.shortMonth!=='last')throw Error('Confirme uso do último dia nos meses curtos.');const startsOn=dateOnly(input.startsOn||calendarDay(),'Início',true),endsOn=dateOnly(input.endsOn,'Fim');if(endsOn&&endsOn<startsOn)throw Error('Fim anterior ao início.');const expenseCenterId=input.expenseCenterId||null,supplierId=input.supplierId||null;if(expenseCenterId)record(next,'expenseCenters',expenseCenterId,true);if(supplierId)record(next,'suppliers',supplierId);return {revision,description:text(input.description,120,'Descrição',true),category:text(input.category,60,'Categoria'),expenseCenterId,supplierId,responsible:text(input.responsible,120,'Responsável'),amountCents:cents(input.value),frequency:input.frequency,shortMonth:input.shortMonth||'last',startsOn,endsOn};}
function recurringAction(state,kind,action,input){return run(state,kind,action,input,(next,date)=>{
 if(kind==='recurringModels'){
  const r=action==='create'?null:record(next,kind,input.id);if(r)expected(r,input);
  if(action==='create'||action==='edit'){const fields=modelFields(next,input,(r?.revisions?.length||0)+1),effectiveOn=action==='edit'?dateOnly(input.effectiveOn,'Vigência futura',true):fields.startsOn;if(r&&effectiveOn<calendarDay())throw Error('Revisão precisa vigorar de hoje em diante.');if(r){r.revisions.push({...fields,effectiveOn});touch(r,date,action,{...input,reason:reason(input)});}else next.recurringModels.push(baseRecord(next,kind,date,input,{...fields,active:true,revisions:[{...fields,effectiveOn}]}));}
  else if(action==='active'){if(typeof input.active!=='boolean')throw Error('Escolha a situação.');r.active=input.active;touch(r,date,action,{...input,reason:reason(input)});}else throw Error('Ação de modelo inválida.');return;
 }
 if(kind!=='recurringOccurrences')throw Error('Previsão inválida.');
 if(action==='generate'){
  const model=record(next,'recurringModels',input.modelId,true);if(model.version!==input.expectedModelVersion)throw Error('Modelo mudou. Simule novamente.');const schedule=recurringSchedule(model,input.start,input.end);if(!Array.isArray(input.dates)||!input.dates.length||input.dates.length>1000||new Set(input.dates).size!==input.dates.length)throw Error('Escolha datas distintas da simulação.');for(const day of input.dates){const selected=schedule.find(r=>r.originalDate===day);if(!selected)throw Error('Data fora da simulação atual.');if(next.recurringOccurrences.some(r=>r.modelId===model.id&&r.originalDate===day))continue;next.recurringOccurrences.push(baseRecord(next,kind,date,input,{...selected,modelName:model.description}));}return;
 }
 const r=record(next,kind,input.id);expected(r,input);if(r.cancelledAt||r.expenseId)throw Error('Previsão cancelada ou realizada conserva o histórico.');
 if(action==='edit'||action==='reschedule'){const why=reason(input),previous={plannedDate:r.plannedDate,amountCents:r.amountCents};r.plannedDate=dateOnly(input.plannedDate,'Nova data prevista',true);if(action==='edit')r.amountCents=cents(input.value);if(input.relatedPayableId!==undefined){if(input.relatedPayableId)record(next,'payables',input.relatedPayableId);r.relatedPayableId=input.relatedPayableId||null;}touch(r,date,action,{...input,reason:why},{previous});}
 else if(action==='cancel'){r.cancelledAt=date;touch(r,date,action,{...input,reason:reason(input)});}
 else if(action==='realize'||action==='link'){
  let expense;if(action==='realize'){if(r.relatedPayableId)throw Error('Pague pela obrigação relacionada e vincule a despesa existente para não duplicar a saída.');const paid=cents(input.value);if(paid!==r.amountCents)text(input.differenceReason,1000,'Diferença previsto / pago',true);const result=require('./domain').expense(next,{value:input.value,description:r.description,category:r.category,expenseCenterId:r.expenseCenterId,paidDate:input.paidDate,paymentMethod:input.paymentMethod,note:input.note||'',cashSessionId:input.cashSessionId,expectedBudgetVersion:input.expectedBudgetVersion,budgetExcessReason:input.budgetExcessReason});Object.assign(next,result);expense=next.expenses.at(-1);expense.recurringOccurrenceId=r.id;}
  else{expense=record(next,'expenses',input.expenseId);if(expense.cancelledAt||expense.payableAllocations||next.recurringOccurrences.some(o=>o.expenseId===expense.id))throw Error('Escolha despesa válida, individual e ainda não vinculada a previsão.');if(expense.payableId&&r.relatedPayableId!==expense.payableId)throw Error('Vincule a obrigação à previsão antes de usar sua despesa.');if(expense.amountCents!==r.amountCents)text(input.differenceReason,1000,'Diferença previsto / pago',true);}
  const saved=record(next,kind,r.id);saved.expenseId=expense.id;saved.realizedAt=date;saved.actualCents=expense.amountCents;saved.actualDate=expense.paidDate;saved.differenceReason=text(input.differenceReason,1000,'Motivo da diferença');touch(saved,date,action,input);
 }else throw Error('Ação de previsão inválida.');
 });}
module.exports={recurringAction};
