const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {pricingAction}=require('./pricing'),{priceOffer,basisPoints,roundRatio}=require('./public/pricing-core');
const {sale}=require('./server'),{quoteAction}=require('./quotes'),{reservationAction}=require('./workflows');
const {validateDatabase}=require('./storage');
const key=()=>randomUUID(),base=()=>({products:[{id:'p',name:'Produto',priceCents:101,stock:100,version:1,category:'Grupo'},{id:'q',name:'Outro',priceCents:200,stock:10,version:1}],customers:[{id:'c',name:'Cliente',version:1}],sales:[],quotes:[]});
const list=db=>pricingAction(db,'priceLists','create',{name:'Atacado',items:[{productId:'p',price:'0.95'}],requestId:key()});
const promo=db=>pricingAction(db,'promotions','create',{name:'Quantidade',type:'percent',percent:'10.00',minQuantity:2,category:'Grupo',requestId:key()});
function offerSale(db,extra={}){const input={customerId:'c',items:[{productId:'p',quantity:2},{productId:'q',quantity:1}],priceListId:db.priceLists[0].id,paymentMethod:'pix',paymentStatus:'pending',...extra},offer=priceOffer(db,input);return sale(db,{...input,expectedOffer:offer.signature,items:offer.items,requestId:key()});}
test('origem de preço é calculada no servidor com alternativa padrão; snapshots preservados',()=>{let db=list(base());const original=structuredClone(db.products);db=offerSale(db);assert.deepEqual(db.sales[0].items.map(i=>i.priceCents),[95,200]);assert.deepEqual(db.sales[0].items.map(i=>i.priceOrigin),['list','standard']);assert.equal(db.sales[0].totalCents,390);assert.equal(db.products[0].priceCents,original[0].priceCents);const snapshot=structuredClone(db.sales[0]);db=pricingAction(db,'priceLists','edit',{id:db.priceLists[0].id,expectedVersion:1,name:'Outra',items:[{productId:'p',price:'0.70'}],requestId:key()});assert.deepEqual(db.sales[0],snapshot);validateDatabase(db);});
test('mudança de regra desde a revisão, preço inventado e lista inativa são recusados',()=>{let db=list(base());const input={items:[{productId:'p',quantity:1}],priceListId:db.priceLists[0].id,paymentMethod:'pix',paymentStatus:'pending',requestId:key()},offer=priceOffer(db,input);db=pricingAction(db,'priceLists','active',{id:db.priceLists[0].id,expectedVersion:1,active:false,reason:'Pausa',requestId:key()});assert.throws(()=>sale(db,{...input,expectedOffer:offer.signature}),/inativa/);db.priceLists[0].active=true;db.priceLists[0].version++;assert.throws(()=>sale(db,{...input,expectedOffer:offer.signature}),/mudou/);const current=priceOffer(db,input);assert.throws(()=>sale(db,{...input,expectedOffer:current.signature,items:[{productId:'p',quantity:1,priceCents:1}]}),/preço/);});
test('percentual usa ponto-base e arredondamento exato, com mínimo justificado',()=>{let db=promo(list(base()));const input={items:[{productId:'p',quantity:2}],priceListId:db.priceLists[0].id,promotionChoices:[{productId:'p',promotionId:db.promotions[0].id}]},offer=priceOffer(db,input);assert.equal(offer.items[0].priceCents,86);assert.equal(offer.promotionCents,18);assert.equal(roundRatio(101,5000),51);assert.throws(()=>basisPoints('0.005'),/duas/);db.products[0].minimumPriceCents=90;assert.throws(()=>priceOffer(db,input),/Justifique/);assert.equal(priceOffer(db,{...input,offerReason:'Autorização declarada'}).subtotalCents,172);});
test('quantidade mínima, sobreposição e combinação adicional não são silenciosas',()=>{const db=promo(list(base())),promotionId=db.promotions[0].id,input={customerId:'c',items:[{productId:'p',quantity:2}],priceListId:db.priceLists[0].id,promotionChoices:[{productId:'p',promotionId}],paymentMethod:'pix',paymentStatus:'pending',discount:'0.01',discountReason:'Acordo'},offer=priceOffer(db,input);assert.throws(()=>priceOffer(db,{...input,items:[{productId:'p',quantity:1}]}),/insuficiente/);assert.throws(()=>priceOffer(db,{...input,promotionChoices:[...input.promotionChoices,...input.promotionChoices]}),/somente uma/);assert.throws(()=>sale(db,{...input,expectedOffer:offer.signature,requestId:key()}),/combinação/);assert.equal(sale(db,{...input,allowPromotionDiscount:true,expectedOffer:offer.signature,requestId:key()}).sales[0].totalCents,171);});
test('reenvio é exato e reajuste ou lote conflitante não altera a origem',()=>{let db=list(base());const payload={id:db.priceLists[0].id,expectedVersion:1,items:[{productId:'p'}],percent:'5.00',reason:'Reajuste',requestId:key()};db=pricingAction(db,'priceLists','adjust',payload);assert.equal(db.priceLists[0].items[0].priceCents,100);assert.deepEqual(pricingAction(db,'priceLists','adjust',payload),db);assert.throws(()=>pricingAction(db,'priceLists','adjust',{...payload,percent:'6'}),/outros dados/);assert.throws(()=>pricingAction(db,'priceLists','adjust',{...payload,requestId:key(),expectedVersion:2,items:[{productId:'p'},{productId:'inexistente'}]}),/fora da lista/);assert.equal(db.priceLists[0].items[0].priceCents,100);});
test('orçamento promocional congela preços e cópia/conversão honram regra encerrada',()=>{let db=promo(list(base()));const input={customerId:'c',items:[{productId:'p',quantity:2}],priceListId:db.priceLists[0].id,promotionChoices:[{productId:'p',promotionId:db.promotions[0].id}]},offer=priceOffer(db,input);db=quoteAction(db,'create',{...input,items:offer.items,expectedOffer:offer.signature,requestId:key()},sale);const q=db.quotes[0];db=pricingAction(db,'promotions','close',{id:db.promotions[0].id,expectedVersion:1,reason:'Fim',requestId:key()});db=quoteAction(db,'create',{sourceId:q.id,sourceVersion:q.version,customerId:'c',items:q.items.map(i=>({...i,quantity:3})),requestId:key()},sale);assert.equal(db.quotes[1].items[0].priceCents,86);assert.equal(db.quotes[1].negotiation.subtotalCents,258);db=quoteAction(db,'convert',{id:q.id,expectedVersion:1,paymentMethod:'pix',paymentStatus:'pending',requestId:key()},sale);assert.equal(db.sales[0].totalCents,172);assert.equal(db.sales[0].items[0].promotion.id,input.promotionChoices[0].promotionId);});
test('vigência local rejeita regra futura e reserva usa lista escolhida explicitamente',()=>{let db=list(base());const listId=db.priceLists[0].id;assert.throws(()=>priceOffer({...db,priceLists:[{...db.priceLists[0],startsOn:'2200-01-01'}]},{items:[{productId:'p',quantity:1}],priceListId:listId}),/vigência/);db=reservationAction(db,'create',{customerId:'c',items:[{productId:'p',quantity:2}],requestId:key()},sale);const r=db.reservations[0],input={customerId:'c',items:r.items,priceListId:listId},offer=priceOffer(db,input);db=reservationAction(db,'convert',{id:r.id,expectedVersion:r.version,priceListId:listId,expectedOffer:offer.signature,expectedPrices:offer.items.map(i=>({productId:i.productId,priceCents:i.priceCents})),paymentMethod:'pix',paymentStatus:'pending',requestId:key()},sale);assert.equal(db.sales[0].totalCents,190);assert.equal(db.products[0].stock,98);});
test('remover último item mantém lista válida e preferência não muda documento antigo',()=>{let db=list(base()),id=db.priceLists[0].id;db=pricingAction(db,'priceLists','customer',{customerId:'c',expectedVersion:1,priceListId:id,requestId:key()});assert.equal(db.customers[0].preferredPriceListId,id);db=pricingAction(db,'priceLists','remove',{id,expectedVersion:1,productId:'p',reason:'Retirar',requestId:key()});assert.equal(priceOffer(db,{priceListId:id,items:[{productId:'p',quantity:1}]}).items[0].priceCents,101);validateDatabase(db);});

test('mínimo atual protege novas vendas e preserva conversão de orçamento histórico',()=>{let db=base();db=quoteAction(db,'create',{customerId:'c',items:[{productId:'p',quantity:1}],requestId:key()},sale);const q=db.quotes[0];db.products[0].minimumPriceCents=150;assert.throws(()=>sale(db,{customerId:'c',items:[{productId:'p',quantity:1}],paymentMethod:'pix',paymentStatus:'pending',requestId:key()}),/Justifique/);db=quoteAction(db,'convert',{id:q.id,expectedVersion:q.version,paymentMethod:'pix',paymentStatus:'pending',requestId:key()},sale);assert.equal(db.sales[0].totalCents,101);});

test('editar lista preserva produto histórico inativo, mas impede inclusão nova',()=>{let db=list(base());db.products[0].active=false;const input={id:db.priceLists[0].id,expectedVersion:1,name:'Atacado revisado',items:[{productId:'p',price:'0.90'}],requestId:key()};db=pricingAction(db,'priceLists','edit',input);assert.equal(db.priceLists[0].items[0].priceCents,90);assert.throws(()=>pricingAction(db,'priceLists','create',{name:'Nova',items:input.items,requestId:key()}),/inativo/);});
