const test=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('crypto');
const {sale,change}=require('./server'),{validateDatabase,persistDatabase}=require('./storage');
const {catalogueNext}=require('./catalogue-next'),{positionAction,reconcilePositions}=require('./positions'),{inventoryAction,returnAction}=require('./workflows'),{quarantineAction}=require('./quarantine'),{purchaseAction}=require('./purchases'),{purchaseNext}=require('./purchase-next'),{agreementAction,reconcileAgreements}=require('./agreements'),{recurringAction}=require('./recurring'),{procedureAction}=require('./procedures'),{priceReviewAction}=require('./price-reviews');
const {checkoutPreview}=require('./public/checkout-core'),{lookupProduct}=require('./public/product-lookup'),{distribution,positionToken}=require('./public/positions-core'),{agreementPosition,agreementToken}=require('./public/agreements-core'),{recurringSchedule}=require('./public/recurring-core'),{paymentBalance}=require('./public/payments'),{receivableRows}=require('./public/accounts-core'),{cashSummary}=require('./public/cash-core'),{budgetPosition}=require('./public/budget-core'),{proposedPrice}=require('./public/price-review-core'),{calendarDay}=require('./public/reports'),{payableAction}=require('./payables');
const {managerReport}=require('./public/business-core'),{priceReviewRows}=require('./public/price-review-core');
function base(){return {products:[{id:'p',name:'Produto',code:'P01',barcode:'00001',stock:40,priceCents:1000,version:1},{id:'q',name:'Alternativo',code:'Q01',stock:10,priceCents:1200,version:1}],customers:[{id:'c',name:'Cliente',version:1}],suppliers:[{id:'f',name:'Fornecedor',active:true,version:1}],sales:[],purchases:[],payables:[],expenses:[],cashSessions:[{id:'cash',openingCents:10000,openedAt:new Date().toISOString(),openedBy:'Teste',closedAt:null,movements:[]}]};}
function input(fields={}){return {requestId:randomUUID(),responsible:'Verificação',...fields};}
function run(state,fn,data){const next=reconcileAgreements(state,reconcilePositions(state,fn(state,data),data));validateDatabase(next);return next;}
function pos(state=base()){let s=run(state,(s,i)=>positionAction(s,'positions','create',i),input({code:'A',name:'Prateleira A'}));return s;}
function transfer(s,q,from='',to=s.positions[0].id){s=run(s,(s,i)=>positionAction(s,'transfers','create',i),input({from,to,reason:'Distribuir',items:[{productId:'p',quantity:q}]}));return run(s,(s,i)=>positionAction(s,'transfers','confirm',i),input({id:s.transfers.at(-1).id,expectedVersion:1,expectedPositions:{p:positionToken(s.products[0])}}));}
function sell(s,extra={}){const d=input({customerId:'c',items:[{productId:'p',quantity:2,priceCents:1000}],paymentMethod:'cash',paymentStatus:'pending',expectedCashSessionId:'cash',...extra});return run(s,sale,d);}
function purchase(s=base()){s=run(s,(s,i)=>purchaseAction(s,'create',i),input({supplierId:'f',items:[{productId:'p',quantity:10,unitCost:'4.00'}]}));return run(s,(s,i)=>purchaseAction(s,'confirm',i),input({id:s.purchases[0].id,expectedVersion:1}));}
function agree(s,side='receive',originIds=s.sales.map(r=>r.id)){const records=side==='receive'?s.sales:s.payables;const expectedOrigins=Object.fromEntries(originIds.map(id=>{const r=records.find(r=>r.id===id),remaining=side==='receive'?paymentBalance(r).remainingCents:require('./public/payables-core').payableBalance(r).remainingCents;return [id,JSON.stringify({version:r.version||0,accountVersion:r.accountVersion||0,returnVersion:r.returnVersion||0,remaining})];}));return run(s,(s,i)=>agreementAction(s,'create',i),input({side,originIds,dueDates:['2026-11-01','2026-12-01'],expectedOrigins,reason:'Novas datas'}));}
test('PDV divide recebimentos e conserva troco somente em dinheiro',()=>{const p=checkoutPreview(2000,0,[{paymentMethod:'cash',value:'5.00',tendered:'10.00'},{paymentMethod:'pix',value:'15.00'}]);assert.equal(p.changeCents,500);assert.equal(p.receivedCents,2000);assert.equal(p.status,'received');});
test('PDV recusa precisão excedente, valores negativos e troco eletrônico',()=>{for(const payments of [[{paymentMethod:'cash',value:'1.001'}],[{paymentMethod:'pix',value:'-1'}],[{paymentMethod:'pix',value:'1',tendered:'2'}],[{paymentMethod:'cash',value:'2',tendered:'1'}]])assert.throws(()=>checkoutPreview(200,0,payments,true));});
test('PDV parcial cria dívida conhecida e Caixa recebe líquido',()=>{const s=sell(base(),{checkoutPayments:[{paymentMethod:'cash',value:'5',tendered:'10'},{paymentMethod:'pix',value:'5'}],allowPending:true,dueDate:'2026-11-01'});assert.equal(paymentBalance(s.sales[0]).remainingCents,1000);assert.equal(s.sales[0].paymentStatus,'partial');assert.equal(cashSummary(s.cashSessions[0]).expectedCents,10500);assert.equal(s.products[0].stock,38);});
test('PDV consumidor final não deixa saldo e reenvio exato não duplica',()=>{assert.throws(()=>sell(base(),{customerId:'',checkoutPayments:[{paymentMethod:'cash',value:'1'}],allowPending:true}));const d=input({items:[{productId:'p',quantity:1}],paymentMethod:'cash',paymentStatus:'received',checkoutPayments:[{paymentMethod:'cash',value:'10',tendered:'20'}],allowPending:false});const s=run(base(),sale,d);assert.deepEqual(run(s,sale,d),s);assert.throws(()=>sale(s,{...d,checkoutPayments:[{paymentMethod:'cash',value:'10',tendered:'30'}]}));});
test('embalagem e identificador preservam zeros e colisões incluem inativos',()=>{let s=run(base(),(s,i)=>catalogueNext(s,'packages','create',i),input({productId:'p',expectedVersion:1,name:'Caixa',factor:6,code:'00006'}));assert.equal(lookupProduct(s.products,'00006').factor,6);s=run(s,(s,i)=>catalogueNext(s,'packages','active',i),input({productId:'p',expectedVersion:2,id:s.products[0].packages[0].id,active:false,reason:'Parada'}));assert.throws(()=>catalogueNext(s,'aliases','create',input({productId:'q',expectedVersion:1,name:'Alias',code:'00006'})));assert.equal(lookupProduct(s.products,'00006').status,'missing');assert.throws(()=>change(s,'/api/products/edit',{id:'q',expectedVersion:1,name:'Outro',price:'12',barcode:'00006'}));});
test('venda salva embalagem aprovada e rejeita fator alterado',()=>{let s=run(base(),(s,i)=>catalogueNext(s,'packages','create',i),input({productId:'p',expectedVersion:1,name:'Caixa',factor:6,code:'CX'}));const pack=s.products[0].packages[0],packages=[{packageId:pack.id,name:pack.name,factor:6,count:1,version:1}];assert.equal(sell(s,{items:[{productId:'p',quantity:6,packages}]}).sales[0].items[0].packages[0].factor,6);s=run(s,(s,i)=>catalogueNext(s,'packages','edit',i),input({productId:'p',expectedVersion:2,id:pack.id,name:'Caixa',code:'CX',factor:8,reason:'Nova caixa'}));assert.throws(()=>sell(s,{items:[{productId:'p',quantity:6,packages}]}));});
test('famílias mantêm SKUs e exigem aviso para atributos iguais',()=>{let s=run(base(),(s,i)=>catalogueNext(s,'families','create',i),input({name:'Camisetas',attributes:['Cor']}));const family=s.families[0];s=run(s,(s,i)=>catalogueNext(s,'families','members',i),input({id:family.id,expectedVersion:1,items:[{productId:'p',expectedVersion:1,attributes:{Cor:'Azul'}}]}));const d=input({id:family.id,expectedVersion:2,items:[{productId:'q',expectedVersion:1,attributes:{Cor:'Azul'}}]});assert.throws(()=>catalogueNext(s,'families','members',d));const next=run(s,(s,i)=>catalogueNext(s,'families','members',i),{...d,acknowledgeDuplicate:true});assert.equal(next.products[0].stock,40);assert.equal(next.products[1].stock,10);});
test('posições começam não distribuídas e transferências não mudam físico',()=>{let s=pos();assert.equal(distribution(s,s.products[0])[0].quantity,40);s=transfer(s,12);assert.equal(s.products[0].stock,40);assert.equal(distribution(s,s.products[0])[0].quantity,28);assert.equal(s.products[0].positionBalances[s.positions[0].id],12);assert.throws(()=>positionAction(s,'positions','active',input({id:s.positions[0].id,expectedVersion:1,active:false,reason:'Fechar'})));});
test('venda consome determinística e cancelamento restaura origens históricas',()=>{let s=transfer(pos(),35);s=sell(s,{items:[{productId:'p',quantity:8}]});assert.deepEqual(s.sales[0].items[0].stockSources.map(a=>a.quantity),[5,3]);assert.equal(s.products[0].positionBalances[s.positions[0].id],32);s=run(s,(s,i)=>change(s,'/api/sales/cancel',i),{id:s.sales[0].id});assert.equal(s.products[0].positionBalances[s.positions[0].id],35);assert.equal(s.products[0].stock,40);});
test('origem física escolhida recusa saldo e concorrência',()=>{const s=transfer(pos(),4),d=input({items:[{productId:'p',quantity:5}],customerId:'c',paymentMethod:'cash',paymentStatus:'pending',sourcePositionId:s.positions[0].id,expectedPositions:{p:positionToken(s.products[0])}});assert.throws(()=>run(s,sale,d));assert.equal(s.products[0].stock,40);const stale={...d,items:[{productId:'p',quantity:1}],expectedPositions:{p:'old'}};assert.throws(()=>run(s,sale,stale));});
test('reversão física exige saldo atual e cria compensação vinculada',()=>{let s=transfer(pos(),10);const r=s.transfers[0];s=run(s,(s,i)=>positionAction(s,'transfers','reverse',i),input({id:r.id,expectedVersion:r.version,reason:'Voltar',expectedPositions:{p:positionToken(s.products[0])}}));assert.equal(s.products[0].stock,40);assert.equal(s.products[0].positionBalances[s.positions[0].id],0);assert.equal(s.transfers[1].reversalOf,r.id);});
test('compra com retenção atribui só vendável ao destino',()=>{let s=purchase(pos()),p=s.purchases[0],destination=s.positions[0].id;s=run(s,(s,i)=>purchaseAction(s,'receive',i),input({id:p.id,expectedVersion:p.version,items:[{productId:'p',quantity:5,quarantineQuantity:2,destinationPositionId:destination}],quarantineReason:'Conferir'}));assert.equal(s.products[0].stock,43);assert.equal(s.products[0].positionBalances[destination],3);assert.equal(s.quarantineEntries[0].remainingQuantity,2);});
test('retenção e liberação reconciliam posições e estoque vendável',()=>{let s=transfer(pos(),40),id=s.positions[0].id;s=run(s,(s,i)=>quarantineAction(s,'create',i),input({productId:'p',quantity:3,reason:'Conferir',sourcePositionId:id,expectedPositions:{p:positionToken(s.products[0])}}));assert.equal(s.products[0].positionBalances[id],37);s=run(s,(s,i)=>quarantineAction(s,'inspect',i),input({id:s.quarantineEntries[0].id,expectedVersion:1,conclusion:'Aprovada'}));s=run(s,(s,i)=>quarantineAction(s,'release',i),input({id:s.quarantineEntries[0].id,expectedVersion:2,quantity:3,reason:'Aprovado',destinationPositionId:id}));assert.equal(s.products[0].positionBalances[id],40);});
test('inventário por posição cega ajusta posição e global juntos',()=>{let s=transfer(pos(),10),scope=s.positions[0].id;s=run(s,(s,i)=>inventoryAction(s,'create',i),input({name:'Cega A',blind:true,positionScope:scope,items:[{productId:'p'}]}));assert.equal(s.inventories[0].items[0].expectedStock,10);const id=s.inventories[0].id;s=run(s,(s,i)=>inventoryAction(s,'count',i),input({id,expectedVersion:1,items:[{productId:'p',counted:8,conferent:'Pessoa 1'}]}));assert.throws(()=>inventoryAction(s,'apply',input({id,expectedVersion:2,reason:'Diferença'})));s=run(s,(s,i)=>inventoryAction(s,'collect',i),input({id,expectedVersion:2}));s=run(s,(s,i)=>inventoryAction(s,'apply',i),input({id,expectedVersion:3,reason:'Diferença'}));assert.equal(s.products[0].stock,38);assert.equal(s.products[0].positionBalances[scope],8);});
test('recontagem preserva primeira e exige decisão justificada',()=>{let s=run(base(),(s,i)=>inventoryAction(s,'create',i),input({name:'Cega',blind:true,items:[{productId:'p'}]})),id=s.inventories[0].id;for(const [action,fields] of [['count',{items:[{productId:'p',counted:39}]}],['collect',{}],['recount',{items:[{productId:'p'}]}],['count',{items:[{productId:'p',counted:38,countNumber:2,conferent:'Pessoa 2'}]}]])s=run(s,(s,i)=>inventoryAction(s,action,i),input({id,expectedVersion:s.inventories[0].version,...fields}));assert.deepEqual(s.inventories[0].items[0].counts,[39,38]);assert.throws(()=>inventoryAction(s,'choose',input({id,expectedVersion:s.inventories[0].version,items:[{productId:'p',countNumber:2}]})));s=run(s,(s,i)=>inventoryAction(s,'choose',i),input({id,expectedVersion:s.inventories[0].version,reason:'Revisado',items:[{productId:'p',countNumber:2}]}));assert.equal(s.inventories[0].items[0].finalDecision.reason,'Revisado');});
test('movimento durante inventário exige nova referência',()=>{let s=run(base(),(s,i)=>inventoryAction(s,'create',i),input({name:'Contagem',blind:true,items:[{productId:'p'}]}));const id=s.inventories[0].id;s=sell(s);s=run(s,(s,i)=>inventoryAction(s,'count',i),input({id,expectedVersion:1,items:[{productId:'p',counted:38}]}));s=run(s,(s,i)=>inventoryAction(s,'collect',i),input({id,expectedVersion:2}));assert.throws(()=>inventoryAction(s,'apply',input({id,expectedVersion:3,reason:'Diferença'})));});
function conference(s,items){const p=s.purchases[0];return run(s,(s,i)=>purchaseNext(s,'purchaseConferences','create',i),input({purchaseId:p.id,expectedPurchaseVersion:p.version,declaredDate:calendarDay(),reference:'Entrega teste',conferent:'Pessoa',items}));}
test('conferência aceita retido e recusado sem estoque duplicado',()=>{let s=conference(purchase(),[{productId:'p',presented:6,sellable:3,held:1,refused:2,reason:'Embalagem danificada',unitCost:'4',destinationPositionId:''}]);s=run(s,(s,i)=>purchaseNext(s,'purchaseConferences','confirm',i),input({id:s.purchaseConferences[0].id,expectedVersion:1,expectedPurchaseVersion:s.purchases[0].version}));assert.equal(s.products[0].stock,43);assert.equal(s.purchases[0].receipts[0].items[0].quantity,4);assert.equal(s.quarantineEntries[0].remainingQuantity,1);assert.ok(s.purchaseOccurrences.some(r=>r.type==='refusal'));});
test('conferência excessiva exige aditamento e não recebe antes',()=>{let s=conference(purchase(),[{productId:'p',presented:12,sellable:12,held:0,refused:0,unitCost:'4'}]);assert.throws(()=>purchaseNext(s,'purchaseConferences','confirm',input({id:s.purchaseConferences[0].id,expectedVersion:1,expectedPurchaseVersion:s.purchases[0].version})));assert.equal(s.products[0].stock,40);s=run(s,(s,i)=>purchaseNext(s,'purchaseAmendments','create',i),input({purchaseId:s.purchases[0].id,expectedPurchaseVersion:2,items:[{productId:'p',quantity:2,unitCost:'4'}],reason:'Excesso aprovado'}));s=run(s,(s,i)=>purchaseNext(s,'purchaseAmendments','confirm',i),input({id:s.purchaseAmendments[0].id,expectedVersion:1,expectedPurchaseVersion:2}));assert.equal(s.purchases[0].items[0].quantity,12);assert.equal(s.purchases[0].originalOrder.items[0].quantity,10);assert.equal(s.products[0].stock,40);assert.equal(s.payables.length,0);});
test('custo efetivo diferente exige motivo e guarda custo pedido',()=>{const state=purchase();assert.throws(()=>conference(state,[{productId:'p',presented:1,sellable:1,held:0,refused:0,unitCost:'5'}]));let s=conference(state,[{productId:'p',presented:1,sellable:1,held:0,refused:0,unitCost:'5',costReason:'Custo declarado'}]);s=run(s,(s,i)=>purchaseNext(s,'purchaseConferences','confirm',i),input({id:s.purchaseConferences[0].id,expectedVersion:1,expectedPurchaseVersion:2}));assert.equal(s.purchases[0].receipts[0].items[0].unitCostCents,500);assert.equal(s.purchases[0].items[0].unitCostCents,400);});
test('conferência recusa multiplicação de custo fora do limite antes de aceitar',()=>{const s=purchase();assert.throws(()=>conference(s,[{productId:'p',presented:2,sellable:2,held:0,refused:0,unitCost:'90071992547409.91',costReason:'Declarado'}]));assert.equal(s.products[0].stock,40);});
test('acordo transfere só saldo, bloqueia recebimento direto e não cria dinheiro',()=>{let s=sell(base());s=agree(s);assert.equal(s.agreements[0].totalCents,2000);assert.equal(receivableRows(s.sales[0])[0].remainingCents,0);assert.equal(receivableRows(s.sales[0],true)[0].remainingCents,2000);assert.equal(s.cashSessions[0].movements.length,0);assert.throws(()=>change(s,'/api/sales/receive',input({id:s.sales[0].id,value:'1',paymentMethod:'cash'})));});
test('recebimento do acordo aloca em origens e mantém centavos',()=>{let s=agree(sell(base())),a=s.agreements[0];s=run(s,(s,i)=>agreementAction(s,'settle',i),input({id:a.id,expectedVersion:a.version,expectedOriginToken:agreementToken(s,a),expectedRemainingCents:2000,installmentId:a.installments[0].id,value:'10',paymentMethod:'cash',expectedCashSessionId:'cash'}));assert.equal(agreementPosition(s,s.agreements[0]).remainingCents,1000);assert.equal(paymentBalance(s.sales[0]).receivedCents,1000);assert.equal(s.cashSessions[0].movements.length,1);assert.throws(()=>agreementAction(s,'cancel',input({id:a.id,expectedVersion:s.agreements[0].version,expectedOriginToken:agreementToken(s,s.agreements[0]),reason:'Cancelar'})));});
test('devolução após acordo reduz apenas origem e parcelas finais',()=>{let s=sell(base());s=sell(s);s=agree(s);const original=s.sales[0];s=run(s,(s,i)=>returnAction(s,'create',i),input({saleId:original.id,expectedVersion:0,items:[{productId:'p',quantity:1,restockQuantity:1}],reason:'Devolvido'}));const p=agreementPosition(s,s.agreements[0]);assert.equal(p.origins[0].remainingCents,1000);assert.equal(p.origins[1].remainingCents,2000);assert.equal(p.installments[1].adjustmentCents,1000);assert.equal(s.agreements[0].adjustments[0].originId,original.id);});
test('cancelar acordo não recebido libera saldos atuais, sem restaurar valor devolvido',()=>{let s=agree(sell(base())),original=s.sales[0];s=run(s,(s,i)=>returnAction(s,'create',i),input({saleId:original.id,expectedVersion:0,items:[{productId:'p',quantity:1,restockQuantity:0}],reason:'Devolvido'}));const a=s.agreements[0];s=run(s,(s,i)=>agreementAction(s,'cancel',i),input({id:a.id,expectedVersion:a.version,expectedOriginToken:agreementToken(s,a),reason:'Voltar às origens'}));assert.equal(receivableRows(s.sales[0])[0].remainingCents,1000);assert.equal(s.sales[0].receipts.length,0);});
function payable(s,value='20',category=''){s=run(s,(s,i)=>payableAction(s,'create',i),input({supplierId:'f',description:'Obrigação',value,dueDates:['2026-11-01']}));s.payables.at(-1).expenseCategory=category;return s;}
test('pagamento de acordo gera uma despesa compartilhada e categorias repartidas',()=>{let s=payable(payable(base(),'20','A'),'20','B');s=agree(s,'pay',s.payables.map(p=>p.id));const a=s.agreements[0];s=run(s,(s,i)=>agreementAction(s,'settle',i),input({id:a.id,expectedVersion:1,expectedOriginToken:agreementToken(s,a),expectedRemainingCents:4000,installmentId:a.installments[0].id,value:'20',paymentMethod:'cash',paidDate:calendarDay(),expectedCashSessionId:'cash',cashSessionId:'cash'}));assert.equal(s.expenses.length,1);assert.equal(s.expenses[0].amountCents,2000);assert.equal(s.payables[0].payments[0].amountCents,2000);assert.equal(budgetPosition(s,calendarDay().slice(0,7),null,'A').spentCents,2000);assert.equal(cashSummary(s.cashSessions[0]).expectedCents,8000);});
test('acordo recusa contrapartes diferentes e pagamentos concorrentes',()=>{const s=sell(base());s.customers.push({id:'other',name:'Outro',version:1});const next=sell(s,{customerId:'other'});assert.throws(()=>agree(next));let same=agree(s);const a=same.agreements[0];assert.throws(()=>agreementAction(same,'settle',input({id:a.id,expectedVersion:1,expectedOriginToken:'stale',installmentId:a.installments[0].id,value:'1',paymentMethod:'cash'})));});
function model(s=base(),extra={}){return run(s,(s,i)=>recurringAction(s,'recurringModels','create',i),input({description:'Aluguel',category:'Instalação',value:'100',frequency:'monthly',shortMonth:'last',startsOn:'2026-01-31',...extra}));}
test('recorrência mensal usa último dia real e semanal mantém âncora',()=>{const s=model(),r=s.recurringModels[0];assert.deepEqual(recurringSchedule(r,'2026-01-01','2026-03-31').map(r=>r.originalDate),['2026-01-31','2026-02-28','2026-03-31']);const weekly=model(base(),{frequency:'weekly',startsOn:'2026-10-01'}).recurringModels[0];assert.deepEqual(recurringSchedule(weekly,'2026-10-01','2026-10-15').map(r=>r.originalDate),['2026-10-01','2026-10-08','2026-10-15']);assert.throws(()=>recurringSchedule(r,'2026-02-30','2026-03-01'));});
test('geração manual não duplica data adiada ou cancelada',()=>{let s=model(),r=s.recurringModels[0],d=input({modelId:r.id,expectedModelVersion:1,start:'2026-01-01',end:'2026-03-31',dates:['2026-02-28']});s=run(s,(s,i)=>recurringAction(s,'recurringOccurrences','generate',i),d);s=run(s,(s,i)=>recurringAction(s,'recurringOccurrences','reschedule',i),input({id:s.recurringOccurrences[0].id,expectedVersion:1,plannedDate:'2026-03-02',reason:'Adiar'}));s=run(s,(s,i)=>recurringAction(s,'recurringOccurrences','generate',i),{...d,requestId:randomUUID()});assert.equal(s.recurringOccurrences.length,1);assert.equal(s.expenses.length,0);});
test('realizar previsão exige diferença e produz uma única despesa',()=>{let s=model(),m=s.recurringModels[0];s=run(s,(s,i)=>recurringAction(s,'recurringOccurrences','generate',i),input({modelId:m.id,expectedModelVersion:1,start:'2026-01-01',end:'2026-03-01',dates:['2026-02-28']}));const d=input({id:s.recurringOccurrences[0].id,expectedVersion:1,value:'90',paidDate:calendarDay(),paymentMethod:'pix'});assert.throws(()=>recurringAction(s,'recurringOccurrences','realize',d));s=run(s,(s,i)=>recurringAction(s,'recurringOccurrences','realize',i),{...d,differenceReason:'Valor negociado'});assert.equal(s.expenses.length,1);assert.equal(s.recurringModels[0].amountCents,10000);assert.equal(s.recurringOccurrences[0].actualCents,9000);});
test('previsão recorrente fica separada de obrigação no orçamento',()=>{let s=model(),m=s.recurringModels[0];s=run(s,(s,i)=>recurringAction(s,'recurringOccurrences','generate',i),input({modelId:m.id,expectedModelVersion:1,start:'2026-10-01',end:'2026-10-31',dates:['2026-10-31']}));const b=budgetPosition(s,'2026-10',null,'Instalação');assert.equal(b.spentCents,0);assert.equal(b.recurringCents,10000);assert.equal(b.projectedCents,0);});
function procedure(s=base()){return run(s,(s,i)=>procedureAction(s,'procedures','create',i),input({name:'Receber compras',purpose:'Conferir mercadoria',steps:[{name:'Conferir',guidance:'Leia itens',required:true,requireReference:true,page:'purchases',suggestedOwner:'Loja'},{name:'Anotar',required:false,requireReference:false}]}));}
function executeProcedure(s){return run(s,(s,i)=>procedureAction(s,'procedureExecutions','create',i),input({procedureId:s.procedures[0].id,expectedProcedureVersion:s.procedures[0].version,responsible:'Pessoa',targetDate:calendarDay()}));}
test('checklist captura revisão e não altera vendas ou estoque',()=>{let s=executeProcedure(procedure()),model=s.procedures[0],execution=s.procedureExecutions[0];s=run(s,(s,i)=>procedureAction(s,'procedures','edit',i),input({id:model.id,expectedVersion:1,name:'Revisão',purpose:'Nova',steps:[{name:'Outro',required:true,requireReference:false}],reason:'Mudar'}));assert.equal(s.procedureExecutions[0].steps[0].name,'Conferir');assert.equal(s.products[0].stock,40);assert.throws(()=>procedureAction(s,'procedureExecutions','complete',input({id:execution.id,expectedVersion:1})));});
test('etapa obrigatória exige referência e opcional só pula com motivo',()=>{let s=purchase(executeProcedure(procedure())),r=s.procedureExecutions[0],step=r.steps[0];assert.throws(()=>procedureAction(s,'procedureExecutions','finish',input({id:r.id,expectedVersion:1,stepId:step.id,owner:'Pessoa'})));s=run(s,(s,i)=>procedureAction(s,'procedureExecutions','reference',i),input({id:r.id,expectedVersion:1,stepId:step.id,link:{kind:'purchases',id:s.purchases[0].id}}));s=run(s,(s,i)=>procedureAction(s,'procedureExecutions','finish',i),input({id:r.id,expectedVersion:2,stepId:step.id,owner:'Pessoa'}));s=run(s,(s,i)=>procedureAction(s,'procedureExecutions','skip',i),input({id:r.id,expectedVersion:3,stepId:r.steps[1].id,reason:'Não necessário'}));s=run(s,(s,i)=>procedureAction(s,'procedureExecutions','complete',i),input({id:r.id,expectedVersion:4}));assert.ok(s.procedureExecutions[0].completedAt);assert.equal(s.purchases[0].receipts.length,0);});
test('impedimento gera tarefa por comando e retoma com histórico',()=>{let s=executeProcedure(procedure()),r=s.procedureExecutions[0],step=r.steps[0];s=run(s,(s,i)=>procedureAction(s,'procedureExecutions','block',i),input({id:r.id,expectedVersion:1,stepId:step.id,reason:'Aguardando fornecedor'}));s=run(s,(s,i)=>procedureAction(s,'procedureExecutions','task',i),input({id:r.id,expectedVersion:2,stepId:step.id,title:'Conferir fornecedor',dueDate:calendarDay()}));s=run(s,(s,i)=>procedureAction(s,'procedureExecutions','resume',i),input({id:r.id,expectedVersion:3,stepId:step.id,reason:'Resposta chegou'}));assert.equal(s.tasks.length,1);assert.equal(s.procedureExecutions[0].steps[0].history[0].reason,'Aguardando fornecedor');});
function priceReview(s=base(),extra={}){return run(s,(s,i)=>priceReviewAction(s,'create',i),input({name:'Reajuste',target:'standard',productIds:['p','q'],...extra}));}
test('simulação inteira arredonda e nunca aceita preço negativo',()=>{assert.deepEqual(proposedPrice(1055,'percent','10',10),{rawCents:1161,priceCents:1160,roundingDifferenceCents:-1});assert.equal(proposedPrice(1055,'fixed','-0.55',100).priceCents,1000);assert.throws(()=>proposedPrice(10,'fixed','-0.11'));assert.throws(()=>proposedPrice(100,'percent','0.001'));});
test('proposta não altera catálogo e aplicação é atômica em conflito',()=>{let s=priceReview(),r=s.priceReviews[0];s=run(s,(s,i)=>priceReviewAction(s,'simulate',i),input({id:r.id,expectedVersion:1,items:[{productId:'p'},{productId:'q'}],mode:'percent',value:'10',rounding:1,reason:'Reajuste'}));assert.equal(s.products[0].priceCents,1000);s.products[1].version++;assert.throws(()=>priceReviewAction(s,'apply',input({id:r.id,expectedVersion:2,reason:'Aprovar'})));assert.equal(s.products[0].priceCents,1000);});
test('aplicar preços preserva venda antiga e reversão é outra proposta',()=>{let s=priceReview(sell(base())),r=s.priceReviews[0];s=run(s,(s,i)=>priceReviewAction(s,'simulate',i),input({id:r.id,expectedVersion:1,items:[{productId:'p'}],mode:'fixed',value:'1',rounding:1,reason:'Reajuste'}));s=run(s,(s,i)=>priceReviewAction(s,'apply',i),input({id:r.id,expectedVersion:2,reason:'Aprovar'}));assert.equal(s.products[0].priceCents,1100);assert.equal(s.sales[0].items[0].priceCents,1000);s=run(s,(s,i)=>priceReviewAction(s,'reverse',i),input({id:r.id,expectedVersion:3,reason:'Voltar'}));assert.equal(s.priceReviews[1].items[0].proposedPriceCents,1000);assert.equal(s.products[0].priceCents,1100);});
test('preço abaixo do mínimo e redução sem motivo são recusados',()=>{const b=base();b.products[0].minimumPriceCents=900;let s=priceReview(b),r=s.priceReviews[0];assert.throws(()=>priceReviewAction(s,'edit',input({id:r.id,expectedVersion:1,items:[{productId:'p',value:'8'}]})));s=run(s,(s,i)=>priceReviewAction(s,'edit',i),input({id:r.id,expectedVersion:1,items:[{productId:'p',value:'9'}]}));assert.throws(()=>priceReviewAction(s,'apply',input({id:r.id,expectedVersion:2,reason:'Lote'})));});
test('referências de preço atualizadas preservam valor proposto',()=>{let s=priceReview(),r=s.priceReviews[0];s=run(s,(s,i)=>priceReviewAction(s,'edit',i),input({id:r.id,expectedVersion:1,items:[{productId:'p',value:'11'}]}));s.products[0].priceCents=1500;s.products[0].version++;s=run(s,(s,i)=>priceReviewAction(s,'refresh',i),input({id:r.id,expectedVersion:2,reason:'Conferir referência'}));assert.equal(s.priceReviews[0].items[0].basePriceCents,1500);assert.equal(s.priceReviews[0].items[0].proposedPriceCents,1100);});
test('novos dados corrompidos e falha de escrita preservam original',()=>{const s=pos(),bad=structuredClone(s);bad.products[0].positionBalances={[s.positions[0].id]:41};assert.throws(()=>validateDatabase(bad));let original='original';const io={existsSync:()=>false,writeFileSync:()=>{throw Error('Cheio');},renameSync:()=>{original='mudou';}};assert.throws(()=>persistDatabase('isolated.json',s,io));assert.equal(original,'original');});
test('previsão financeira usa datas dos acordos nas duas pontas e filtra mês',()=>{let s=agree(sell(base()));s=payable(s);s=agree(s,'pay',s.payables.map(p=>p.id));const report=managerReport(s,'forecast','2026-12-01','2026-12-31');assert.deepEqual(report.rows,[['2026-12-01',1000,1000,0]]);const obligations=managerReport(s,'obligations','2026-12-01','2026-12-31');assert.equal(obligations.rows.reduce((n,r)=>n+r[2],0),1000);});
test('relatório não conserva vencimento original após acordo e restaura ao cancelar',()=>{let s=sell(base(),{dueDate:'2026-10-10'});s=agree(s);assert.equal(managerReport(s,'forecast','2026-10-01','2026-10-31').rows.length,0);const a=s.agreements[0];s=run(s,(s,i)=>agreementAction(s,'cancel',i),input({id:a.id,expectedVersion:a.version,expectedOriginToken:agreementToken(s,a),reason:'Sem efetivos'}));assert.equal(managerReport(s,'forecast','2026-10-01','2026-10-31').rows[0][1],2000);});
test('despesa compartilhada reparte duas categorias e caixa recebe saída uma vez',()=>{let s=payable(payable(base(),'5','A'),'15','B');s=agree(s,'pay',s.payables.map(p=>p.id));const a=s.agreements[0];s=run(s,(s,i)=>agreementAction(s,'settle',i),input({id:a.id,expectedVersion:a.version,expectedOriginToken:agreementToken(s,a),expectedRemainingCents:2000,installmentId:a.installments[0].id,value:'10',paymentMethod:'cash',paidDate:calendarDay(),expectedCashSessionId:'cash',cashSessionId:'cash'}));assert.equal(s.expenses.length,1);assert.deepEqual(s.expenses[0].payableAllocations.map(a=>a.amountCents),[500,500]);assert.equal(budgetPosition(s,calendarDay().slice(0,7),null,'A').spentCents,500);assert.equal(budgetPosition(s,calendarDay().slice(0,7),null,'B').spentCents,500);assert.equal(cashSummary(s.cashSessions[0]).expectedCents,9000);assert.equal(s.cashSessions[0].movements.length,1);});
test('previsão relacionada cobre só a obrigação ainda representada e avisa cancelamento',()=>{const s=payable(base(),'20','A'),p=s.payables[0];s.recurringOccurrences=[{id:'rr',plannedDate:'2026-11-01',amountCents:3000,category:'A',relatedPayableId:p.id}];let b=budgetPosition(s,'2026-11',null,'A');assert.equal(b.recurringCents,1000);assert.equal(b.projectedWithRecurringCents,3000);p.cancelledAt=new Date().toISOString();b=budgetPosition(s,'2026-11',null,'A');assert.equal(b.recurringCents,3000);assert.match(b.recurringRows[0].relationWarning,/reveja/);});
test('mesma obrigação reparte cobertura recorrente uma única vez com ordem estável',()=>{const s=payable(base(),'100','A'),p=s.payables[0];s.recurringOccurrences=[{id:'segundo',plannedDate:'2026-11-02',amountCents:10000,category:'A',relatedPayableId:p.id},{id:'primeiro',plannedDate:'2026-11-01',amountCents:10000,category:'A',relatedPayableId:p.id}];const b=budgetPosition(s,'2026-11',null,'A');assert.deepEqual(b.recurringRows.map(r=>[r.id,r.coveredCents,r.forecastCents]),[['primeiro',10000,0],['segundo',0,10000]]);assert.equal(b.projectedWithRecurringCents,20000);assert.match(b.recurringRows[1].relationWarning,/repartir/);s.recurringOccurrences.reverse();assert.deepEqual(budgetPosition(s,'2026-11',null,'A'),b);});
test('cobertura recorrente de acordo conserva origem e reparte apenas parcela do mês',()=>{let s=payable(base(),'100','A');const id=s.payables[0].id;s=agree(s,'pay',[id]);s.recurringOccurrences=[{id:'a',plannedDate:'2026-11-01',amountCents:4000,category:'A',relatedPayableId:id},{id:'b',plannedDate:'2026-11-01',amountCents:4000,category:'A',relatedPayableId:id}];const b=budgetPosition(s,'2026-11',null,'A');assert.equal(b.obligations[0].payableId,id);assert.equal(b.obligations[0].agreementId,s.agreements[0].id);assert.deepEqual(b.recurringRows.map(r=>r.coveredCents),[4000,1000]);assert.equal(b.pendingCents,5000);assert.equal(b.recurringCents,3000);assert.equal(b.projectedWithRecurringCents,8000);});
test('revisão mostra promoção por categoria e outras listas vigentes',()=>{const s=priceReview();s.products[0].category='A';s.promotions=[{id:'promo',name:'Categoria A',category:'A',active:true}];s.priceLists=[{id:'lista',name:'Atacado',active:true,items:[{productId:'p',priceCents:900}]}];const rows=priceReviewRows(s,s.priceReviews[0]);assert.deepEqual(rows[0].promotions,['Categoria A']);assert.deepEqual(rows[0].relatedLists,[{name:'Atacado',priceCents:900}]);assert.deepEqual(rows[1].promotions,[]);});
test('proposta histórica em lista suspensa continua consultável e sinaliza conflito',()=>{const b=base();b.priceLists=[{id:'lista',name:'Lista',active:true,version:1,number:1,history:[],items:[]}];const s=priceReview(b,{target:'list',listId:'lista'});s.priceLists[0].active=false;assert.equal(priceReviewRows(s,s.priceReviews[0])[0].conflict,true);assert.throws(()=>priceReviewAction(s,'apply',input({id:s.priceReviews[0].id,expectedVersion:1,reason:'Aplicar'})));});
test('reposição com requestId reutilizado para outro destino é recusada',()=>{const s=pos(),d=input({id:'p',quantity:2,note:'Entrada',destinationPositionId:s.positions[0].id});const next=run(s,(s,i)=>change(s,'/api/stock',i),d);assert.equal(next.products[0].positionBalances[d.destinationPositionId],2);assert.throws(()=>change(next,'/api/stock',{...d,destinationPositionId:''}));assert.deepEqual(change(next,'/api/stock',d),next);});
test('atualizar preços de orçamento conserva embalagem e edição registra revisão de itens',()=>{const {quoteAction}=require('./quotes');let s=run(base(),(s,i)=>catalogueNext(s,'packages','create',i),input({productId:'p',expectedVersion:1,name:'Caixa',factor:2,code:'CX2'}));const p=s.products[0].packages[0],packages=[{packageId:p.id,name:p.name,factor:p.factor,count:1,version:p.version}];s=run(s,(s,i)=>quoteAction(s,'create',i),input({items:[{productId:'p',quantity:2,packages}]}));const q=s.quotes[0];s=run(s,(s,i)=>quoteAction(s,'prices',i),input({id:q.id,expectedVersion:1,expectedPrices:[{productId:'p',priceCents:1000}]}));assert.equal(s.quotes[0].items[0].packages[0].factor,2);s=run(s,(s,i)=>quoteAction(s,'edit',i),input({id:q.id,expectedVersion:2,items:[{productId:'q',quantity:1,substitutedFrom:'p'}]}));assert.equal(s.quotes[0].itemRevisions[0].items[0].productId,'p');assert.equal(s.quotes[0].items[0].substitutedFrom.id,'p');});
