const {validDay}=require('./public/reports');const {distribution}=require('./public/positions-core');
const integer=(n,min=0)=>Number.isSafeInteger(n)&&n>=min;
function fail(message){throw Error('Dados V0.12 inválidos: '+message);}
function list(value,label,max=500,empty=false){if(!Array.isArray(value)||!empty&&!value.length||value.length>max)fail(label);}
function sum(values){const n=values.reduce((a,b)=>a+b,0);if(!Number.isSafeInteger(n))fail('soma fora do limite');return n;}
function validateRound10(db){
 for(const kind of ['families','positions','transfers','purchaseConferences','purchaseAmendments','purchaseOccurrences','agreements','recurringModels','recurringOccurrences','procedures','procedureExecutions','priceReviews'])for(const r of db[kind]||[])if(!integer(r.version,1)||!integer(r.number,1)||!Array.isArray(r.history)||typeof r.date!=='string'||!Number.isFinite(Date.parse(r.date)))fail(kind);
 const codes=new Map();for(const p of db.products){for(const kind of ['packages','aliases']){if(p[kind]===undefined)continue;list(p[kind],kind,500,true);const ids=new Set();for(const a of p[kind]){if(typeof a.id!=='string'||ids.has(a.id)||typeof a.name!=='string'||!a.name||typeof a.code!=='string'||typeof a.active!=='boolean'||!integer(a.version,1)||kind==='packages'&&(!integer(a.factor,1)||a.factor>1000000||!integer(p.priceCents*a.factor)))fail('embalagem / identificador');ids.add(a.id);if(a.code){const key=a.code.toLowerCase();if(codes.has(key))fail('código alternativo repetido');codes.set(key,{productId:p.id,alternative:true});}}}if(p.positionBalances){for(const [id,q] of Object.entries(p.positionBalances))if(!integer(q)||!(db.positions||[]).some(r=>r.id===id&&(q===0||r.active)))fail('posição / quantidade');distribution(db,p);}if(p.familyId&&!(db.families||[]).some(r=>r.id===p.familyId))fail('família ausente');}
 for(const p of db.products)for(const value of [p.code,p.barcode].filter(Boolean)){if(codes.has(value.toLowerCase()))fail('código principal colide com alternativa');}
 for(const s of [...db.sales,...(db.quotes||[]),...(db.purchases||[])])for(const i of s.items){if(i.packages){list(i.packages,'snapshot de embalagem',100,true);if(i.packages.some(a=>typeof a.name!=='string'||!integer(a.factor,1)||!integer(a.count,1)||!integer(a.version,1))||sum(i.packages.map(a=>a.factor*a.count))>i.quantity)fail('equivalência histórica');}}
 for(const m of db.positionMovements||[])if(!integer(m.quantity,1)||typeof m.productId!=='string'||!Number.isFinite(Date.parse(m.date)))fail('movimento de posição');
 for(const r of db.transfers||[]){list(r.items,'transferência');if(r.from===r.to||r.items.some(i=>!integer(i.quantity,1)||!db.products.some(p=>p.id===i.productId)))fail('transferência');}
 for(const r of db.purchaseConferences||[]){list(r.items,'conferência');if(!validDay(r.declaredDate)||!db.purchases?.some(p=>p.id===r.purchaseId))fail('conferência / origem');for(const i of r.items)if(![i.presented,i.sellable,i.held,i.refused,i.unitCostCents,i.originalUnitCostCents,i.missing,i.excess].every(n=>integer(n))||sum([i.sellable,i.held,i.refused])!==i.presented)fail('destinos da conferência');}
 for(const r of db.purchaseAmendments||[]){list(r.items,'aditamento');if(r.items.some(i=>!integer(i.extraQuantity,1)||!integer(i.unitCostCents))||sum(r.items.map(i=>i.extraQuantity*i.unitCostCents))!==r.totalCents)fail('total do aditamento');}
 for(const s of db.sales){if(s.checkout){const c=s.checkout;if(![c.totalCents,c.internalCents,c.receivedCents,c.remainingCents,c.cashCents,c.tenderedCents,c.changeCents].every(n=>integer(n))||sum([c.internalCents,c.receivedCents,c.remainingCents])!==c.totalCents||c.tenderedCents-c.cashCents!==c.changeCents)fail('liquidação dividida');}for(const r of s.receipts||[])if(r.tenderedCents!==undefined&&(!integer(r.tenderedCents)||!integer(r.changeCents)||r.tenderedCents-r.amountCents!==r.changeCents||r.paymentMethod!=='cash'&&r.changeCents))fail('troco de recebimento');}
 for(const e of db.expenses||[])if(e.payableAllocations){list(e.payableAllocations,'despesa compartilhada',500);if(e.payableId||sum(e.payableAllocations.map(a=>a.amountCents))!==e.amountCents)fail('valor da despesa compartilhada');const ids=new Set();for(const a of e.payableAllocations){const p=db.payables?.find(p=>p.id===a.payableId),payment=p?.payments.find(r=>r.id===a.paymentId);if(ids.has(a.paymentId)||!integer(a.amountCents,1)||!payment||payment.expenseId!==e.id||payment.amountCents!==a.amountCents||payment.installmentId!==a.installmentId)fail('alocação recíproca da despesa');ids.add(a.paymentId);}}
 for(const a of db.agreements||[]){if(!['receive','pay'].includes(a.side))fail('tipo de acordo');list(a.origins,'origens do acordo',60);list(a.installments,'parcelas do acordo',60);list(a.payments,'efetivos do acordo',10000,true);if(a.origins.some(o=>!integer(o.amountCents,1)||!(a.side==='receive'?db.sales:db.payables||[]).some(r=>r.id===o.id))||sum(a.origins.map(o=>o.amountCents))!==a.totalCents||a.installments.some(i=>!integer(i.amountCents,1)||i.dueDate&&!validDay(i.dueDate))||sum(a.installments.map(i=>i.amountCents))!==a.totalCents)fail('principal do acordo');for(const p of a.payments){list(p.allocations,'alocação do acordo',500);if(!integer(p.amountCents,1)||!a.installments.some(i=>i.id===p.installmentId)||p.allocations.some(x=>!integer(x.amountCents,1)||!a.origins.some(o=>o.id===x.originId))||sum(p.allocations.map(x=>x.amountCents))!==p.amountCents)fail('efetivo do acordo');}if(sum(a.payments.map(p=>p.amountCents))>a.totalCents)fail('acordo pago acima do pactuado');}
 for(const r of db.recurringModels||[]){list(r.revisions,'revisões recorrentes',1000);for(const v of r.revisions)if(!integer(v.amountCents,1)||!validDay(v.startsOn)||!validDay(v.effectiveOn)||v.endsOn&&!validDay(v.endsOn)||!['weekly','monthly'].includes(v.frequency))fail('recorrência');}
 const occurrenceKeys=new Set();for(const r of db.recurringOccurrences||[]){const key=r.modelId+':'+r.originalDate;if(occurrenceKeys.has(key)||!db.recurringModels?.some(m=>m.id===r.modelId)||!validDay(r.originalDate)||!validDay(r.plannedDate)||!integer(r.amountCents,1)||r.expenseId&&!db.expenses?.some(e=>e.id===r.expenseId))fail('ocorrência recorrente');occurrenceKeys.add(key);}
 for(const r of [...(db.procedures||[]),...(db.procedureExecutions||[])]){list(r.steps,'etapas',30);if(new Set(r.steps.map(s=>s.id)).size!==r.steps.length||r.steps.some(s=>typeof s.name!=='string'||typeof s.required!=='boolean'||typeof s.requireReference!=='boolean'))fail('etapas de procedimento');}
 for(const r of db.procedureExecutions||[])for(const s of r.steps)if(!['pending','completed','blocked','skipped'].includes(s.status)||!Array.isArray(s.references)||!Array.isArray(s.history)||s.required&&s.status==='skipped')fail('execução de etapa');
 for(const r of db.priceReviews||[]){list(r.items,'itens da revisão');if(!['standard','list'].includes(r.target)||r.items.some(i=>!integer(i.basePriceCents)||!integer(i.proposedPriceCents)||!integer(i.productVersion)||!db.products.some(p=>p.id===i.productId)))fail('preços propostos');}
 return db;
}
module.exports={validateRound10};
