const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');const {sale,change}=require('./server'),{returnAction}=require('./workflows'),{storeCreditAction}=require('./store-credits'),{storeCreditBalance}=require('./public/store-credit-core'),{refundBalance}=require('./public/workflow-core'),{paymentBalance}=require('./public/payments'),{receivableRows}=require('./public/accounts-core'),{validateDatabase}=require('./storage'),{movementSummary,calendarDay}=require('./public/reports');const key=()=>randomUUID();
const base=()=>({products:[{id:'p',name:'Produto',stock:20,priceCents:101,version:1}],customers:[{id:'c',name:'Cliente',version:1},{id:'d',name:'Outro',version:1}],sales:[]});
function issued(){let db=sale(base(),{customerId:'c',items:[{productId:'p',quantity:4}],paymentMethod:'pix',paymentStatus:'received',requestId:key()});db=returnAction(db,'create',{saleId:db.sales[0].id,expectedVersion:0,items:[{productId:'p',quantity:4,restockQuantity:4}],reason:'Troca',requestId:key()});const payload={saleId:db.sales[0].id,returnId:db.sales[0].returns[0].id,expectedVersion:1,expectedRefundCents:404,value:'4.04',reason:'Escolha do cliente',requestId:key()};return {db:storeCreditAction(db,'issue',payload),payload};}
function buy(db,value='2.02',status='received',qty=4){return sale(db,{customerId:'c',items:[{productId:'p',quantity:qty}],paymentMethod:'pix',paymentStatus:status,storeCreditValue:value,expectedStoreCreditCents:storeCreditBalance(db,'c'),requestId:key()});}
test('emissão só converte restituição identificada e replay não emite novamente',()=>{const {db,payload}=issued();assert.equal(storeCreditBalance(db,'c'),404);assert.equal(refundBalance(db.sales[0]).availableCents,0);assert.deepEqual(storeCreditAction(db,'issue',payload),db);assert.throws(()=>storeCreditAction(db,'issue',{...payload,requestId:key()}),/mudaram/);validateDatabase(db);});
test('pagamento misto liquida sem inflar dinheiro e mantém recebíveis corretos',()=>{let {db}=issued();db=buy(db);const s=db.sales[1];assert.equal(s.receipts[0].amountCents,202);assert.equal(paymentBalance(s).remainingCents,0);assert.equal(paymentBalance(s).internalCents,202);assert.equal(receivableRows(s)[0].remainingCents,0);assert.equal(movementSummary(db.sales,[],calendarDay(),calendarDay()).incomeCents,606);assert.equal(storeCreditBalance(db,'c'),202);validateDatabase(db);});
test('restante pendente pode ser recebido sem cobrar crédito duas vezes',()=>{let {db}=issued();db=buy(db,'2.02','pending');const s=db.sales[1];assert.equal(s.receipts.length,0);assert.equal(paymentBalance(s).remainingCents,202);assert.equal(receivableRows(s)[0].remainingCents,202);validateDatabase(db);});
test('consumo concorrente e uso de outro cliente não alteram origem',()=>{let {db}=issued();const snapshot=structuredClone(db);assert.throws(()=>sale(db,{customerId:'d',items:[{productId:'p',quantity:4}],paymentMethod:'pix',paymentStatus:'pending',storeCreditValue:'1',expectedStoreCreditCents:404,requestId:key()}),/Saldo/);assert.deepEqual(db,snapshot);db=buy(db);assert.throws(()=>sale(db,{customerId:'c',items:[{productId:'p',quantity:4}],paymentMethod:'pix',paymentStatus:'pending',storeCreditValue:'2',expectedStoreCreditCents:404,requestId:key()}),/Saldo/);});
test('devoluções parciais restauram centavos históricos e limitam dinheiro efetivo',()=>{let {db}=issued();db=buy(db,'2.03');const s=db.sales[1];db=returnAction(db,'create',{saleId:s.id,expectedVersion:0,items:[{productId:'p',quantity:1,restockQuantity:1}],reason:'Parcial',requestId:key()});assert.equal(db.sales[1].storeCreditRestoredCents,51);assert.equal(refundBalance(db.sales[1]).availableCents,50);for(let v=1;v<4;v++)db=returnAction(db,'create',{saleId:s.id,expectedVersion:v,items:[{productId:'p',quantity:1,restockQuantity:1}],reason:'Restante',requestId:key()});assert.equal(db.sales[1].storeCreditRestoredCents,203);assert.equal(storeCreditBalance(db,'c'),404);assert.equal(refundBalance(db.sales[1]).availableCents,201);validateDatabase(db);});
test('cancelar venda restaura uma vez; crédito consumido não cancela emissão',()=>{let {db}=issued();db=buy(db,'4.04');assert.throws(()=>storeCreditAction(db,'cancel',{id:db.storeCredits[0].id,expectedVersion:2,reason:'Cancelar',requestId:key()}),/nunca/);db=change(db,'/api/sales/cancel',{id:db.sales[1].id});assert.equal(storeCreditBalance(db,'c'),404);assert.equal(refundBalance(db.sales[1]).availableCents,0);assert.throws(()=>change(db,'/api/sales/cancel',{id:db.sales[1].id}),/já/);validateDatabase(db);});
test('cancelamento de emissão nunca usada reabre restituição; corrupção é rejeitada',()=>{let {db}=issued();db=storeCreditAction(db,'cancel',{id:db.storeCredits[0].id,expectedVersion:1,reason:'Cliente escolheu restituição',requestId:key()});assert.equal(storeCreditBalance(db,'c'),0);assert.equal(refundBalance(db.sales[0]).availableCents,404);validateDatabase(db);const broken=structuredClone(db);broken.storeCredits[0].remainingCents=1;assert.throws(()=>validateDatabase(broken),/extrato/);});
