const A=require('./advanced-common'),{randomUUID}=require('node:crypto');const {refundBalance}=require('./public/workflow-core'),{receiptList}=require('./public/payments'),{storeCreditBalance,internalSettled,returnCreditCents}=require('./public/store-credit-core');
function storeCreditAction(state,action,input){return A.run(state,'storeCredits',action,input,(next,date)=>{
 if(action==='issue'){
  const s=A.record(next,'sales',input.saleId);if(!s.customerId)throw Error('Crédito exige cliente identificado.');if((s.returnVersion||0)!==input.expectedVersion)throw Error('As devoluções mudaram.');
  const r=(s.returns||[]).find(r=>r.id===input.returnId);if(!r)throw Error('Selecione a devolução de origem.');const balance=refundBalance({...s,receipts:receiptList(s)}),amountCents=A.cents(input.value);if(input.expectedRefundCents!==balance.availableCents||amountCents>balance.availableCents)throw Error('Crédito acima do saldo de restituição disponível ou saldo alterado.');
  const issued=(next.storeCredits||[]).filter(c=>c.returnId===r.id&&!c.cancelledAt).reduce((n,c)=>n+c.amountCents,0);if(issued+amountCents>r.totalCents-(r.storeCreditRestoredCents||0))throw Error('Crédito acima da devolução selecionada.');
  const c=A.baseRecord(next,'storeCredits',date,input,{customerId:s.customerId,customerName:s.customerName,saleId:s.id,returnId:r.id,amountCents,remainingCents:amountCents,events:[],reason:A.reason(input)});c.events.push({id:randomUUID(),date,type:'issue',amountCents,saleId:s.id,returnId:r.id});next.storeCredits.push(c);s.storeCreditIssuedCents=(s.storeCreditIssuedCents||0)+amountCents;s.returnVersion=(s.returnVersion||0)+1;
 }else if(action==='cancel'){
  const c=A.record(next,'storeCredits',input.id);A.expected(c,input);if(c.cancelledAt||c.events.some(e=>e.type==='use')||c.remainingCents!==c.amountCents)throw Error('Somente crédito nunca utilizado pode ser cancelado.');const s=A.record(next,'sales',c.saleId);c.cancelledAt=date;c.remainingCents=0;c.events.push({id:randomUUID(),date,type:'cancel',amountCents:c.amountCents,saleId:s.id});A.touch(c,date,action,input,{reason:A.reason(input)});s.storeCreditIssuedCents-=c.amountCents;s.returnVersion=(s.returnVersion||0)+1;
 }else throw Error('Operação de crédito inválida.');
});}
function consumeCredits(state,s,input,date){
 const amount=input.storeCreditValue?A.cents(input.storeCreditValue,true):0;if(!amount)return;if(!s.customerId)throw Error('Selecione o cliente do crédito.');const balance=storeCreditBalance(state,s.customerId);if(input.expectedStoreCreditCents!==balance||amount>balance||amount>s.totalCents)throw Error('Saldo de crédito mudou ou valor acima do saldo/total.');
 s.storeCreditCents=amount;s.storeCreditAllocations=[];let left=amount;const rows=(state.storeCredits||[]).filter(c=>c.customerId===s.customerId&&!c.cancelledAt&&c.remainingCents).sort((a,b)=>a.date.localeCompare(b.date)||a.number-b.number);
 for(const c of rows){const used=Math.min(left,c.remainingCents);if(!used)continue;c.remainingCents-=used;A.touch(c,date,'use',input);c.events.push({id:randomUUID(),date,type:'use',amountCents:used,saleId:s.id});s.storeCreditAllocations.push({creditId:c.id,amountCents:used,restoredCents:0});left-=used;}
 if(left)throw Error('Crédito insuficiente.');
}
function restoreCredits(state,s,amount,date,returnId=null){let left=amount;for(const allocation of s.storeCreditAllocations||[]){const value=Math.min(left,allocation.amountCents-allocation.restoredCents);if(!value)continue;const c=A.record(state,'storeCredits',allocation.creditId);if(c.cancelledAt)throw Error('Origem de crédito incompatível.');c.remainingCents=A.safe(c.remainingCents+value,'Saldo de crédito');allocation.restoredCents+=value;A.touch(c,date,'restore',{});c.events.push({id:randomUUID(),date,type:'restore',amountCents:value,saleId:s.id,returnId});left-=value;}if(left)throw Error('Restauração de crédito acima do uso.');s.storeCreditRestoredCents=(s.storeCreditRestoredCents||0)+amount;}
function creditReturn(state,s,r,date){if(!s.storeCreditCents)return;const previous={...s,returns:s.returns.filter(x=>x.id!==r.id)};const value=returnCreditCents(previous,r.items);r.storeCreditRestoredCents=value;restoreCredits(state,s,value,date,r.id);}
function creditCancel(state,s,date){restoreCredits(state,s,internalSettled(s),date);}
module.exports={storeCreditAction,consumeCredits,creditReturn,creditCancel};
