const A=require('./advanced-common'),{randomUUID}=require('node:crypto'),{calendarDay}=require('./public/reports'),{supplierProposal,supplierComparison}=require('./public/supplier-quote-core'),{purchaseAction}=require('./purchases');
function supplierQuoteAction(state,action,input){return A.run(state,'supplierQuotes',action,input,(next,date)=>{
 let r=action==='create'?null:A.record(next,'supplierQuotes',input.id);if(r){A.expected(r,input);if(r.closedAt||r.cancelledAt)throw Error('Cotação encerrada.');}
 if(action==='create'||action==='edit'){
  if(r?.responses.length)throw Error('Solicitação com respostas confirmadas não pode ser editada.');if(!Array.isArray(input.supplierIds)||!input.supplierIds.length||input.supplierIds.length>100||new Set(input.supplierIds).size!==input.supplierIds.length)throw Error('Selecione fornecedores distintos.');const suppliers=input.supplierIds.map(id=>{const s=A.record(next,'suppliers',id,true);return {id:s.id,name:s.name};});const items=A.items(input.items).map(i=>{const p=A.record(next,'products',i.productId,true);return {productId:p.id,name:p.name,code:p.code||'',quantity:A.integer(i.quantity,'Quantidade')};});const fields={suppliers,items,deadline:A.dateOnly(input.deadline,'Prazo de resposta'),note:A.text(input.note,1000,'Observação')};if(r){const previous=structuredClone(r);Object.assign(r,fields);A.touch(r,date,action,input,{previous});}else next.supplierQuotes.push(A.baseRecord(next,'supplierQuotes',date,input,{...fields,responses:[],purchaseIds:[]}));
 }else if(action==='respond'){
  if(r.purchaseIds.length)throw Error('Respostas selecionadas já originaram preparações.');const supplier=r.suppliers.find(s=>s.id===input.supplierId);if(!supplier)throw Error('Fornecedor fora da solicitação.');A.record(next,'suppliers',supplier.id,true);const rows=A.items(input.items);if(rows.length!==r.items.length)throw Error('Declare cada produto cotado ou não cotado.');const items=rows.map(i=>{if(!r.items.some(p=>p.productId===i.productId)||typeof i.quoted!=='boolean')throw Error('Resposta de produto inválida.');return {productId:i.productId,quoted:i.quoted,unitCostCents:i.quoted?A.cents(i.unitCost,true):null,offeredQuantity:i.quoted?A.integer(i.offeredQuantity,'Quantidade ofertada',0):0,leadDays:i.quoted?A.integer(i.leadDays,'Prazo em dias',0,3650):null};});const old=r.responses.find(x=>x.supplierId===supplier.id);if(old&&input.expectedResponseVersion!==old.version)throw Error('Resposta mudou.');if(!old&&input.expectedResponseVersion!==null&&input.expectedResponseVersion!==undefined)throw Error('Resposta não encontrada.');const fields={supplierId:supplier.id,supplierName:supplier.name,items,validUntil:A.dateOnly(input.validUntil,'Validade'),freightCents:A.cents(input.freight||'0',true),reference:A.text(input.reference,150,'Referência')};supplierProposal(r,fields);if(old){const previous=structuredClone(old);Object.assign(old,fields);A.touch(old,date,'respond',input,{previous});}else r.responses.push({id:randomUUID(),version:1,date,history:[],...fields});A.touch(r,date,action,input);
 }else if(action==='select'){
  if(r.purchaseIds.length)throw Error('Preparações já geradas por esta cotação.');const compare=supplierComparison(r);const selections=A.items(input.items);if(selections.length!==r.items.length)throw Error('Escolha explicitamente um fornecedor por produto.');const groups=new Map(),chosen=[];
  for(const i of selections){const row=compare.find(p=>p.productId===i.productId),candidate=row?.proposals.find(p=>p.supplierId===i.supplierId);if(!candidate||!candidate.quoted||!candidate.valid||candidate.offeredQuantity<row.quantity)throw Error('Proposta vencida, não cotada ou quantidade insuficiente.');A.record(next,'suppliers',i.supplierId,true);A.record(next,'products',i.productId,true);if(i.expectedCostCents!==candidate.unitCostCents||i.expectedResponseVersion!==candidate.version)throw Error('Resposta mudou desde a revisão.');const lower=row.proposals.filter(p=>p.quoted&&p.valid&&p.offeredQuantity>=row.quantity&&p.unitCostCents<candidate.unitCostCents);const reason=lower.length?A.text(i.reason,1000,'Justificativa de proposta superior',true):A.text(i.reason,1000,'Justificativa');const group=groups.get(i.supplierId)||[];group.push({productId:i.productId,quantity:row.quantity,unitCost:String(candidate.unitCostCents/100)});groups.set(i.supplierId,group);chosen.push({...i,reason,responseId:candidate.responseId});}
  for(const [supplierId,items] of groups){const response=r.responses.find(p=>p.supplierId===supplierId),result=purchaseAction(next,'create',{supplierId,items,note:'Origem: cotação COT-'+r.number+' · frete declarado '+(response.freightCents/100).toFixed(2)+' como referência separada, sem inclusão no custo.',requestId:randomUUID()});Object.assign(next,result);r=A.record(next,'supplierQuotes',input.id);const p=next.purchases.at(-1);p.supplierQuoteId=r.id;p.supplierQuoteNumber=r.number;p.supplierQuoteResponseId=response.id;p.quotedFreightCents=response.freightCents;p.quotedSelection=chosen.filter(i=>i.supplierId===supplierId);r.purchaseIds.push(p.id);}
  r.selections=chosen;r.selectedAt=date;A.touch(r,date,action,input);
 }else if(action==='close'||action==='cancel'){r[action==='close'?'closedAt':'cancelledAt']=date;A.touch(r,date,action,input,{reason:A.reason(input)});}else throw Error('Ação de cotação inválida.');
});}
module.exports={supplierQuoteAction};
