const {randomUUID}=require('node:crypto');
const {text,integer,dateOnly,items,record,reason,baseRecord,touch,expected,cents,run,safe}=require('./advanced-common');
const {availableQuantity}=require('./public/workflow-core');const {supplierReturnSummary,receiptReturnRemaining}=require('./public/supplier-return-core');const {movement}=require('./domain');const {calendarDay}=require('./public/reports');const {addRetention}=require('./quarantine');
function origin(state,input){const purchase=record(state,'purchases',input.purchaseId),receipt=purchase.receipts.find(r=>r.id===input.receiptId);if(!receipt)throw Error('Entrega de origem não encontrada.');return {purchase,receipt};}
function preparedItems(state,input){const {receipt}=origin(state,input);return items(input.items).map(i=>{const original=receipt.items.find(o=>o.productId===i.productId),quantity=integer(i.quantity,'Quantidade');if(!original||quantity>receiptReturnRemaining(state,input.purchaseId,input.receiptId,i.productId))throw Error('Quantidade acima do recebido ainda não devolvido.');if(!['sellable','quarantine'].includes(i.source))throw Error('Selecione a origem física.');if(i.source==='quarantine'){const held=record(state,'quarantineEntries',i.quarantineEntryId);if(held.productId!==i.productId||held.origin?.id!==input.purchaseId||held.origin?.receiptId!==input.receiptId)throw Error('Entrada retida não pertence à entrega.');}return {productId:i.productId,name:original.name,quantity,source:i.source,quarantineEntryId:i.source==='quarantine'?i.quarantineEntryId:null,unitCostCents:original.unitCostCents,acceptedQuantity:0,refusedQuantity:0,returnedQuantity:0};});}
function supplierReturnAction(state,action,input){return run(state,'supplierReturns',action,input,(next,date)=>{
 let row=action==='create'?null:record(next,'supplierReturns',input.id);if(row)expected(row,input);
 if(action==='create'||action==='edit'){
  if(row&&(row.dispatchedAt||row.cancelledAt))throw Error('Somente preparações abertas podem ser editadas.');const {purchase,receipt}=origin(next,input),prepared=preparedItems(next,input),totalCents=safe(prepared.reduce((n,i)=>n+safe(i.quantity*i.unitCostCents),0),'Valor de referência'),fields={purchaseId:purchase.id,purchaseNumber:purchase.number,receiptId:receipt.id,supplierId:purchase.supplierId,supplierName:purchase.supplierName,items:prepared,totalCents,reason:reason(input),reference:text(input.reference,120,'Referência'),refunds:[]};
  if(row){if(row.purchaseId!==purchase.id||row.receiptId!==receipt.id)throw Error('A origem da preparação deve ser preservada.');const before=structuredClone(row.items);Object.assign(row,fields);touch(row,date,action,input,{before});}else next.supplierReturns.push(baseRecord(next,'supplierReturns',date,input,fields));return;
 }
 if(row.cancelledAt)throw Error('Preparação cancelada preserva seu histórico.');
 if(action==='cancel'){if(row.dispatchedAt)throw Error('Unidades expedidas não voltam automaticamente.');row.cancelledAt=date;touch(row,date,action,{...input,reason:reason(input)});return;}
 if(action==='dispatch'){
  if(row.dispatchedAt)throw Error('Devolução já expedida.');for(const i of row.items){if(i.quantity>receiptReturnRemaining(next,row.purchaseId,row.receiptId,i.productId))throw Error('Outra devolução comprometeu esta entrega.');const p=record(next,'products',i.productId);if(i.source==='sellable'){if(i.quantity>availableQuantity(next,p))throw Error('Saída compromete reservas ou ultrapassa vendável.');if(input.expectedStocks&&input.expectedStocks[p.id]!==p.stock)throw Error('Estoque mudou.');p.stock-=i.quantity;movement(next,p,-i.quantity,'supplierReturn',row.id,row.reason,date);}else{const held=record(next,'quarantineEntries',i.quarantineEntryId);if(i.quantity>held.remainingQuantity)throw Error('Saldo retido insuficiente.');if(input.expectedQuarantineVersions&&input.expectedQuarantineVersions[held.id]!==held.version)throw Error('Entrada retida mudou.');held.remainingQuantity-=i.quantity;held.dispositions.push({date,type:'supplierReturn',quantity:i.quantity,referenceId:row.id,reason:row.reason});touch(held,date,'supplierReturn',input);}}
  row.dispatchedAt=date;row.dispatchReference=text(input.reference,120,'Referência');touch(row,date,action,input);return;
 }
 if(!row.dispatchedAt)throw Error('Expeça antes de declarar resposta ou restituição.');
 if(action==='accept'||action==='refuse'||action==='physicalreturn'){
  items(input.items);for(const i of input.items){const line=row.items.find(o=>o.productId===i.productId),quantity=integer(i.quantity,'Quantidade');if(!line)throw Error('Produto fora da devolução.');
   if(action==='physicalreturn'){
    if(quantity>line.refusedQuantity-line.returnedQuantity)throw Error('Retorno físico acima das unidades recusadas pendentes.');const p=record(next,'products',line.productId);if(i.destination==='sellable'){if(p.active===false)throw Error('Reative o produto antes de retornar ao vendável.');p.stock=safe(p.stock+quantity);movement(next,p,quantity,'supplierReturnBack',row.id,reason(input),date);}else if(i.destination==='quarantine')addRetention(next,p.id,quantity,date,input,{kind:'supplierReturns',id:row.id,purchaseId:row.purchaseId,receiptId:row.receiptId});else throw Error('Escolha o destino físico.');line.returnedQuantity+=quantity;
   }else{if(quantity>line.quantity-line.acceptedQuantity-line.refusedQuantity)throw Error('Resposta acima das unidades expedidas sem decisão.');line[action==='accept'?'acceptedQuantity':'refusedQuantity']+=quantity;}
  }const declaredDate=dateOnly(input.declaredDate,'Data declarada',true);if(declaredDate>calendarDay())throw Error('Data efetiva não pode ser futura.');touch(row,date,action,{...input,reason:reason(input)},{declaredDate,reference:text(input.reference,120,'Referência'),items:structuredClone(input.items)});return;
 }
 if(action==='refund'){
  const summary=supplierReturnSummary(row),amountCents=cents(input.value),paidDate=dateOnly(input.paidDate,'Data do recebimento',true),method=input.paymentMethod;if(paidDate>calendarDay()||!['cash','pix','debit','credit','other'].includes(method))throw Error('Data ou forma efetiva inválida.');if(amountCents>summary.referencePendingCents||input.expectedRefundCents!==summary.referencePendingCents)throw Error('Restituição acima da referência aceita ou saldo alterado.');const refund={id:randomUUID(),amountCents,paidDate,date:paidDate+'T12:00:00-03:00',paymentMethod:method,responsible:text(input.responsible,120,'Responsável'),reference:text(input.reference,120,'Referência'),reason:reason(input),cashSessionId:null};
  if(input.cashSessionId){const {openCash,cashSummary}=require('./public/cash-core'),cash=openCash(next);if(method!=='cash'||paidDate!==calendarDay()||!cash||cash.id!==input.cashSessionId||cashSummary(cash).expectedCents!==input.expectedCashCents)throw Error('Vínculo com Caixa alterado ou incompatível.');refund.cashSessionId=cash.id;cash.movements.push({id:randomUUID(),type:'supplierRefund',amountCents,paymentMethod:'cash',date,referenceId:refund.id,note:row.supplierName,responsible:refund.responsible});cashSummary(cash);}
  row.refunds.push(refund);touch(row,date,action,input);return;
 }
 throw Error('Ação de devolução ao fornecedor inválida.');
 });}
module.exports={supplierReturnAction};
