const {randomUUID}=require('crypto');const {command,expectedVersion,nextNumber}=require('./commands');const {optional}=require('./domain');const {validDay}=require('./public/reports');const {receivableRows}=require('./public/accounts-core');
function validateLink(state,link){if(!link)return null;const kinds=['products','customers','suppliers','sales','quotes','purchases','payables','reservations','inventories','quarantineEntries','expenseBudgets','deliveries','supplierQuotes','supplierReturns','agreements','recurringOccurrences','procedureExecutions','purchaseOccurrences','priceReviews','transfers'];if(!kinds.includes(link.kind))throw Error('Tipo de vínculo inválido.');const r=state[link.kind]?.find(r=>r.id===link.id);if(!r)throw Error('Registro de vínculo não encontrado.');if(link.installmentId){const parts=link.kind==='sales'?receivableRows(r):link.kind==='payables'?r.installments:[];if(!parts.some(i=>i.id===link.installmentId))throw Error('Parcela do vínculo não encontrada.');}return {kind:link.kind,id:link.id,installmentId:link.installmentId||null,name:r.name||r.customerName||r.supplierName||r.description||'Registro '+r.number};}
function taskAction(state,action,input){return command(state,'tasks',action,input,(next,date)=>{
 next.tasks||=[];next.hiddenOperations||=[];
 if(action==='hide'||action==='restore'){const key=optional(input.key,240);if(!key)throw Error('Informe a pendência.');if(action==='hide'&&!require('./public/business-core').operationRows(next).some(r=>r.key===key))throw Error('Esta pendência não existe mais na posição atual.');const reason=optional(input.reason,1000);if(!reason)throw Error('Informe o motivo.');let r=next.hiddenOperations.find(r=>r.key===key);if(!r){r={id:randomUUID(),key,history:[]};next.hiddenOperations.push(r);}r.hidden=action==='hide';r.history.push({date,hidden:r.hidden,reason,responsible:optional(input.responsible,120)});return;}
 let r=action==='create'?null:next.tasks.find(r=>r.id===input.id);if(action!=='create')expectedVersion(r,input,'Esta tarefa');if(r?.cancelledAt)throw Error('Tarefa cancelada preserva seu histórico.');
 const before=r?{title:r.title,dueDate:r.dueDate,priority:r.priority,status:r.completedAt?'completed':'open',responsible:r.responsible}:null;
 if(action==='create'||action==='edit'){
  if(r?.completedAt)throw Error('Reabra a tarefa antes de editar.');const title=optional(input.title,160),dueDate=optional(input.dueDate,10),priority=input.priority||'normal';if(!title)throw Error('Informe o título da tarefa.');if(dueDate&&!validDay(dueDate))throw Error('Informe uma data real.');if(!['low','normal','high'].includes(priority))throw Error('Prioridade inválida.');const fields={title,dueDate:dueDate||null,priority,responsible:optional(input.responsible,120),note:optional(input.note,1000),link:validateLink(next,input.link),updatedAt:date};if(r)Object.assign(r,fields);else{r={id:randomUUID(),number:nextNumber(next.tasks),version:0,date,history:[],...fields};next.tasks.push(r);}
 }else if(action==='complete'){if(r.completedAt)throw Error('Tarefa já concluída.');r.completedAt=date;r.completionNote=optional(input.note,1000);}
 else if(action==='reopen'){if(!r.completedAt)throw Error('Tarefa já aberta.');r.completedAt=null;r.reopenReason=optional(input.reason,1000);if(!r.reopenReason)throw Error('Informe o motivo da reabertura.');}
 else if(action==='cancel'){r.cancelledAt=date;r.cancelReason=optional(input.reason,1000);if(!r.cancelReason)throw Error('Informe o motivo do cancelamento.');}
 else throw Error('Ação de tarefa inválida.');r.version++;r.updatedAt=date;r.history.push({date,action,before,responsible:optional(input.responsible,120),note:optional(input.note||input.reason,1000)});
});}
module.exports={taskAction,validateLink};
