const test=require('node:test'),assert=require('node:assert/strict');
const {payableAction}=require('./payables'),{payableBalance,payableStatus,payableSummary,splitCents}=require('./public/payables-core');
const {purchaseAction,supplierAction}=require('./purchases'),{sale,change}=require('./server'),{quoteAction,activeAction}=require('./quotes');
const {cashAction}=require('./cash'),{cashSummary}=require('./public/cash-core'),{expense,cancelExpense}=require('./domain'),{movementSummary,calendarDay}=require('./public/reports');
const {incomingProduct,replenishmentRows}=require('./public/replenishment-core'),{discountTotals}=require('./public/discount-core'),{exportCsv}=require('./export');
const {persistDatabase,readDatabase,validateDatabase}=require('./storage');
let serial=0;const key=()=> 'own-v9-'+(++serial);
function initial(){return {products:[{id:'p',name:'Produto',code:'P',stock:2,minStock:10,priceCents:1000},{id:'b',name:'Bolsa',stock:0,minStock:0,priceCents:2000}],customers:[{id:'c',name:'Cliente'}],sales:[],suppliers:[{id:'f',name:'Fabricante'}]};}
function create(db=initial(),extra={}){return payableAction(db,'create',{supplierId:'f',description:'Mercadorias',value:'100.01',dueDates:['2026-09-30'],requestId:key(),...extra});}
function action(db,type,extra={}){const p=db.payables[0];return payableAction(db,type,{id:p.id,expectedVersion:p.version,installmentId:p.installments[0].id,requestId:key(),...extra});}
function pay(db,extra={}){return action(db,'pay',{value:'20.00',paymentMethod:'pix',paidDate:calendarDay(),...extra});}
function buy(db=initial(),quantity=5){db=purchaseAction(db,'create',{supplierId:'f',items:[{productId:'p',quantity,unitCost:'10.00'}],requestId:key()});return purchaseAction(db,'confirm',{id:db.purchases[0].id,expectedVersion:1,requestId:key()});}
test('obrigação e parcelas exatas não movimentam dinheiro ou mercadoria',()=>{const old=initial(),next=create(old,{dueDates:['2026-09-30','2026-10-30','']});assert.deepEqual(next.products,old.products);assert.deepEqual(next.expenses,[]);assert.equal(next.payables[0].totalCents,10001);assert.deepEqual(next.payables[0].installments.map(i=>i.amountCents),[3334,3334,3333]);assert.equal(next.payables[0].installments[2].dueDate,null);assert.equal(payableStatus(next.payables[0]),'open');assert.equal(old.payables,undefined);});
test('limites de parcelas precisão vencimento e fornecedor são recusados',()=>{for(const data of [{value:'0'},{value:'1.999'},{dueDates:Array(61).fill('')},{dueDates:['2026-02-30']},{supplierId:'inexistente'},{description:''}])assert.throws(()=>create(initial(),data));assert.deepEqual(splitCents(101,2),[51,50]);assert.throws(()=>splitCents(2,3));});
test('compra exige confirmação revisão e justificativa de diferença',()=>{const db=buy();assert.throws(()=>create(db,{purchaseId:db.purchases[0].id,expectedPurchaseVersion:2}),/diferença/);const next=create(db,{purchaseId:db.purchases[0].id,expectedPurchaseVersion:2,differenceReason:'Frete combinado'});assert.equal(next.payables[0].purchaseTotalCents,5000);assert.equal(next.payables[0].totalCents,10001);assert.equal(next.products[0].stock,2);assert.throws(()=>create(db,{purchaseId:db.purchases[0].id,expectedPurchaseVersion:1}),/mudou/);});
test('referência repetida e segunda conta de compra exigem aviso reconhecido',()=>{let db=create(initial(),{reference:'REF-1'});assert.throws(()=>create(db,{reference:'ref-1'}),/repetição/);db=create(db,{reference:'ref-1',acknowledgeDuplicate:true});assert.equal(db.payables.length,2);let order=buy();order=create(order,{purchaseId:order.purchases[0].id,expectedPurchaseVersion:2,value:'50.00'});assert.throws(()=>create(order,{purchaseId:order.purchases[0].id,expectedPurchaseVersion:2,value:'50.00'}),/repetição/);});
test('reenvio de criação pagamento e cancelamento é exato e não duplica',()=>{const requestId=key(),payload={supplierId:'f',description:'Fatura',value:'100',dueDates:[''],requestId};let db=payableAction(initial(),'create',payload);assert.deepEqual(payableAction(db,'create',payload),db);assert.throws(()=>payableAction(db,'create',{...payload,value:'101'}),/outros dados/);const p=db.payables[0],payment={id:p.id,expectedVersion:1,installmentId:p.installments[0].id,value:'20',paymentMethod:'pix',paidDate:calendarDay(),requestId:key()};db=payableAction(db,'pay',payment);assert.deepEqual(payableAction(db,'pay',payment),db);assert.equal(db.expenses.length,1);assert.throws(()=>payableAction(db,'pay',{...payment,value:'21'}),/outros dados/);const cancel={id:p.id,expectedVersion:2,reason:'Acordo',requestId:key()};db=payableAction(db,'cancel',cancel);assert.deepEqual(payableAction(db,'cancel',cancel),db);assert.equal(db.payables[0].payments.length,1);});
test('edição mantém criação e snapshot; versão velha e conta paga não editam',()=>{let db=create(),date=db.payables[0].date;db=action(db,'edit',{supplierId:'f',description:'Conta ajustada',value:'99.00',dueDates:['2026-10-15','2026-11-15'],reference:'R'});assert.equal(db.payables[0].date,date);assert.equal(db.payables[0].version,2);assert.equal(db.auditLog[0].kind,'payable');assert.throws(()=>action(db,'edit',{expectedVersion:1}),/mudou/);db=pay(db);assert.throws(()=>action(db,'edit'),/pagamentos/);});
test('pagamento parcial e integral gera despesa única e não altera estoque',()=>{let db=create(),products=structuredClone(db.products);db=pay(db);assert.equal(payableStatus(db.payables[0]),'partial');assert.deepEqual(payableBalance(db.payables[0]),{paidCents:2000,remainingCents:8001,cancelledCents:0});db=pay(db,{value:'80.01',paymentMethod:'debit'});assert.equal(payableStatus(db.payables[0]),'paid');assert.equal(db.expenses.length,2);assert.equal(movementSummary([],db.expenses).expenseCents,10001);assert.deepEqual(db.products,products);assert.throws(()=>pay(db),/saldo/);});
test('versão e limites protegem pagamentos simultâneos e falhas atômicas',()=>{const db=create(),before=JSON.stringify(db),p=db.payables[0];assert.throws(()=>pay(db,{value:'100.02'}),/saldo/);assert.throws(()=>pay(db,{paidDate:'2200-01-01'}),/futura/);assert.throws(()=>pay(db,{value:'1.001'}),/casas/);assert.equal(JSON.stringify(db),before);const next=pay(db,{value:'90'});assert.throws(()=>pay(next,{expectedVersion:p.version,value:'90'}),/mudou/);assert.equal(next.expenses.length,1);});
test('pagamento em dinheiro e despesa são atômicos com Caixa atual e saldo',()=>{let db=cashAction(initial(),'open',{responsible:'Operador',openingValue:'50'});db=create(db);const c=db.cashSessions[0],before=structuredClone(db);assert.throws(()=>pay(db,{value:'60',paymentMethod:'cash',cashSessionId:c.id,expectedCashCents:5000}),/insuficiente/);assert.deepEqual(db,before);assert.throws(()=>pay(db,{paymentMethod:'pix',cashSessionId:c.id,expectedCashCents:5000}),/dinheiro/);assert.throws(()=>pay(db,{paymentMethod:'cash',cashSessionId:c.id,expectedCashCents:4900}),/saldo do Caixa/);db=pay(db,{paymentMethod:'cash',cashSessionId:c.id,expectedCashCents:5000});assert.equal(cashSummary(db.cashSessions[0]).expectedCents,3000);assert.equal(db.cashSessions[0].movements.length,1);assert.equal(db.expenses[0].cashSessionId,c.id);});
test('dinheiro externo e pagamento antigo não reescrevem gaveta; vínculo antigo recusado',()=>{let db=cashAction(initial(),'open',{responsible:'Operador',openingValue:'50'});db=create(db);const id=db.cashSessions[0].id;assert.throws(()=>pay(db,{paymentMethod:'cash',paidDate:'2026-01-01',cashSessionId:id,expectedCashCents:5000}),/hoje/);db=pay(db,{paymentMethod:'cash',paidDate:'2026-01-01'});assert.equal(cashSummary(db.cashSessions[0]).expectedCents,5000);assert.equal(db.expenses[0].cashSessionId,null);});
test('cancelar saldo preserva pagamentos despesas e dinheiro',()=>{let db=pay(create());const expenses=structuredClone(db.expenses);assert.throws(()=>action(db,'cancel',{reason:''}),/motivo/);db=action(db,'cancel',{reason:'Fornecedor dispensou restante'});assert.deepEqual(db.expenses,expenses);assert.deepEqual(payableBalance(db.payables[0]),{paidCents:2000,remainingCents:0,cancelledCents:8001});assert.throws(()=>pay(db),/cancelado/);assert.throws(()=>cancelExpense(db,db.expenses[0].id),/vinculada/);});
test('vincular despesa existente não cria saída nem movimento adicional',()=>{let db=cashAction(initial(),'open',{responsible:'Operador',openingValue:'50'});db=expense(db,{description:'Fornecedor já pago',value:'20',paidDate:calendarDay(),paymentMethod:'cash',cashSessionId:db.cashSessions[0].id});db=create(db);const oldCash=structuredClone(db.cashSessions),expenseId=db.expenses[0].id;assert.throws(()=>action(db,'link',{expenseId}),/fornecedor/);db=action(db,'link',{expenseId,acknowledgeSupplier:true});assert.equal(db.expenses.length,1);assert.deepEqual(db.cashSessions,oldCash);assert.equal(payableBalance(db.payables[0]).paidCents,2000);assert.throws(()=>action(db,'link',{expenseId,acknowledgeSupplier:true}),/vinculada/);assert.throws(()=>cancelExpense(db,expenseId),/vinculada/);});
test('resumo separa vencidas hoje sem vencimento e saldo cancelado',()=>{let db=create(initial(),{value:'30',dueDates:['2026-09-29','2026-09-30','']});assert.deepEqual(payableSummary(db.payables,'2026-09-30'),{paidCents:0,remainingCents:3000,cancelledCents:0,undatedCents:1000,overdueCents:1000,todayCents:1000});db=pay(db,{value:'5'});db=action(db,'cancel',{reason:'Acordo'});assert.equal(payableSummary(db.payables,'2026-09-30').remainingCents,0);assert.equal(payableSummary(db.payables,'2026-09-30').paidCents,500);});
test('CSV protegido distingue obrigação de pagamento e descontos líquidos',()=>{const db=create(initial(),{description:'=TESTE'}),csv=exportCsv(db,'payables',[db.payables[0].id]).body;assert.ok(csv.includes("'=TESTE"));assert.ok(csv.includes('100,01'));assert.ok(csv.includes('Saldo cancelado'));const sold=sale(db,{items:[{productId:'p',quantity:1}],paymentMethod:'pix',paymentStatus:'pending',discount:'1.01',discountReason:'Negociação'});assert.ok(exportCsv(sold,'discounts',[sold.sales[0].id]).body.includes('8,99'));});
test('desconto inválido não baixa estoque e subtotal antigo equivale a zero desconto',()=>{const db=initial(),input={items:[{productId:'p',quantity:1}],paymentMethod:'pix',paymentStatus:'pending'};for(const data of [{discount:'10',discountReason:'Igual'},{discount:'-1',discountReason:'Erro'},{discount:'1.999',discountReason:'Precisão'},{discount:'1'}])assert.throws(()=>sale(db,{...input,...data}));assert.equal(db.products[0].stock,2);const sold=sale(db,{...input,discount:'1.01',discountReason:'Negociação'});assert.equal(sold.sales[0].subtotalCents,1000);assert.equal(sold.sales[0].totalCents,899);assert.equal(sold.sales[0].discountCents,101);assert.equal(sold.sales[0].receipts.length,0);assert.equal(sale(db,input).sales[0].discountCents,0);});
test('reenvio com desconto alterado recusado; recebimento usa total líquido',()=>{const db=initial(),input={items:[{productId:'p',quantity:1}],paymentMethod:'cash',paymentStatus:'received',discount:'2',discountReason:'Oferta',requestId:key()};const sold=sale(db,input);assert.equal(sold.sales[0].receipts[0].amountCents,800);assert.deepEqual(sale(sold,input),sold);assert.throws(()=>sale(sold,{...input,discount:'3'}),/outros dados/);});
test('orçamento edição cópia atualização e conversão preservam desconto autorizado',()=>{let db=quoteAction(initial(),'create',{items:[{productId:'p',quantity:1}],discount:'2',discountReason:'Acordo',requestId:key()},sale),q=db.quotes[0];assert.equal(q.totalCents,800);db.products[0].priceCents=1500;db=quoteAction(db,'prices',{id:q.id,expectedVersion:1,expectedPrices:[{productId:'p',priceCents:1500}],requestId:key()},sale);q=db.quotes[0];assert.equal(q.totalCents,1300);const copy=quoteAction(db,'create',{sourceId:q.id,sourceVersion:q.version,items:q.items,discount:'2',discountReason:'Acordo',requestId:key()},sale);assert.equal(copy.quotes[1].discountCents,200);db=quoteAction(db,'convert',{id:q.id,expectedVersion:2,paymentMethod:'pix',paymentStatus:'received',discount:'14',requestId:key()},sale);assert.equal(db.sales[0].totalCents,1300);assert.equal(db.sales[0].discountCents,200);assert.equal(db.sales[0].receipts[0].amountCents,1300);});
test('atualização de preço que invalida desconto é recusada inteira',()=>{let db=quoteAction(initial(),'create',{items:[{productId:'p',quantity:1}],discount:'9',discountReason:'Oferta',requestId:key()},sale);db.products[0].priceCents=800;const before=structuredClone(db);assert.throws(()=>quoteAction(db,'prices',{id:db.quotes[0].id,expectedVersion:1,expectedPrices:[{productId:'p',priceCents:800}],requestId:key()},sale),/menor/);assert.deepEqual(db,before);});
test('reposição desconta entregas previstas mas não aumenta disponível',()=>{let db=buy(initial(),5),row=replenishmentRows(db).find(p=>p.id==='p');assert.equal(row.stock,2);assert.equal(row.incoming,5);assert.equal(row.suggested,3);assert.equal(incomingProduct(db.purchases,'p')[0].quantity,5);db=purchaseAction(db,'receive',{id:db.purchases[0].id,expectedVersion:2,items:[{productId:'p',quantity:2}],requestId:key()});row=replenishmentRows(db).find(p=>p.id==='p');assert.equal(row.stock,4);assert.equal(row.incoming,3);assert.equal(row.suggested,3);db=purchaseAction(db,'close',{id:db.purchases[0].id,expectedVersion:3,reason:'Sem restante',requestId:key()});assert.equal(replenishmentRows(db).find(p=>p.id==='p').suggested,6);assert.equal(replenishmentRows(db).find(p=>p.id==='b').suggested,0);});
test('previsão pode ser reprogramada com motivo histórico e versão sem mudar itens',()=>{let db=buy(),p=db.purchases[0],items=structuredClone(p.items);assert.throws(()=>purchaseAction(db,'reschedule',{id:p.id,expectedVersion:2,expectedDate:'2026-10-01',requestId:key()}),/Explique/);db=purchaseAction(db,'reschedule',{id:p.id,expectedVersion:2,expectedDate:'2026-10-01',reason:'Prazo fornecedor',responsible:'Operador',requestId:key()});assert.deepEqual(db.purchases[0].items,items);assert.equal(db.purchases[0].scheduleHistory.length,1);assert.equal(db.auditLog[0].responsible,'Operador');assert.equal(db.products[0].stock,2);assert.throws(()=>purchaseAction(db,'reschedule',{id:p.id,expectedVersion:2,requestId:key()}),/mudou/);});
test('edição de cadastro e situação protegem duas janelas e registram campos futuros',()=>{const db=initial(),edited=change(db,'/api/products/edit',{id:'p',expectedVersion:0,name:'Novo',price:'11',responsible:'Operador'});assert.equal(edited.products[0].version,1);assert.equal(edited.auditLog[0].changes.find(c=>c.field==='name').before,'Produto');assert.throws(()=>change(edited,'/api/products/edit',{id:'p',expectedVersion:0,name:'Velho',price:'10'}),/mudou/);assert.throws(()=>activeAction(edited,'products',{id:'p',active:false,expectedVersion:0}),/mudou/);const supplier=supplierAction(db,'edit',{id:'f',name:'Nome novo',expectedVersion:0});assert.throws(()=>supplierAction(supplier,'edit',{id:'f',name:'Outro',expectedVersion:0}),/mudou/);});
test('estrutura e versão de dados inválidas interrompem gravação',()=>{for(const db of [{...initial(),purchases:[{id:'invalid'}]},{...initial(),cashSessions:[{id:'invalid'}]},{},{products:[],customers:[],sales:[],schemaVersion:3},{...initial(),products:[{id:'p',name:'X',stock:-1,priceCents:100}]}])assert.throws(()=>validateDatabase(db));const original=initial();assert.equal(validateDatabase(original),original);});
test('falha de gravação mantém original e reenvio exato persiste uma vez',()=>{let file=JSON.stringify(initial()),temp;const io={existsSync:p=>p.endsWith('.tmp')?!!temp:true,readFileSync:()=>file,writeFileSync:(p,v)=>{temp=v;},renameSync:()=>{throw Error('Sem espaço');},unlinkSync:()=>{temp=undefined;}};const before=file,next=create(JSON.parse(file));assert.throws(()=>persistDatabase('fake.json',next,io),/gravar/);assert.equal(file,before);assert.equal(temp,undefined);assert.deepEqual(readDatabase('fake.json',io),initial());io.renameSync=()=>{file=temp;temp=undefined;};const saved=persistDatabase('fake.json',next,io);assert.equal(saved.schemaVersion,2);assert.equal(readDatabase('fake.json',io).payables.length,1);});

test('despesa sem informação válida não pode ser vinculada a parcela',()=>{const db=create();db.expenses.push({id:'legacy',description:'Antiga',amountCents:1000,paidDate:'2026-01-01'});assert.throws(()=>action(db,'link',{expenseId:'legacy',acknowledgeSupplier:true}),/forma de pagamento/);assert.equal(db.payables[0].payments.length,0);});



