const {randomUUID}=require('node:crypto');
const {command,expectedVersion,nextNumber,safe}=require('./commands');
const {optional,movement}=require('./domain');
const {validDay,calendarDay}=require('./public/reports');
const {moneyCents}=require('./money');
const {isActive}=require('./public/quotes-core');
const {discountTotals}=require('./public/discount-core');
const {receiptList,paymentBalance}=require('./public/payments');
const {linkExpense}=require('./cash');
const {inventoryStatus,stockToken,inventoryPreview,inventorySummary,saleAllocation,returnPreview,returnedQuantity,returnedCents,availableQuantity,reservationStatus,refundBalance}=require('./public/workflow-core');
const quantity=(value,zero=false)=>{if(!['number','string'].includes(typeof value)||typeof value==='string'&&!value.trim())throw Error('Informe uma quantidade inteira.');const n=Number(value);if(!Number.isSafeInteger(n)||n<(zero?0:1))throw Error('Informe uma quantidade inteira '+(zero?'não negativa.':'maior que zero.'));return n;};
function uniqueItems(items){if(!Array.isArray(items)||!items.length||items.length>500)throw Error('Selecione de 1 a 500 produtos.');const ids=new Set();for(const i of items){if(ids.has(i.productId))throw Error('Produto repetido.');ids.add(i.productId);}}
function reason(input){const text=optional(input.reason,1000);if(!text)throw Error('Informe o motivo desta operação.');return text;}
function inventoryAction(state,action,input){return command(state,'inventory',action,input,(next,date)=>{
 next.inventories||=[];let r=action==='create'?null:next.inventories.find(r=>r.id===input.id);if(r)expectedVersion(r,input,'Este inventário');else if(action!=='create')throw Error('Inventário não encontrado.');
 if(r&&inventoryStatus(r)!=='draft')throw Error('Inventário concluído ou cancelado não pode ser alterado.');
 if(action==='create'){
  if(input.positionScope!==undefined)require('./positions').validPosition(next,input.positionScope);if(input.blind!==undefined&&typeof input.blind!=='boolean')throw Error('Escolha o modo da coleta.');const name=optional(input.name,120);if(!name)throw Error('Identifique a contagem.');uniqueItems(input.items);
  const items=input.items.map(i=>{const p=next.products.find(p=>p.id===i.productId);if(!p||!isActive(p)&&input.includeInactive!==true)throw Error('Selecione produtos ativos ou autorize incluir inativos.');return {productId:p.id,name:p.name,code:p.code||'',barcode:p.barcode||'',expectedStock:input.positionScope!==undefined?require('./public/positions-core').positionQuantity(next,p,input.positionScope):p.stock,expectedGlobalStock:p.stock,positionToken:require('./public/positions-core').positionToken(p),stockToken:stockToken(next,p.id),counted:null,note:''};});
  next.inventories.push({id:randomUUID(),number:nextNumber(next.inventories),version:1,name,date,responsible:optional(input.responsible,120),note:optional(input.note,1000),items,rebases:[],blind:!!input.blind,...(input.positionScope!==undefined?{positionScope:input.positionScope,positionName:require('./positions').validPosition(next,input.positionScope).name}:{}),collectionHistory:[]});
 }else if(action==='add'){
  uniqueItems(input.items);if(r.items.length+input.items.length>500)throw Error('Limite de 500 produtos no inventário.');for(const i of input.items){if(r.items.some(o=>o.productId===i.productId))throw Error('Produto já está na sessão.');const p=next.products.find(p=>p.id===i.productId);if(!p)throw Error('Produto não encontrado.');r.items.push({productId:p.id,name:p.name,code:p.code||'',barcode:p.barcode||'',expectedStock:r.positionScope!==undefined?require('./public/positions-core').positionQuantity(next,p,r.positionScope):p.stock,expectedGlobalStock:p.stock,positionToken:require('./public/positions-core').positionToken(p),stockToken:stockToken(next,p.id),counted:null,note:''});}r.version++;r.updatedAt=date;
 }else if(['collect','reopen','close'].includes(action)){if(action==='collect'){if(r.items.some(i=>i.counted===null))throw Error('Conte todos os itens antes de encerrar a coleta.');r.collectedAt=date;r.collectionHistory||=[];r.collectionHistory.push({date,action,responsible:optional(input.responsible,120)});}else if(action==='reopen'){if(!r.collectedAt)throw Error('A coleta já está aberta.');delete r.collectedAt;r.collectionHistory.push({date,action,reason:reason(input)});}else{r.cancelledAt=date;r.closedWithoutAdjustment=true;r.reason=reason(input);r.collectionHistory.push({date,action,reason:r.reason});}r.version++;r.updatedAt=date;
 }else if(action==='recount'){uniqueItems(input.items);if(!r.collectedAt)throw Error('Encerre a coleta antes de selecionar recontagem.');for(const i of input.items){const row=r.items.find(a=>a.productId===i.productId);if(!row)throw Error('Produto fora da sessão.');row.recountRequired=true;row.finalDecision=null;}r.version++;r.updatedAt=date;
 }else if(action==='count'){
  uniqueItems(input.items);for(const i of input.items){const row=r.items.find(o=>o.productId===i.productId);if(!row)throw Error('Produto fora deste inventário.');if(r.collectedAt&&Number(i.countNumber||1)===1)throw Error('Reabra a coleta para alterar a primeira contagem.');const phase=Number(i.countNumber||1);if(![1,2].includes(phase))throw Error('Escolha primeira ou segunda contagem.');row.counts||=[row.counted,null];row.countNotes||=[row.note||'',''];if(phase===2&&row.counts[0]===null)throw Error('Registre a primeira contagem antes da segunda.');row.countHistory||=[];row.countHistory.push({date,countNumber:phase,previous:row.counts[phase-1],previousNote:row.countNotes[phase-1]});row.counts[phase-1]=quantity(i.counted,true);row.countNotes[phase-1]=optional(i.note,500);row.conferents||=[];row.conferents[phase-1]={name:optional(i.conferent||input.responsible,120),date};if(row.recountRequired)row.finalDecision=null;row.selectedCount||=1;row.counted=row.counts[row.selectedCount-1];row.note=row.countNotes[row.selectedCount-1];}r.version++;r.updatedAt=date;
 }else if(action==='choose'){
  uniqueItems(input.items);for(const i of input.items){const row=r.items.find(o=>o.productId===i.productId),phase=Number(i.countNumber);if(!row||![1,2].includes(phase)||row.counts?.[phase-1]===null||row.counts?.[phase-1]===undefined)throw Error('A contagem escolhida ainda não foi registrada.');if((r.blind||r.positionScope!==undefined||row.recountRequired)&&row.counts[0]!==row.counts[1])reason(input);row.finalDecision={date,countNumber:phase,reason:input.reason?reason(input):'',responsible:optional(input.responsible,120)};row.selectedCount=phase;row.counted=row.counts[phase-1];row.note=row.countNotes[phase-1];}r.version++;r.updatedAt=date;
 }else if(action==='rebase'){
  const why=reason(input),changes=[];for(const i of r.items){const p=next.products.find(p=>p.id===i.productId);if(!p)throw Error('Produto não encontrado.');changes.push({productId:p.id,before:i.expectedStock,after:p.stock,counted:i.counted,counts:i.counts,countNotes:i.countNotes,note:i.note});i.expectedStock=r.positionScope!==undefined?require('./public/positions-core').positionQuantity(next,p,r.positionScope):p.stock;i.expectedGlobalStock=p.stock;i.positionToken=require('./public/positions-core').positionToken(p);i.stockToken=stockToken(next,p.id);if(!(r.blind||r.positionScope!==undefined)){i.counted=null;i.counts=[null,null];i.countNotes=['',''];i.selectedCount=1;i.note='';}else{delete i.finalDecision;i.recountRequired=true;}}r.rebases.push({date,reason:why,changes});r.version++;r.updatedAt=date;
 }else if(action==='apply'){
  if((r.blind||r.positionScope!==undefined)&&!r.collectedAt)throw Error('Encerre a coleta antes de revisar ajustes.');if(r.items.some(i=>i.recountRequired&&(!i.finalDecision||i.counts?.[1]===null||i.counts?.[1]===undefined)))throw Error('Conclua recontagens e decisões finais.');const rows=inventoryPreview(next,r),summary=inventorySummary(rows);if(summary.missing)throw Error('Preencha a contagem de todos os produtos.');if(summary.conflicts)throw Error('O estoque mudou durante a contagem. Confira as movimentações e atualize a referência explicitamente.');
  if(rows.some(i=>(r.positionScope!==undefined?i.currentGlobalStock+i.difference:i.counted)<i.reserved))throw Error('A contagem fica abaixo das reservas abertas. Regularize as reservas antes de aplicar.');
  const why=summary.changed?reason(input):optional(input.reason,1000);for(const i of rows){const p=next.products.find(p=>p.id===i.productId);if(i.difference){p.stock=r.positionScope!==undefined?safe(p.stock+i.difference,'Estoque'):i.counted;if(r.positionScope!==undefined&&r.positionScope){require('./positions').validPosition(next,r.positionScope);p.positionBalances||={};p.positionBalances[r.positionScope]=i.counted;}movement(next,p,i.difference,'inventory',r.id,why,date);if(r.positionScope!==undefined){const m=next.stockMovements.at(-1);m.positionHandled=true;m.positionAllocations=[{positionId:r.positionScope,name:r.positionName,quantity:Math.abs(i.difference)}];next.positionMovements||=[];next.positionMovements.push({id:randomUUID(),date,productId:p.id,productName:p.name,from:i.difference<0?r.positionScope:null,to:i.difference>0?r.positionScope:null,fromName:i.difference<0?r.positionName:null,toName:i.difference>0?r.positionName:null,quantity:Math.abs(i.difference),referenceId:r.id,type:'inventory',reason:why,stockMovementId:m.id});}}const saved=r.items.find(o=>o.productId===i.productId);saved.difference=i.difference;saved.finalStock=i.counted;}
  r.appliedAt=date;r.reason=why;r.summary=summary;r.version++;r.updatedAt=date;
 }else if(action==='cancel'){r.cancelledAt=date;r.reason=reason(input);r.version++;r.updatedAt=date;}else throw Error('Ação de inventário inválida.');
});}
function returnAction(state,action,input){return command(state,'returns',action,input,(next,date)=>{
 const s=next.sales.find(s=>s.id===input.saleId);if(!s)throw Error('Venda não encontrada.');if(s.cancelledAt)throw Error('Venda cancelada não aceita devolução de itens.');if((s.returnVersion||0)!==input.expectedVersion)throw Error('As devoluções desta venda mudaram. Confira as quantidades atuais antes de revisar novamente.');
 if(action==='create'){
  s.receipts=receiptList(s);const why=reason(input);uniqueItems(input.items);const items=input.items.map(i=>{const original=s.items.find(o=>o.productId===i.productId);const q=quantity(i.quantity);if(!original||q>original.quantity-returnedQuantity(s,i.productId))throw Error('Devolução acima do saldo vendido.');const restockQuantity=i.restockQuantity===undefined?(typeof i.restock==='boolean'?(i.restock?q:0):null):quantity(i.restockQuantity,true);if(restockQuantity===null||restockQuantity>q)throw Error('Informe quantas unidades podem voltar ao estoque, sem ultrapassar a devolução.');return {productId:i.productId,quantity:q,restockQuantity,restock:restockQuantity>0,note:optional(i.note,500)};});
  const reviewed=returnPreview(s,items);for(const i of reviewed){if(i.restockQuantity){const p=next.products.find(p=>p.id===i.productId);if(!p)throw Error('Produto não encontrado.');safe(p.stock+i.restockQuantity,'Estoque');if(input.expectedStocks&&input.expectedStocks[i.productId]!==p.stock)throw Error('O estoque mudou. Reabra a revisão da devolução.');}}
  s.returnAllocation||=saleAllocation(s);const r={id:randomUUID(),number:nextNumber(next.sales.flatMap(s=>s.returns||[])),date,reason:why,responsible:optional(input.responsible,120),items:reviewed,totalCents:safe(reviewed.reduce((n,i)=>n+i.amountCents,0),'Crédito da devolução')};s.returns||=[];s.returns.push(r);
  for(const i of reviewed)if(i.restockQuantity){const p=next.products.find(p=>p.id===i.productId);p.stock+=i.restockQuantity;movement(next,p,i.restockQuantity,'return',r.id,why,date);next.stockMovements.at(-1).saleId=s.id;}
  require('./quarantine').quarantineReturn(next,s,r,input,date);
  require('./store-credits').creditReturn(next,s,r,date);
  const balance=paymentBalance(s);if(balance.known)s.paymentStatus=balance.remainingCents===0?'received':balance.receivedCents>0?'partial':'pending';s.returnVersion=(s.returnVersion||0)+1;
 }else if(action==='refund'){
  const balance=refundBalance({...s,receipts:receiptList(s)}),amountCents=moneyCents(input.value);if(amountCents>balance.availableCents)throw Error('A devolução de dinheiro ultrapassa o valor efetivamente recebido e creditado.');if(input.expectedRefundCents!==balance.availableCents)throw Error('O saldo de devolução mudou. Revise novamente.');
  if(!['cash','pix','debit','credit','other'].includes(input.paymentMethod))throw Error('Informe a forma efetiva da devolução.');const paidDate=input.paidDate;if(!validDay(paidDate)||paidDate>calendarDay())throw Error('Informe uma data efetiva sem usar futuro.');
  const why=reason(input),expense={id:randomUUID(),description:'Devolução ao cliente: '+s.customerName,amountCents,paidDate,paymentMethod:input.paymentMethod,cashSessionId:null,note:why,createdAt:date,saleRefundId:s.id};
  const cash=require('./public/cash-core').openCash(next);if(input.cashSessionId&&(!cash||input.expectedCashCents!==require('./public/cash-core').cashSummary(cash).expectedCents))throw Error('O Caixa mudou. Revise novamente.');linkExpense(next,expense,input);if(expense.cashSessionId){const m=cash.movements.at(-1);m.type='refund';m.referenceId=s.id;m.note=why;}
  // A devolução entra no histórico da venda e do Caixa; não criar outra despesa na consulta de movimentações.
  s.refunds||=[];s.refunds.push({id:expense.id,amountCents,paymentMethod:expense.paymentMethod,date:paidDate+'T12:00:00-03:00',paidDate,cashSessionId:expense.cashSessionId,note:why,returnRefund:true,recordedAt:date});s.returnVersion=(s.returnVersion||0)+1;
 }else throw Error('Ação de devolução inválida.');
});}
function reservationAction(state,action,input,sale){return command(state,'reservations',action,input,(next,date)=>{
 next.reservations||=[];const r=action==='create'?null:next.reservations.find(r=>r.id===input.id);if(action!=='create')expectedVersion(r,input,'Esta reserva');
 if(r&&reservationStatus(r)!=='open'&&!(reservationStatus(r)==='expired'&&['renew','cancel'].includes(action)))throw Error('Reserva convertida ou cancelada não pode ser alterada.');
 if(action==='create'||action==='edit'){
  const customer=next.customers.find(c=>c.id===input.customerId);if(!isActive(customer))throw Error('Selecione um cliente ativo para a reserva.');uniqueItems(input.items);
  const validUntil=optional(input.validUntil,10);if(validUntil&&(!validDay(validUntil)||validUntil<calendarDay()))throw Error('Informe uma validade real de hoje em diante.');
  const items=input.items.map(i=>{const p=next.products.find(p=>p.id===i.productId),q=quantity(i.quantity);if(!isActive(p))throw Error('Selecione produtos ativos.');if(q>availableQuantity(next,p,r?.id))throw Error('Saldo livre insuficiente: '+p.name+'.');if(i.priceCents!==undefined&&i.priceCents!==p.priceCents)throw Error('Preço mudou. Revise a reserva.');return {productId:p.id,name:p.name,code:p.code||'',quantity:q,priceCents:p.priceCents};});
  const pricing=discountTotals(items.reduce((n,i)=>safe(n+i.quantity*i.priceCents,'Subtotal'),0),input.discount||'0',input.discountReason||'');
  const fields={customerId:customer.id,customerName:customer.name,validUntil,items,...pricing,note:optional(input.note,1000),responsible:optional(input.responsible,120),updatedAt:date};if(r){Object.assign(r,fields);r.version++;}else next.reservations.push({id:randomUUID(),number:nextNumber(next.reservations),version:1,date,...fields});
 }else if(action==='renew'){
  if(r.items.some(i=>{const p=next.products.find(p=>p.id===i.productId);return !isActive(p)||i.quantity>availableQuantity(next,p,r.id);}))throw Error('Confira os cadastros e o saldo livre antes de renovar.');
  const validUntil=optional(input.validUntil,10);if(validUntil&&(!validDay(validUntil)||validUntil<calendarDay()))throw Error('Informe uma validade real de hoje em diante.');r.renewals||=[];r.renewals.push({date,previous:r.validUntil,validUntil:validUntil||null,reason:reason(input)});r.validUntil=validUntil||null;r.version++;r.updatedAt=date;
 }else if(action==='cancel'){r.cancelledAt=date;r.reason=reason(input);r.version++;r.updatedAt=date;}
 else if(action==='convert'){
  if(!isActive(next.customers.find(c=>c.id===r.customerId)))throw Error('Cliente inativo.');r.saleId='converting';
  const offer=require('./pricing').validatedOffer(next,{...input,items:r.items,customerId:r.customerId,discount:String((r.discountCents||0)/100)});
  const priced=r.items.map(i=>{const p=next.products.find(p=>p.id===i.productId),selected=offer?.items.find(p=>p.productId===i.productId),priceCents=selected?.priceCents??p?.priceCents;if(!isActive(p)||input.expectedPrices?.find(o=>o.productId===i.productId)?.priceCents!==priceCents)throw Error('Preços ou cadastros mudaram. Reabra a revisão da conversão.');return {...i,...(selected||{}),priceCents};});
  const result=sale(next,{customerId:r.customerId,items:priced.map(i=>({productId:i.productId,quantity:i.quantity,priceCents:i.priceCents})),paymentMethod:input.paymentMethod,paymentStatus:input.paymentStatus,dueDate:input.dueDate,expectedCashSessionId:input.expectedCashSessionId},{...r,items:priced,...(offer?{negotiation:offer}:{})});Object.assign(next,result);const saved=next.reservations.find(o=>o.id===r.id),created=next.sales.at(-1);saved.saleId=created.id;saved.convertedAt=date;saved.version++;created.reservationId=saved.id;created.reservationNumber=saved.number;
 }else throw Error('Ação de reserva inválida.');
});}
module.exports={inventoryAction,returnAction,reservationAction,quantity};
