'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
function fixture(){
 let submit,finish;const timers=[],shown=[],sandbox={window:{foundationContext:{user:{id:'admin'},sessionId:'s1',companyId:'c1',unitId:'u1'}},foundationAfterRender(){},foundationChooseContext(){},foundationAuthScreen(){},foundationAdmin(){},extraPageHandlers:{},extraPageTitles:{},navigationGroups:[{id:'commercial',pages:[]}],commercialRecordActions:()=>'',commercialBindRowActions(){},field:()=>'',esc:v=>String(v),commercialDate:v=>v,foundationModal:(title,body,label,handler)=>submit=handler,foundationRequest:()=>new Promise(resolve=>finish=resolve),setTimeout:fn=>timers.push(fn)};
 vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../public/foundation-operations.js'),'utf8'),sandbox);sandbox.accessDialog=(title,body)=>shown.push({title,body});sandbox.accessAdminReset('target','Pessoa sintética');
 const form={isConnected:true,elements:{operatorPassword:{value:'senha sintética'},reason:{value:'Recuperação sintética'}}};return {sandbox,form,timers,shown,submit:()=>submit(form),finish:()=>finish({resetCode:'synthetic-code',expiresAt:'2026-10-02T20:00:00Z'})};
}
test('reset UI mostra código apenas na sessão/contexto solicitante após resposta',async()=>{const f=fixture(),pending=f.submit();f.finish();await pending;assert.equal(f.form.elements.operatorPassword.value,'');assert.equal(f.timers.length,1);f.timers[0]();assert.equal(f.shown.length,1);assert.match(f.shown[0].body,/synthetic-code/);});
test('resposta tardia do reset não mostra código após logout, outra sessão ou contexto',async()=>{for(const change of [f=>f.sandbox.window.foundationContext=null,f=>f.sandbox.window.foundationContext.sessionId='s2',f=>f.sandbox.window.foundationContext.unitId='u2',f=>f.form.isConnected=false]){const f=fixture(),pending=f.submit();change(f);f.finish();await pending;assert.equal(f.timers.length,0);assert.equal(f.shown.length,0);assert.equal(f.form.elements.operatorPassword.value,'');}});
test('reset UI revalida contexto no callback adiado que exibe código',async()=>{const f=fixture(),pending=f.submit();f.finish();await pending;f.sandbox.window.foundationContext.user.id='outro';f.timers[0]();assert.equal(f.shown.length,0);});
