'use strict';
// HTTP contract tests use synthetic identities and in-memory databases exclusively.
const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {fixture,profile}=require('./http-fixture'),{loadState}=require('./scoped-state'),{writeState,canonical}=require('./state-repository');
const {createCompany,createUnit}=require('./entities'),{grantCompanyAccess,grantUnitAccess}=require('./access'),{assignRole}=require('./rbac');
const BASE='/api/commercial/',EDITOR=['catalog.view','catalog.manage'],SELLER=['catalog.view','sales.view','sales.create'];
const PRIVATE='REGISTRATION-PRIVATE-MARKER';
function base(){return{products:[{id:'product',name:'Produto existente',stock:10,priceCents:1000,code:'P001',barcode:'0000123',category:'Acessórios',minStock:5,active:true,version:3,costCents:991,custom:{unknownFinancial:PRIVATE}}],customers:[{id:'customer',name:'Cliente existente',phone:'11900000000',email:'fixture@example.test',notes:'Contato autorizado',active:true,version:2,custom:{unknownFinancial:PRIVATE}}],sales:[],suppliers:[{id:'supplier',name:'Fornecedor atual',phone:'11900000001',email:'supplier@example.test',active:true,version:2,custom:{unknownFinancial:PRIVATE}}],purchases:[{id:'purchase',number:1,supplierId:'supplier',supplierName:'Fornecedor histórico',version:3,confirmedAt:'2020-01-01T12:00:00Z',date:'2020-01-01T10:00:00Z',totalCents:1000,items:[{productId:'product',name:'Nome no pedido',quantity:2,unitCostCents:500}],receipts:[{id:'receipt',sequence:1,date:'2020-01-02T12:00:00Z',custom:{unknownFinancial:PRIVATE},items:[{productId:'product',name:'Nome no recebimento',quantity:1,unitCostCents:625,originalUnitCostCents:500,costReason:'Custo conferido',custom:{unknownFinancial:PRIVATE}}]}]}]};}
function get(f,scope=f.scope){return loadState(f.store,scope);}
function update(f,fn,scope=f.scope){const before=get(f,scope),next=structuredClone(before.state);fn(next);f.store.transaction(()=>writeState(f.store,scope,next,before.revision));}
async function scenario(t,options={}){const f=await fixture(t),initial=get(f);f.store.transaction(()=>writeState(f.store,f.scope,options.state||base(),initial.revision));f.editor=await profile(f,options.permissions||EDITOR,'registration-editor');return f;}
function denied(result,statuses=[400,401,403,409,422]){assert.ok(statuses.includes(result.status),result.text);assert.equal(typeof result.data.error,'string');assert.doesNotMatch(result.text,/SQLITE|FOREIGN KEY|password_hash|\bat .*\.js:\d+/i);}
function safeRecord(record){assert.equal(typeof record.id,'string');for(const key of ['stock','minStock','costCents','unitCostCents','minimumPriceCents','custom','unknownFinancial','history','execution','receipts'])assert.equal(Object.hasOwn(record,key),false,key);assert.equal(JSON.stringify(record).includes(PRIVATE),false);}
function route(kind,action){return BASE+kind+(action==='create'?(kind==='suppliers'?'/create':''):'/'+action);}
function createInput(kind,extra={}){return{name:'Cadastro sintético '+kind,requestId:randomUUID(),...(kind==='products'?{price:'12.34',stock:0,code:'NEW-'+randomUUID().slice(0,8),barcode:'0000999'}:{phone:'11912345678',email:'new@example.test',notes:'Contato'}),...extra};}
function editInput(kind,record,extra={}){return{id:record.id,expectedVersion:record.version,name:record.name+' editado',...(kind==='products'?{price:'10.00'}:{phone:record.phone,email:record.email,notes:record.notes||''}),...extra};}

test('GET detalhes dos três cadastros exige só leitura e retorna DTO sem estoque custo ou extras',async t=>{
 const f=await scenario(t),reader=await profile(f,['catalog.view'],'registration-reader');for(const[kind,id]of [['products','product'],['customers','customer'],['suppliers','supplier']]){const result=await reader.client.call(BASE+kind+'/by-id?id='+id);assert.equal(result.status,200,result.text);assert.deepEqual(Object.keys(result.data),['record']);safeRecord(result.data.record);assert.equal(result.data.record.id,id);assert.equal(result.data.record.version,kind==='products'?3:2);}
 denied(await reader.client.call('/api/state'),[403]);const blocked=await profile(f,['catalog.manage'],'registration-no-view');denied(await blocked.client.call(BASE+'products/by-id?id=product'),[403]);
});

test('GET detalhe do produto mostra mínimo somente com inventory.view sem revelar saldo custo ou extras',async t=>{
 const f=await scenario(t),onlyCatalog=await f.editor.client.call(BASE+'products/by-id?id=product');assert.equal(onlyCatalog.status,200,onlyCatalog.text);safeRecord(onlyCatalog.data.record);const inventoryReader=await profile(f,['catalog.view','inventory.view'],'registration-minimum-reader'),allowed=await inventoryReader.client.call(BASE+'products/by-id?id=product');assert.equal(allowed.status,200,allowed.text);assert.equal(allowed.data.record.minStock,5);const withoutMinimum={...allowed.data.record};delete withoutMinimum.minStock;safeRecord(withoutMinimum);assert.equal(allowed.data.record.version,3);assert.equal(get(f).state.products[0].minStock,5);
});

test('GET detalhes/custo rejeitam parâmetros desconhecidos repetidos vazios e identificador estrangeiro',async t=>{
 const f=await scenario(t,{permissions:['catalog.view','financial.view']});for(const suffix of ['', '?id=', '?id=product&id=product','?id=product&companyId='+f.scope.companyId])denied(await f.editor.client.call(BASE+'products/by-id'+suffix),[422]);for(const suffix of ['', '?productId=', '?productId=product&productId=product','?productId=product&include=stock'])denied(await f.editor.client.call(BASE+'product-costs'+suffix),[422]);
 const c=createCompany(f.store,{name:'Outra empresa'}),u=createUnit(f.store,c.id,{name:'Outra unidade'}),scope={companyId:c.id,unitId:u.id};f.store.transaction(()=>writeState(f.store,scope,{products:[{id:'foreign-product',name:'Privado',stock:8,priceCents:100}],customers:[],sales:[]},0));for(const query of ['products/by-id?id=foreign-product','product-costs?productId=foreign-product'])denied(await f.editor.client.call(BASE+query),[404]);
});

test('GET custo exige catálogo+financeiro e usa recibo efetivo sem histórico extra ou custo inventado',async t=>{
 const f=await scenario(t),finance=await profile(f,['catalog.view','financial.view'],'registration-cost-reader'),onlyFinance=await profile(f,['financial.view'],'registration-finance-only');denied(await f.editor.client.call(BASE+'product-costs?productId=product'),[403]);denied(await onlyFinance.client.call(BASE+'product-costs?productId=product'),[403]);const result=await finance.client.call(BASE+'product-costs?productId=product');assert.equal(result.status,200,result.text);assert.deepEqual(result.data.cost,{productId:'product',productName:'Nome no recebimento',unitCostCents:625,supplierName:'Fornecedor histórico',date:'2020-01-02T12:00:00Z',sequence:1,purchaseId:'purchase',purchaseNumber:1});assert.equal(result.data.revision,get(f).revision);assert.equal(result.text.includes(PRIVATE),false);
 update(f,state=>state.products.push({id:'uncosted',name:'Sem recebimento',stock:0,priceCents:100,costCents:888}));const missing=await finance.client.call(BASE+'product-costs?productId=uncosted');assert.equal(missing.status,200,missing.text);assert.equal(missing.data.cost,null);
});

test('GET checkout-context exige três direitos e retorna só identidade do Caixa aberto sem financeiro',async t=>{
 const f=await scenario(t),seller=await profile(f,SELLER,'registration-checkout');let result=await seller.client.call(BASE+'sales/checkout-context');assert.equal(result.status,200,result.text);assert.deepEqual(result.data,{cashSessionId:null});const opened=await f.owner.call('/api/cash/open',{requestId:randomUUID(),openingValue:'12.34',responsible:'Sintético'});assert.equal(opened.status,201,opened.text);const cash=get(f).state.cashSessions[0];result=await seller.client.call(BASE+'sales/checkout-context');assert.equal(result.status,200,result.text);assert.deepEqual(result.data,{cashSessionId:cash.id});
 for(const removed of SELLER){const restricted=await profile(f,SELLER.filter(p=>p!==removed),'checkout-without-'+removed.replace('.','-'));denied(await restricted.client.call(BASE+'sales/checkout-context'),[403]);}denied(await seller.client.call(BASE+'sales/checkout-context?companyId='+f.scope.companyId),[422]);
});

test('POST criação parcial dos três cadastros não exige financeiro/estoque e devolve DTO limitado',async t=>{
 const f=await scenario(t);for(const kind of ['products','customers','suppliers']){const input=createInput(kind),result=await f.editor.client.call(route(kind,'create'),input);assert.equal(result.status,201,result.text);assert.equal(result.data.replayed,false);safeRecord(result.data.record);assert.equal(result.data.record.version,1);const record=get(f).state[kind].find(r=>r.id===result.data.record.id);assert.equal(record.name,input.name);if(kind==='products'){assert.equal(record.stock,0);assert.equal(record.barcode,'0000999');}}
 denied(await f.editor.client.call('/api/state'),[403]);
});

test('POST estoque inicial positivo exige ajuste, grava movimento/executor juntos e mantém DTO sem saldo',async t=>{
 const f=await scenario(t),before=get(f),input=createInput('products',{stock:3});denied(await f.editor.client.call(route('products','create'),input),[403]);assert.equal(canonical(get(f)),canonical(before));const adjuster=await profile(f,[...EDITOR,'inventory.adjust'],'registration-stock-adjust');const result=await adjuster.client.call(route('products','create'),input);assert.equal(result.status,201,result.text);safeRecord(result.data.record);const state=get(f).state,record=state.products.find(r=>r.id===result.data.record.id),movement=state.stockMovements.find(m=>m.productId===record.id);assert.equal(record.stock,3);assert.equal(movement.quantity,3);assert.equal(movement.stockAfter,3);assert.equal(movement.type,'initial');assert.equal(movement.execution.executedBy,adjuster.user.id);
});

test('POST minStock explicitado inclusive zero exige consultar+ajustar estoque; omissão preserva mínimo existente',async t=>{
 const f=await scenario(t),record=get(f).state.products[0],before=get(f);for(const rights of [EDITOR,[...EDITOR,'inventory.view'],[...EDITOR,'inventory.adjust']]){const user=await profile(f,rights,'minimum-'+randomUUID());for(const minStock of [0,8]){denied(await user.client.call(route('products','edit'),editInput('products',record,{minStock})),[403]);denied(await user.client.call(route('products','create'),createInput('products',{minStock})),[403]);}}assert.equal(canonical(get(f)),canonical(before));
 let result=await f.editor.client.call(route('products','edit'),editInput('products',record));assert.equal(result.status,201,result.text);assert.equal(get(f).state.products[0].minStock,5);const adjuster=await profile(f,[...EDITOR,'inventory.view','inventory.adjust'],'minimum-full'),current=get(f).state.products[0];result=await adjuster.client.call(route('products','edit'),editInput('products',current,{minStock:8}));assert.equal(result.status,201,result.text);assert.equal(get(f).state.products[0].minStock,8);safeRecord(result.data.record);
});

test('POST edição preserva extras custo saldo identificadores e vinculação histórica; versão muda sem duplicar',async t=>{
 const f=await scenario(t);for(const kind of ['products','customers','suppliers']){const before=get(f),original=before.state[kind][0],result=await f.editor.client.call(route(kind,'edit'),editInput(kind,original));assert.equal(result.status,201,result.text);safeRecord(result.data.record);const updated=get(f).state[kind][0];assert.equal(updated.version,original.version+1);assert.deepEqual(updated.custom,original.custom);assert.equal(get(f).state[kind].length,before.state[kind].length);if(kind==='products'){assert.equal(updated.stock,original.stock);assert.equal(updated.costCents,original.costCents);assert.equal(updated.barcode,'0000123');assert.equal(updated.minStock,5);}assert.equal(get(f).state.purchases[0].supplierName,'Fornecedor histórico');assert.equal(get(f).state.purchases[0].receipts[0].items[0].unitCostCents,625);}
});

test('POST criação é idempotente por requestId/conteúdo e reenvio alterado não cria outro cadastro',async t=>{
 const f=await scenario(t);for(const kind of ['products','customers','suppliers']){const input=createInput(kind),first=await f.editor.client.call(route(kind,'create'),input);assert.equal(first.status,201,first.text);const before=get(f),events=f.store.db.prepare('SELECT count(*) n FROM audit_events').get().n,replayed=await f.editor.client.call(route(kind,'create'),input);assert.equal(replayed.status,201,replayed.text);assert.equal(replayed.data.record.id,first.data.record.id);assert.equal(replayed.data.replayed,true);assert.equal(canonical(get(f)),canonical(before));assert.equal(f.store.db.prepare('SELECT count(*) n FROM audit_events').get().n,events);denied(await f.editor.client.call(route(kind,'create'),{...input,name:'Conteúdo mudou'}),[409]);assert.equal(canonical(get(f)),canonical(before));}
});

test('POST edição/ativação exigem versão e versão obsoleta não altera estado; criação exige requestId',async t=>{
 const f=await scenario(t);for(const kind of ['products','customers','suppliers']){const original=get(f).state[kind][0],before=get(f);for(const expectedVersion of [undefined,original.version-1]){denied(await f.editor.client.call(route(kind,'edit'),editInput(kind,original,{expectedVersion})),[409,422]);denied(await f.editor.client.call(route(kind,'active'),{id:original.id,expectedVersion,active:false}),[409,422]);}denied(await f.editor.client.call(route(kind,'create'),createInput(kind,{requestId:undefined})),[422]);assert.equal(canonical(get(f)),canonical(before));const result=await f.editor.client.call(route(kind,'active'),{id:original.id,expectedVersion:original.version,active:false});assert.equal(result.status,201,result.text);assert.equal(result.data.record.active,false);safeRecord(result.data.record);assert.equal(get(f).state[kind][0].version,original.version+1);}
});

test('POST sem cada direito ou após revogação e com CSRF/Origin inválidos não grava cadastro',async t=>{
 const f=await scenario(t),before=get(f);for(const permissions of [['catalog.view'],['catalog.manage']]){const restricted=await profile(f,permissions,'registration-restricted-'+randomUUID());for(const kind of ['products','customers','suppliers'])denied(await restricted.client.call(route(kind,'create'),createInput(kind)),[403]);}
 denied(await f.editor.client.call(route('products','create'),createInput('products'),{'X-CSRF-Token':'invalid'}),[403]);denied(await f.editor.client.call(route('products','create'),createInput('products'),{Origin:'https://foreign.invalid'}),[403]);f.store.db.prepare('DELETE FROM role_permissions WHERE company_id=? AND role_id=? AND permission_code=?').run(f.scope.companyId,f.editor.role.id,'catalog.manage');denied(await f.editor.client.call(route('products','create'),createInput('products')),[403]);assert.equal(canonical(get(f)),canonical(before));
});

test('POST identidade/prova campos desconhecidos custo e saldo de edição não são autoridade do cliente',async t=>{
 const f=await scenario(t),original=get(f).state.products[0],before=get(f);for(const extra of [{stock:0},{stock:99},{costCents:1},{unitCostCents:1},{companyId:f.scope.companyId},{userId:f.ownerId},{authorizedBy:f.ownerId},{proof:{authorizedBy:f.ownerId}},{custom:{tampered:true}}])denied(await f.editor.client.call(route('products','edit'),editInput('products',original,extra)),[422]);assert.equal(canonical(get(f)),canonical(before));
});

test('POST identificadores existentes só em outra empresa retornam404 e não editam/desativam terceiros',async t=>{
 const f=await scenario(t),c=createCompany(f.store,{name:'Empresa estrangeira sintética'}),u=createUnit(f.store,c.id,{name:'Unidade estrangeira'}),scope={companyId:c.id,unitId:u.id},foreign={products:[{id:'foreign-products',name:'Produto privado',stock:0,priceCents:1000,version:1}],customers:[{id:'foreign-customers',name:'Cliente privado',version:1}],suppliers:[{id:'foreign-suppliers',name:'Fornecedor privado',version:1}],sales:[]};f.store.transaction(()=>writeState(f.store,scope,foreign,0));const ownBefore=get(f),foreignBefore=get(f,scope);
 for(const kind of ['products','customers','suppliers']){const record=foreign[kind][0];denied(await f.editor.client.call(route(kind,'edit'),editInput(kind,record)),[404]);denied(await f.editor.client.call(route(kind,'active'),{id:record.id,expectedVersion:record.version,active:false}),[404]);}assert.equal(canonical(get(f)),canonical(ownBefore));assert.equal(canonical(get(f,scope)),canonical(foreignBefore));
});

test('POST valores inválidos e código duplicado incluindo inativo não deixam cadastro parcial',async t=>{
 const f=await scenario(t),before=get(f);for(const extra of [{name:''},{price:'-1'},{stock:-1},{stock:1.5},{barcode:123},{code:'P001'},{barcode:'0000123'}])denied(await f.owner.call(route('products','create'),createInput('products',extra)),[400,409,422]);update(f,state=>state.products[0].active=false);const inactive=get(f);denied(await f.owner.call(route('products','create'),createInput('products',{code:'P001'})),[400,409,422]);assert.equal(canonical(get(f)),canonical(inactive));assert.equal(get(f).state.products.length,before.state.products.length);
});

test('POST falha de auditoria desfaz SQL cadastro revisão e requestId; retry confirma uma vez',async t=>{
 const f=await scenario(t),input=createInput('products'),before=get(f),events=f.store.db.prepare('SELECT count(*) n FROM audit_events').get().n;f.store.db.exec("CREATE TRIGGER deny_registration_audit BEFORE INSERT ON audit_events WHEN NEW.entity='products' BEGIN SELECT RAISE(ABORT,'synthetic registration rollback'); END;");denied(await f.editor.client.call(route('products','create'),input),[500]);assert.equal(canonical(get(f)),canonical(before));assert.equal(f.store.db.prepare('SELECT count(*) n FROM audit_events').get().n,events);f.store.db.exec('DROP TRIGGER deny_registration_audit');const first=await f.editor.client.call(route('products','create'),input);assert.equal(first.status,201,first.text);assert.equal(first.data.replayed,false);const replayed=await f.editor.client.call(route('products','create'),input);assert.equal(replayed.status,201,replayed.text);assert.equal(replayed.data.record.id,first.data.record.id);assert.equal(get(f).state.products.length,before.state.products.length+1);
});

test('POST duas edições concorrentes da mesma versão confirmam uma alteração e preservam mínimo/extras',async t=>{
 const f=await scenario(t),record=get(f).state.products[0],input=editInput('products',record),results=await Promise.all([f.editor.client.call(route('products','edit'),{...input,name:'Primeiro'}),f.editor.client.call(route('products','edit'),{...input,name:'Segundo'})]);assert.equal(results.filter(r=>r.status===201).length,1);denied(results.find(r=>r.status!==201),[409]);const saved=get(f).state.products[0];assert.equal(saved.version,record.version+1);assert.equal(saved.minStock,5);assert.deepEqual(saved.custom,record.custom);
});

test('GET/POST contextos com mesmos IDs não misturam cadastro custo Caixa nem reenvio; aba antiga é rejeitada',async t=>{
 const f=await scenario(t,{permissions:[...EDITOR,'financial.view','sales.view','sales.create']}),sibling=createUnit(f.store,f.scope.companyId,{name:'Unidade irmã'}),scope={companyId:f.scope.companyId,unitId:sibling.id},other=base();other.products[0].name='Produto da outra unidade';other.purchases[0].receipts[0].items[0].unitCostCents=777;other.purchases[0].receipts[0].items[0].costReason='Custo da outra unidade';f.store.transaction(()=>{writeState(f.store,scope,other,0);grantUnitAccess(f.store,f.editor.user.id,scope.companyId,scope.unitId);assignRole(f.store,f.editor.user.id,scope.companyId,scope.unitId,f.editor.role.id);});
 const input=createInput('customers'),first=await f.editor.client.call(route('customers','create'),input);assert.equal(first.status,201,first.text);const selected=await f.editor.client.call('/api/auth/context',scope);assert.equal(selected.status,200,selected.text);const headers={'X-Company-ID':f.scope.companyId,'X-Unit-ID':f.scope.unitId};denied(await f.editor.client.call(BASE+'products/by-id?id=product',undefined,headers),[409]);denied(await f.editor.client.call(route('products','edit'),editInput('products',base().products[0]),headers),[409]);const detail=await f.editor.client.call(BASE+'products/by-id?id=product');assert.equal(detail.data.record.name,'Produto da outra unidade');const cost=await f.editor.client.call(BASE+'product-costs?productId=product');assert.equal(cost.data.cost.unitCostCents,777);assert.deepEqual((await f.editor.client.call(BASE+'sales/checkout-context')).data,{cashSessionId:null});
 const repeated=await f.editor.client.call(route('customers','create'),input);assert.equal(repeated.status,201,repeated.text);assert.equal(repeated.data.replayed,false);assert.notEqual(repeated.data.record.id,first.data.record.id);assert.equal(get(f).state.products[0].name,'Produto existente');assert.equal(get(f,scope).state.products[0].name,'Produto da outra unidade');
});

test('POST preview calcula preço/desconto de inativo sem conceder autorização ou alterar qualquer dado comercial',async t=>{
 const f=await scenario(t),seller=await profile(f,SELLER,'registration-preview');update(f,state=>state.products[0].active=false);const input={requestId:randomUUID(),customerId:'customer',items:[{productId:'product',quantity:2,priceCents:1000}],paymentMethod:'pix',paymentStatus:'received',expectedCashSessionId:null,discount:'1.00',discountReason:'Desconto informado'},before=get(f),events=f.store.db.prepare('SELECT count(*) n FROM audit_events').get().n,grants=f.store.db.prepare('SELECT count(*) n FROM inactive_sale_approvals').get().n,result=await seller.client.call(BASE+'sales/preview',input);assert.equal(result.status,200,result.text);assert.equal(result.data.offer.items[0].priceCents,1000);assert.equal(result.data.subtotalCents,2000);assert.equal(result.data.totalCents,1900);assert.equal(result.data.expectedOffer,result.data.offer.signature);assert.equal(result.data.approvalToken,undefined);for(const key of ['stock','costCents','unitCostCents','minimumPriceCents','receipts','cashSessions'])assert.equal(Object.hasOwn(result.data.offer.items[0],key),false,key);assert.equal(result.text.includes(PRIVATE),false);assert.equal(canonical(get(f)),canonical(before));assert.equal(f.store.db.prepare('SELECT count(*) n FROM audit_events').get().n,events);assert.equal(f.store.db.prepare('SELECT count(*) n FROM inactive_sale_approvals').get().n,grants);denied(await seller.client.call(BASE+'sales',{...input,expectedOffer:result.data.expectedOffer}),[403,409]);assert.equal(canonical(get(f)),canonical(before));
});

test('POST preview exige permissões/CSRF, rejeita credenciais e não dispensa revisão do preço na venda',async t=>{
 const f=await scenario(t),seller=await profile(f,SELLER,'registration-preview-security'),input={requestId:randomUUID(),items:[{productId:'product',quantity:1,priceCents:1000}],paymentMethod:'pix',paymentStatus:'received',expectedCashSessionId:null};for(const removed of SELLER){const restricted=await profile(f,SELLER.filter(p=>p!==removed),'preview-without-'+removed.replace('.','-'));denied(await restricted.client.call(BASE+'sales/preview',input),[403]);}denied(await seller.client.call(BASE+'sales/preview',input,{'X-CSRF-Token':'invalid'}),[403]);for(const extra of [{approverPassword:'Credencial sintética 2026!'},{authorizedBy:f.ownerId},{proof:{authorizedBy:f.ownerId}}])denied(await seller.client.call(BASE+'sales/preview',{...input,...extra}),[422]);const preview=await seller.client.call(BASE+'sales/preview',input);assert.equal(preview.status,200,preview.text);update(f,state=>state.products[0].priceCents=1100);const before=get(f);denied(await seller.client.call(BASE+'sales',{...input,expectedOffer:preview.data.expectedOffer}),[400,409,422]);assert.equal(canonical(get(f)),canonical(before));
});
