'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {SqlStore}=require('./sql-store'),{createCompany,createUnit}=require('./entities');
const {writeState}=require('./state-repository'),{loadState}=require('./scoped-state');
const {hydrateCustomers,queryCustomers,getCustomer,normalizeAllCommercial,verifyCommercial}=require('./commercial-store');
function fixture(t,customers){const s=new SqlStore(':memory:',{environment:'test'}),c=createCompany(s,{name:'Sintética'}),u=createUnit(s,c.id,{name:'Sintética'}),scope={companyId:c.id,unitId:u.id},state={products:[],customers:customers||[{id:'c',name:'Cliente'}],sales:[]};s.transaction(()=>writeState(s,scope,state,0));t.after(()=>s.close());return{s,scope,state};}
test('Clientes possuem colunas reais e preservam contatos documentos notas e extras',t=>{const value=JSON.parse('{"id":"c","name":"Cliente","phone":"+55 00","email":"a@example.test","contactName":"Contato","address":"Endereço fictício","document":"00123","commercialId":"ANTIGO","notes":"Observações","active":false,"version":2,"date":"2020-01-01","updatedAt":null,"preferredPriceListId":null,"history":[{"kind":"old","who":"declarado"}],"__proto__":{"preserve":true},"custom":null}');const{s,scope,state}=fixture(t,[value]),row=s.db.prepare('SELECT * FROM commercial_customers').get();assert.equal(row.phone,'+55 00');assert.equal(row.document,'00123');assert.equal(row.commercial_id,'ANTIGO');assert.equal(row.notes,'Observações');assert.equal(row.active,0);assert.deepEqual(hydrateCustomers(s,scope),state.customers);assert.equal(Object.hasOwn(hydrateCustomers(s,scope)[0],'__proto__'),true);assert.deepEqual(verifyCommercial(s).units[0].customers.count,1);});
test('Cliente antigo sem active/version/documento permanece sem campos fabricados',t=>{const{s,scope,state}=fixture(t,[{id:'c',name:'Cliente',phone:null,email:{legacy:'opaque'}}]);assert.deepEqual(loadState(s,scope).state,state);const c=getCustomer(s,scope,'c');assert.equal(Object.hasOwn(c,'version'),false);assert.equal(Object.hasOwn(c,'active'),false);assert.equal(Object.hasOwn(c,'document'),false);assert.equal(c.phone,null);assert.deepEqual(c.email,{legacy:'opaque'});});
test('Clientes SQL mantêm ordem e pai referenciado durante reordenação',t=>{const{s,scope,state}=fixture(t,[{id:'c1',name:'Um'},{id:'c2',name:'Dois'}]);s.db.exec('CREATE TABLE future_customer_ref(company_id TEXT,unit_id TEXT,customer_id TEXT,FOREIGN KEY(company_id,unit_id,customer_id) REFERENCES commercial_customers(company_id,unit_id,id)) STRICT;');s.db.prepare('INSERT INTO future_customer_ref VALUES(?,?,?)').run(scope.companyId,scope.unitId,'c1');const next=structuredClone(state);next.customers.reverse();next.customers[1].name='Atualizado';s.transaction(()=>writeState(s,scope,next,1));assert.deepEqual(hydrateCustomers(s,scope),next.customers);assert.equal(s.db.prepare('SELECT count(*) n FROM future_customer_ref').get().n,1);});
test('mesmo Cliente ID em empresa e unidade distintas não atravessa leitura/escrita',t=>{const{s,scope}=fixture(t),c=createCompany(s,{name:'Outra'}),u=createUnit(s,c.id,{name:'Outra'}),other={companyId:c.id,unitId:u.id},u2=createUnit(s,scope.companyId,{name:'Outra na mesma empresa'}),sameCompany={companyId:scope.companyId,unitId:u2.id};s.transaction(()=>{writeState(s,other,{products:[],customers:[{id:'c',name:'Privado outra empresa'}],sales:[]},0);writeState(s,sameCompany,{products:[],customers:[{id:'c',name:'Privado outra unidade'}],sales:[]},0);});assert.equal(getCustomer(s,scope,'c').name,'Cliente');assert.equal(getCustomer(s,other,'c').name,'Privado outra empresa');assert.equal(getCustomer(s,sameCompany,'c').name,'Privado outra unidade');assert.equal(queryCustomers(s,scope,{q:'Privado'}).total,0);assert.throws(()=>getCustomer(s,{...scope,userId:'not-a-member'},'c'),e=>e.status===403);});
test('tenant/unidade composta impede linha de Cliente em combinação cruzada',t=>{const{s,scope}=fixture(t),c=createCompany(s,{name:'Outra'}),u=createUnit(s,c.id,{name:'Outra'});assert.throws(()=>s.db.prepare("INSERT INTO commercial_customers(company_id,unit_id,id,ordinal,name,present_fields,extra_json,search_text,sort_name) VALUES(?,?,'cross',1,'Cross','[]','{}','','')").run(scope.companyId,u.id),/FOREIGN KEY/);});
test('paginação Clientes lê SQL sem payload e oferece filtros limites e busca segura',t=>{const{s,scope}=fixture(t,[{id:'b',name:'José',phone:'123'},{id:'a',name:'José',email:'e@example.test',document:'DOC'},{id:'c',name:'Terceiro',active:false}]);s.db.prepare("UPDATE unit_states SET payload='{}'").run();const page=queryCustomers(s,scope,{q:'jose',page:2,pageSize:1});assert.equal(page.total,2);assert.equal(page.items[0].id,'b');assert.equal(queryCustomers(s,scope,{q:'DOC'}).items[0].id,'a');assert.equal(queryCustomers(s,scope,{status:'inactive'}).total,1);assert.equal(queryCustomers(s,scope,{status:'active'}).total,2);assert.equal(queryCustomers(s,scope,{q:'%'}).total,0);assert.throws(()=>queryCustomers(s,scope,{sort:'DROP TABLE users'}),e=>e.status===422);assert.throws(()=>queryCustomers(s,scope,{pageSize:101}),e=>e.status===422);assert.throws(()=>getCustomer(s,scope,'missing'),e=>e.status===404);});
test('Clientes novos sem unit_states têm consulta vazia sem criar marcador',t=>{const{s,scope}=fixture(t),u=createUnit(s,scope.companyId,{name:'Nova'}),other={companyId:scope.companyId,unitId:u.id};assert.equal(queryCustomers(s,other).total,0);assert.throws(()=>getCustomer(s,other,'c'),e=>e.status===404);assert.equal(s.db.prepare("SELECT count(*) n FROM commercial_normalizations WHERE aggregate='customers'").get().n,1);});
test('tamper no Cliente SQL bloqueia snapshot/normalização sem reparar autoridade',t=>{const{s,scope}=fixture(t);s.db.prepare("UPDATE commercial_customers SET name='corrupt'").run();assert.throws(()=>loadState(s,scope),e=>e.code==='COMMERCIAL_DIVERGENCE');assert.throws(()=>normalizeAllCommercial(s),e=>e.code==='COMMERCIAL_DIVERGENCE');assert.equal(s.db.prepare('SELECT name FROM commercial_customers').get().name,'corrupt');});
test('tamper no espelho Cliente ou revisão é rejeitado sem substituir SQL',t=>{const{s,scope,state}=fixture(t),next=structuredClone(state);next.customers[0].name='forjado';s.db.prepare('UPDATE unit_states SET payload=?').run(JSON.stringify(next));assert.throws(()=>loadState(s,scope),e=>e.code==='COMMERCIAL_DIVERGENCE');assert.equal(getCustomer(s,scope,'c').name,'Cliente');s.db.exec("UPDATE commercial_normalizations SET source_revision=99 WHERE aggregate='customers'");assert.throws(()=>queryCustomers(s,scope),e=>e.code==='COMMERCIAL_DIVERGENCE');});
test('erro depois da escrita de Clientes desfaz Produtos Clientes e snapshot',t=>{const{s,scope,state}=fixture(t),next=structuredClone(state);next.products.push({id:'p',name:'Novo produto',stock:0,priceCents:1});next.customers[0].name='Alterado';s.db.exec("CREATE TRIGGER fail_snapshot_customer BEFORE UPDATE ON unit_states BEGIN SELECT RAISE(ABORT,'customer rollback'); END;");assert.throws(()=>s.transaction(()=>writeState(s,scope,next,1)),/customer rollback/);assert.deepEqual(hydrateCustomers(s,scope),state.customers);assert.equal(s.db.prepare('SELECT count(*) n FROM commercial_products').get().n,0);assert.deepEqual(loadState(s,scope).state,state);});
test('migração Clientes é idempotente sem mudar revisão ou duplicar histórico',t=>{const{s,scope,state}=fixture(t);s.db.exec("DELETE FROM commercial_normalizations WHERE aggregate='customers';DELETE FROM commercial_customers;");assert.equal(normalizeAllCommercial(s),1);assert.equal(normalizeAllCommercial(s),0);assert.deepEqual(loadState(s,scope).state,state);assert.equal(loadState(s,scope).revision,1);assert.equal(verifyCommercial(s).units[0].customers.equivalent,true);});
test('editar Cliente não reescreve nome ou histórico financeiro da Venda',t=>{const{s,scope,state}=fixture(t),next=structuredClone(state);next.sales.push({id:'sale',customerId:'c',customerName:'Nome no momento',items:[],totalCents:0});s.transaction(()=>writeState(s,scope,next,1));const changed=structuredClone(next);changed.customers[0].name='Nome atual';s.transaction(()=>writeState(s,scope,changed,2));assert.equal(loadState(s,scope).state.sales[0].customerName,'Nome no momento');assert.equal(loadState(s,scope).state.sales[0].customerId,'c');assert.equal(getCustomer(s,scope,'c').name,'Nome atual');});
