'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {SqlStore}=require('./sql-store'),{createCompany,createUnit}=require('./entities');
const {writeState,canonical}=require('./state-repository'),{loadState}=require('./scoped-state');
const {normalizeAllProducts,normalizeProducts,hydrateProducts,verifyCommercial,queryProducts,lookupProduct}=require('./commercial-store');
const {decimal,add,compare,legacyInteger}=require('./decimal');
function fixture(t,state){const s=new SqlStore(':memory:',{environment:'test'}),c=createCompany(s,{name:'Empresa sintética'}),u=createUnit(s,c.id,{name:'Unidade sintética'}),scope={companyId:c.id,unitId:u.id};t.after(()=>s.close());const value=state||{products:[{id:'p',name:'Mouse',stock:10,priceCents:4990}],customers:[],sales:[]};s.transaction(()=>writeState(s,scope,value,0));return{s,scope,state:value};}
test('decimal exato aceita frações textuais e inteiros seguros sem truncamento',()=>{assert.equal(decimal('000.5000'),'0.5');assert.equal(decimal('-0.000'),'0');assert.equal(add('9007199254740991','0.5'),'9007199254740991.5');assert.equal(add('-0.5','0.2'),'-0.3');assert.equal(compare('0.50','0.500'),0);assert.equal(compare('-2.1','-2.09'),-1);assert.equal(legacyInteger('9007199254740991'),Number.MAX_SAFE_INTEGER);assert.throws(()=>legacyInteger('0.5'),/fracionada/);assert.throws(()=>decimal(0.5),/decimais usam texto/);assert.throws(()=>decimal('1e6'));assert.throws(()=>legacyInteger('9007199254740992'));});
test('produto usa colunas relacionais e preserva desconhecidos, ausência e null',t=>{const state={products:[{id:'p',name:'Mouse',stock:Number.MAX_SAFE_INTEGER,priceCents:4990,code:'SKU1',sku:'SKUANTIGO',barcode:'123',description:'Descrição',costCents:1300,unitCostCents:1400,unit:'kg',measureUnit:null,active:false,date:null,custom:{preserve:true},notes:'Histórico'}, {id:'q',name:'Outro',stock:0,priceCents:1}],customers:[],sales:[]};const{s,scope}=fixture(t,state),row=s.db.prepare('SELECT * FROM commercial_products WHERE id=?').get('p');assert.equal(row.price_cents,4990);assert.equal(row.cost_cents,1300);assert.equal(row.unit_cost_cents,1400);assert.equal(row.stock_quantity,'9007199254740991');assert.equal(row.unit,'kg');assert.equal(row.sku,'SKUANTIGO');assert.deepEqual(JSON.parse(row.extra_json),{custom:{preserve:true},notes:'Histórico'});assert.deepEqual(loadState(s,scope).state,state);assert.equal(Object.hasOwn(hydrateProducts(s,scope)[1],'unit'),false);assert.equal(Object.hasOwn(hydrateProducts(s,scope)[1],'version'),false);assert.equal(verifyCommercial(s).units[0].equivalent,true);});
test('chaves extras especiais e opcionais de tipo histórico não se perdem',t=>{const p=JSON.parse('{"id":"p","name":"Produto","stock":0,"priceCents":1,"description":{"old":"opaque"},"costCents":"not-guessed","__proto__":{"preserve":true},"constructor":{"old":1},"unit":null,"aliases":[],"packages":[]}');const{s,scope,state}=fixture(t,{products:[p],customers:[],sales:[]});assert.deepEqual(loadState(s,scope).state,state);assert.equal(Object.hasOwn(hydrateProducts(s,scope)[0],'__proto__'),true);assert.deepEqual(hydrateProducts(s,scope)[0].__proto__,{preserve:true});assert.equal(hydrateProducts(s,scope)[0].unit,null);assert.deepEqual(hydrateProducts(s,scope)[0].aliases,[]);});
test('aliases e embalagens têm tabelas próprias com ordem, IDs e história intacta',t=>{const p={id:'p',name:'Mouse',stock:2,priceCents:100,aliases:[{id:'a2',name:'Segundo',code:'ALT2',active:true,version:1,history:[],custom:'a'},{id:'a1',name:'Primeiro',code:'ALT1',active:false,version:1,history:[]}],packages:[{id:'pack',name:'Caixa',code:'PACK',active:true,version:1,factor:3,unit:'unidade',history:[{date:'2023',action:'create',responsible:'Declarado'}]}]};const{s,scope,state}=fixture(t,{products:[p],customers:[],sales:[]});assert.equal(s.db.prepare('SELECT count(*) n FROM commercial_product_aliases').get().n,2);assert.equal(s.db.prepare('SELECT factor_quantity FROM commercial_product_packages').get().factor_quantity,'3');assert.deepEqual(hydrateProducts(s,scope),state.products);assert.equal(lookupProduct(s,scope,'alt2').product.id,'p');assert.equal(lookupProduct(s,scope,'pack').packageUnits,3);assert.throws(()=>lookupProduct(s,scope,'alt1'),e=>e.status===404);});
test('ordem dos produtos pode mudar sem perda e sem recriar pai referenciado',t=>{const{s,scope,state}=fixture(t,{products:[{id:'p',name:'P',stock:1,priceCents:10},{id:'q',name:'Q',stock:2,priceCents:20}],customers:[],sales:[]});s.db.exec('CREATE TABLE future_reference(company_id TEXT,unit_id TEXT,product_id TEXT,FOREIGN KEY(company_id,unit_id,product_id) REFERENCES commercial_products(company_id,unit_id,id)) STRICT;');s.db.prepare('INSERT INTO future_reference VALUES(?,?,?)').run(scope.companyId,scope.unitId,'p');const next=structuredClone(state);next.products.reverse();next.products[1].stock=5;s.transaction(()=>writeState(s,scope,next,1));assert.deepEqual(hydrateProducts(s,scope),next.products);assert.equal(s.db.prepare('SELECT count(*) n FROM future_reference').get().n,1);});
test('SQL e snapshot atualizam juntos, falha de gravação desfaz ambos',t=>{const{s,scope,state}=fixture(t),next=structuredClone(state);next.products[0].stock=11;next.products[0].name='Alterado';s.db.exec("CREATE TRIGGER fail_snapshot BEFORE UPDATE ON unit_states BEGIN SELECT RAISE(ABORT,'injected snapshot'); END;");assert.throws(()=>s.transaction(()=>writeState(s,scope,next,1)),/injected snapshot/);assert.deepEqual(hydrateProducts(s,scope),state.products);assert.deepEqual(loadState(s,scope).state,state);assert.equal(loadState(s,scope).revision,1);});
test('tamper no SQL não é reparado pelo espelho nem aceita novo comando',t=>{const{s,scope,state}=fixture(t);s.db.prepare("UPDATE commercial_products SET name='tampered' WHERE id='p'").run();assert.throws(()=>loadState(s,scope),e=>e.code==='COMMERCIAL_DIVERGENCE');assert.throws(()=>s.transaction(()=>writeState(s,scope,state,1)),e=>e.code==='COMMERCIAL_DIVERGENCE');assert.equal(s.db.prepare('SELECT name FROM commercial_products').get().name,'tampered');});
test('tamper no espelho não substitui o SQL normalizado',t=>{const{s,scope,state}=fixture(t),next=structuredClone(state);next.products[0].stock=999;s.db.prepare('UPDATE unit_states SET payload=?').run(JSON.stringify(next));assert.throws(()=>normalizeAllProducts(s),e=>e.code==='COMMERCIAL_DIVERGENCE');assert.equal(hydrateProducts(s,scope)[0].stock,10);});
test('normalizar estado antigo é equivalente e idempotente por unidade',t=>{const{s,scope,state}=fixture(t);s.db.exec('DELETE FROM commercial_normalizations; DELETE FROM commercial_position_movements; DELETE FROM commercial_stock_movements; DELETE FROM commercial_stock_entries; DELETE FROM commercial_position_balances; DELETE FROM commercial_stock_balances; DELETE FROM commercial_product_aliases; DELETE FROM commercial_product_packages; DELETE FROM commercial_products;');assert.equal(normalizeAllProducts(s),1);assert.equal(normalizeAllProducts(s),0);assert.deepEqual(loadState(s,scope).state,state);assert.equal(loadState(s,scope).revision,1);assert.equal(s.db.prepare('SELECT source_revision FROM commercial_normalizations').get().source_revision,1);});
test('migração aditiva falha de maneira atômica e exige transação',t=>{const{s,scope,state}=fixture(t);s.db.exec('DELETE FROM commercial_normalizations; DELETE FROM commercial_position_movements; DELETE FROM commercial_stock_movements; DELETE FROM commercial_stock_entries; DELETE FROM commercial_position_balances; DELETE FROM commercial_stock_balances;DELETE FROM commercial_products;');assert.throws(()=>normalizeProducts(s,scope,state,1),/transação/);s.db.exec("CREATE TRIGGER fail_normalize BEFORE INSERT ON commercial_normalizations BEGIN SELECT RAISE(ABORT,'injected migration'); END;");assert.throws(()=>normalizeAllProducts(s),/injected migration/);assert.equal(s.db.prepare('SELECT count(*) n FROM commercial_products').get().n,0);assert.deepEqual(loadState(s,scope).state,state);});
test('normalização de cadastros não altera vínculos e snapshots de vendas',t=>{const state={products:[{id:'p',name:'Nome atual',stock:2,priceCents:200}],customers:[{id:'c',name:'Cliente',notes:'Original'}],sales:[{id:'s',customerId:'c',customerName:'Nome histórico',items:[{productId:'p',name:'Snapshot produto',quantity:1,priceCents:101}],totalCents:101}]};const{s,scope}=fixture(t,state);assert.deepEqual(loadState(s,scope).state,state);assert.equal(s.db.prepare("SELECT count(*) n FROM commercial_customers").get().n,1);});
test('FK composta impede aliases apontando produto de outra empresa/unidade',t=>{const{s,scope}=fixture(t),c=createCompany(s,{name:'Outra empresa'}),u=createUnit(s,c.id,{name:'Outra unidade'});assert.throws(()=>s.db.prepare("INSERT INTO commercial_product_aliases(company_id,unit_id,product_id,id,ordinal,present_fields,extra_json) VALUES(?,?,?,'evil',0,'[]','{}')").run(c.id,u.id,'p'),/FOREIGN KEY/);assert.throws(()=>s.db.prepare("INSERT INTO commercial_product_aliases(company_id,unit_id,product_id,id,ordinal,present_fields,extra_json) VALUES(?,?,?,'evil',0,'[]','{}')").run(scope.companyId,u.id,'p'),/FOREIGN KEY/);});
test('mesmo ID pode existir em duas empresas sem cruzar consulta ou escrita',t=>{const{s,scope}=fixture(t),c=createCompany(s,{name:'Outra empresa'}),u=createUnit(s,c.id,{name:'Outra unidade'}),other={companyId:c.id,unitId:u.id};s.transaction(()=>writeState(s,other,{products:[{id:'p',name:'Privado',stock:42,priceCents:900,code:'OTHER'}],customers:[],sales:[]},0));assert.equal(queryProducts(s,scope).items[0].name,'Mouse');assert.equal(queryProducts(s,other).items[0].name,'Privado');assert.throws(()=>lookupProduct(s,scope,'OTHER'),e=>e.status===404);assert.equal(lookupProduct(s,other,'OTHER').product.id,'p');});
test('unidade nova tem catálogo vazio sem escrita GET e marker faltante em estado existente bloqueia',t=>{
 const{s,scope}=fixture(t),u=createUnit(s,scope.companyId,{name:'Nova'}),other={companyId:scope.companyId,unitId:u.id};
 // Compare persisted content, not the number of aggregates present in a release.
 // total_changes also detects writes that leave the same values behind.
 const persisted=()=>({
  markers:s.db.prepare('SELECT * FROM commercial_normalizations ORDER BY company_id,unit_id,aggregate').all(),
  states:s.db.prepare('SELECT * FROM unit_states ORDER BY company_id,unit_id').all(),
  changes:s.db.prepare('SELECT total_changes() n').get().n
 });
 const before=persisted();
 assert.ok(before.markers.some(row=>row.company_id===scope.companyId&&row.unit_id===scope.unitId&&row.aggregate==='products'));
 assert.equal(before.markers.some(row=>row.company_id===other.companyId&&row.unit_id===other.unitId),false);
 assert.equal(before.states.some(row=>row.company_id===other.companyId&&row.unit_id===other.unitId),false);
 assert.deepEqual(queryProducts(s,other),{items:[],page:1,pageSize:50,total:0,totalPages:0,revision:0});
 assert.deepEqual(persisted(),before);
 assert.throws(()=>lookupProduct(s,other,'any'),e=>e.status===404);
 assert.deepEqual(persisted(),before);

 // Remove only the catalog marker; unrelated normalized aggregates must survive.
 s.db.prepare("DELETE FROM commercial_normalizations WHERE company_id=? AND unit_id=? AND aggregate='products'").run(scope.companyId,scope.unitId);
 const withoutMarker=persisted();
 assert.throws(()=>queryProducts(s,scope),e=>e.status===503&&e.code==='NORMALIZATION_REQUIRED');
 assert.deepEqual(persisted(),withoutMarker);
});
test('consulta rejeita revisão SQL diferente da revisão do espelho por metadados',t=>{const{s,scope}=fixture(t);s.db.exec('UPDATE commercial_normalizations SET source_revision=99');assert.throws(()=>queryProducts(s,scope),e=>e.code==='COMMERCIAL_DIVERGENCE');assert.throws(()=>lookupProduct(s,scope,'x'),e=>e.code==='COMMERCIAL_DIVERGENCE');});
test('página, filtros e ordenação estável são SQL, sem ler snapshot',t=>{const{s,scope}=fixture(t,{products:[{id:'b',name:'Água',stock:2,priceCents:2,active:true,code:'B'},{id:'a',name:'Água',stock:1,priceCents:1,code:'A'},{id:'c',name:'Suco',stock:3,priceCents:3,active:false,code:'C'}],customers:[],sales:[]});s.db.prepare("UPDATE unit_states SET payload='{}'").run();let page=queryProducts(s,scope,{q:'agua',pageSize:1,page:2});assert.equal(page.total,2);assert.equal(page.totalPages,2);assert.equal(page.items[0].id,'b');assert.equal(queryProducts(s,scope,{status:'inactive'}).items[0].id,'c');assert.equal(queryProducts(s,scope,{status:'active'}).total,2);assert.equal(queryProducts(s,scope,{sort:'code',direction:'desc',pageSize:1}).items[0].id,'c');assert.equal(queryProducts(s,scope,{q:'%'}).total,0);assert.equal(queryProducts(s,scope,{q:"' OR 1=1 --"}).total,0);assert.throws(()=>queryProducts(s,scope,{sort:'name; DROP TABLE users'}),e=>e.status===422);assert.throws(()=>queryProducts(s,scope,{pageSize:101}),e=>e.status===422);});
test('busca por código rejeita ambiguidade histórica sem escolher produto arbitrário',t=>{const{s,scope}=fixture(t,{products:[{id:'p',name:'P',stock:1,priceCents:1,barcode:'123'},{id:'q',name:'Q',stock:1,priceCents:1,barcode:'123'}],customers:[],sales:[]});assert.throws(()=>lookupProduct(s,scope,'123'),e=>e.status===409);});
test('runtime prepara snapshots anteriores antes de disponibilizar identidade',t=>{const{s,scope,state}=fixture(t);s.db.exec('DELETE FROM commercial_normalizations; DELETE FROM commercial_position_movements; DELETE FROM commercial_stock_movements; DELETE FROM commercial_stock_entries; DELETE FROM commercial_position_balances; DELETE FROM commercial_stock_balances;DELETE FROM commercial_products;');const runtime=require('./runtime').createRuntime({store:s,environment:'test',filename:':memory:',importLegacy:false,pairingToken:'test-private-code'});assert.equal(verifyCommercial(s).units.length,1);assert.deepEqual(loadState(s,scope).state,state);runtime.close();});
test('ferramenta conferente é read-only e não migra um schema antigo',t=>{const dir=path.resolve(__dirname,'../.qa/foundation-v1-1');fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,'verify-'+require('node:crypto').randomUUID()+'.sqlite'),s=new SqlStore(file,{environment:'test'}),c=createCompany(s,{name:'Sintética'}),u=createUnit(s,c.id,{name:'Sintética'});s.transaction(()=>writeState(s,{companyId:c.id,unitId:u.id},{products:[{id:'p',name:'Teste',stock:0,priceCents:1}],customers:[],sales:[]},0));s.close();t.after(()=>{for(const suffix of ['','-wal','-shm'])if(fs.existsSync(file+suffix))fs.unlinkSync(file+suffix);});const bytes=fs.readFileSync(file),report=require('../scripts/verify-commercial').verifyFile(file);assert.equal(report.units[0].equivalent,true);assert.deepEqual(fs.readFileSync(file),bytes);});
