'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {SqlStore}=require('./sql-store'),{createCompany,createUnit}=require('./entities'),{grantCompanyAccess,grantUnitAccess}=require('./access');
const {loadState}=require('./scoped-state'),{writeState,executeStateCommand}=require('./state-repository');
const {queryInventory,queryStockMovements}=require('./inventory-store'),{verifyCommercial,normalizeAllCommercial}=require('./commercial-store');
const {sale,change}=require('../server');
function fixture(t,state={products:[{id:'p',name:'Produto',stock:10,priceCents:1000}],customers:[],sales:[],stockMovements:[{id:'old',productId:'p',productName:'Nome antigo',quantity:3,stockAfter:3,type:'initial',referenceId:'p',date:'2020',note:'Histórico',custom:{keep:true}}]}){
 const s=new SqlStore(':memory:',{environment:'test'}),c=createCompany(s,{name:'Empresa sintética'}),u=createUnit(s,c.id,{name:'Unidade sintética'}),scope={companyId:c.id,unitId:u.id};s.transaction(()=>writeState(s,scope,state,0));t.after(()=>s.close());s.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?)').run('actor','Pessoa verificada','actor-fixture','synthetic-hash','active','2020','2020');grantCompanyAccess(s,'actor',c.id);grantUnitAccess(s,'actor',c.id,u.id);return{s,scope,state,ctx:{...scope,userId:'actor',sessionId:'synthetic-session'}};
}
test('estoque SQL conserva histórico incompleto com âncora técnica, extras e sem inventar autor',t=>{const{s,scope,state}=fixture(t);assert.deepEqual(loadState(s,scope).state,state);const row=s.db.prepare('SELECT * FROM commercial_stock_balances').get();assert.equal(row.quantity,'10');assert.equal(row.technical_anchor,'7');assert.equal(s.db.prepare('SELECT execution_json FROM commercial_stock_movements').get().execution_json,null);assert.equal(verifyCommercial(s).units[0].inventory.technicalAnchors,1);assert.equal(normalizeAllCommercial(s),0);});
test('coleções de movimentos ausentes permanecem ausentes em hidratação e consulta',t=>{const state={products:[{id:'p',name:'Produto',stock:2,priceCents:100}],customers:[],sales:[]},{s,scope}=fixture(t,state);assert.deepEqual(loadState(s,scope).state,state);assert.equal(queryStockMovements(s,scope).total,0);});
test('distribuição histórica null permanece distinta de objeto vazio e propriedade ausente',t=>{const state={products:[{id:'null',name:'Sem distribuição declarada',stock:2,priceCents:100,positionBalances:null},{id:'empty',name:'Distribuição vazia',stock:2,priceCents:100,positionBalances:{}},{id:'absent',name:'Sem campo',stock:2,priceCents:100}],customers:[],sales:[]},{s,scope}=fixture(t,state);assert.deepEqual(loadState(s,scope).state,state);assert.deepEqual(s.db.prepare('SELECT positions_present FROM commercial_stock_balances ORDER BY product_id').all().map(r=>r.positions_present),[0,1,2]);});
test('comando operacional não altera saldo silenciosamente mesmo sem posições',t=>{const{s,ctx,scope}=fixture(t),before=loadState(s,scope);assert.throws(()=>executeStateCommand(s,ctx,state=>{state.products[0].stock++;return state;}),e=>e.code==='STOCK_HISTORY_REQUIRED');assert.deepEqual(loadState(s,scope),before);});
test('movimento antigo não aceita edição, remoção ou troca de identidade',t=>{const{s,ctx,scope}=fixture(t),before=loadState(s,scope);for(const edit of [state=>state.stockMovements[0].note='Mudado',state=>state.stockMovements=[],state=>state.stockMovements[0].id='new'])assert.throws(()=>executeStateCommand(s,ctx,state=>{edit(state);return state;}),e=>e.code==='STOCK_HISTORY_IMMUTABLE');assert.deepEqual(loadState(s,scope),before);});
test('movimento novo com delta correto ainda exige documento de origem',t=>{const{s,ctx}=fixture(t);assert.throws(()=>executeStateCommand(s,ctx,state=>{state.products[0].stock++;state.stockMovements.push({id:'fake',productId:'p',quantity:1,stockAfter:11,type:'purchase',referenceId:'missing',date:'2026'});return state;}),e=>e.code==='STOCK_ORIGIN_REQUIRED');});
test('guard recusa saldo intermediário incorreto antes de tornar movimento histórico',t=>{const{s,ctx}=fixture(t);assert.throws(()=>executeStateCommand(s,ctx,state=>{state.products[0].stock++;state.stockEntries=[{id:'entry',productId:'p',quantity:1,date:'2026'}];state.stockMovements.push({id:'new',productId:'p',quantity:1,stockAfter:999,type:'entry',referenceId:'entry',date:'2026'});return state;}),e=>e.code==='STOCK_HISTORY_BALANCE');});
test('guard recusa SKU diferente do documento e sinal de saída positivo',t=>{const{s,ctx}=fixture(t);for(const quantity of [-1,1])assert.throws(()=>executeStateCommand(s,ctx,state=>{state.products[0].stock+=quantity;state.stockEntries=[{id:'foreign-entry',productId:'other',quantity:1,date:'2026'}];state.stockMovements.push({id:'new',productId:'p',quantity,stockAfter:10+quantity,type:'entry',referenceId:'foreign-entry',date:'2026'});return state;}),e=>e.code==='STOCK_ORIGIN_REQUIRED');});
test('guard mantém prefixo do histórico: proíbe reordenação e inserção retroativa',t=>{const{s,ctx}=fixture(t);const sold=executeStateCommand(s,ctx,state=>sale(state,{requestId:'prefix-stock-sale',items:[{productId:'p',quantity:1}],paymentMethod:'pix',paymentStatus:'received'}));assert.equal(sold.state.stockMovements.length,2);assert.throws(()=>executeStateCommand(s,ctx,state=>{state.stockMovements.reverse();return state;}),e=>e.code==='STOCK_HISTORY_IMMUTABLE');});
test('movimento físico não reutiliza origem global antiga para mudar distribuição',t=>{const{s,ctx}=fixture(t);assert.throws(()=>executeStateCommand(s,ctx,state=>{state.positionMovements=[{id:'fake-physical',productId:'p',quantity:2,from:'dep',to:null,type:'initial',referenceId:'p',stockMovementId:'old',date:'2026'}];return state;}),e=>e.code==='STOCK_ORIGIN_REQUIRED');});
test('movimento físico não usa transferência inexistente ou sem o SKU/quantidade correspondente',t=>{const{s,ctx}=fixture(t);assert.throws(()=>executeStateCommand(s,ctx,state=>{state.positionMovements=[{id:'fake-transfer',productId:'p',quantity:2,from:'dep',to:'',type:'transfer',referenceId:'missing',date:'2026'}];return state;}),e=>e.code==='STOCK_ORIGIN_REQUIRED');});
test('venda e cancelamento preservam âncora, SQL, origem e executor verificado',t=>{const{s,ctx,scope}=fixture(t),input={requestId:'sale-stock-proof',items:[{productId:'p',quantity:2,priceCents:1000}],paymentMethod:'pix',paymentStatus:'received'},saved=executeStateCommand(s,ctx,state=>sale(state,input));assert.equal(saved.state.products[0].stock,8);assert.equal(s.db.prepare('SELECT technical_anchor FROM commercial_stock_balances').get().technical_anchor,'7');assert.equal(saved.state.stockMovements[1].execution.executedBy,'actor');const canceled=executeStateCommand(s,ctx,state=>change(state,'/api/sales/cancel',{id:saved.state.sales[0].id}));assert.equal(canceled.state.products[0].stock,10);assert.equal(queryStockMovements(s,scope).total,3);assert.equal(s.db.prepare('SELECT technical_anchor FROM commercial_stock_balances').get().technical_anchor,'7');});
test('falha SQL do saldo desfaz venda, recebimento, movimento, revisão e auditoria',t=>{const{s,ctx,scope}=fixture(t),before=loadState(s,scope),events=s.db.prepare('SELECT count(*) n FROM audit_events').get().n;s.db.exec("CREATE TRIGGER deny_balance BEFORE INSERT ON commercial_stock_balances BEGIN SELECT RAISE(ABORT,'balance rollback'); END;");assert.throws(()=>executeStateCommand(s,ctx,state=>sale(state,{requestId:'rollback-stock-sale',items:[{productId:'p',quantity:1}],paymentMethod:'pix',paymentStatus:'received'})),/balance rollback/);assert.deepEqual(loadState(s,scope),before);assert.equal(s.db.prepare('SELECT count(*) n FROM audit_events').get().n,events);});
test('saldo ou âncora SQL adulterados bloqueiam leitura e nunca são reimportados do espelho',t=>{const{s,scope}=fixture(t);s.db.exec("UPDATE commercial_stock_balances SET quantity='99'");assert.throws(()=>loadState(s,scope),e=>e.code==='COMMERCIAL_DIVERGENCE');assert.throws(()=>normalizeAllCommercial(s),e=>e.code==='COMMERCIAL_DIVERGENCE');s.db.exec("UPDATE commercial_stock_balances SET quantity='10',technical_anchor='8'");assert.throws(()=>loadState(s,scope),e=>e.code==='COMMERCIAL_DIVERGENCE');});
test('consulta de estoque pagina SQL sem carregar snapshot e filtra antes de paginar',t=>{const state={products:Array.from({length:121},(_,i)=>({id:String(i).padStart(3,'0'),name:i%2?'João':'Outro',stock:i,priceCents:100,code:'P'+i,active:i!==120})),customers:[],sales:[]},{s,scope}=fixture(t,state);s.db.exec("UPDATE unit_states SET payload='{}'");const page=queryInventory(s,scope,{q:'joao',page:2,pageSize:25});assert.equal(page.total,60);assert.equal(page.items.length,25);assert.equal(page.items[0].id,'051');assert.equal(queryInventory(s,scope,{status:'inactive'}).items[0].id,'120');assert.equal(queryInventory(s,scope,{q:'%'}).total,0);assert.throws(()=>queryInventory(s,scope,{pageSize:101}),e=>e.status===422);});
test('saldo e movimentos de IDs iguais não cruzam empresa/unidade, nem vínculo do usuário',t=>{const{s,scope}=fixture(t),c=createCompany(s,{name:'Outra'}),u=createUnit(s,c.id,{name:'Outra'}),other={companyId:c.id,unitId:u.id};s.transaction(()=>writeState(s,other,{products:[{id:'p',name:'Privado',stock:77,priceCents:100}],customers:[],sales:[]},0));assert.equal(queryInventory(s,scope).items[0].stock,10);assert.equal(queryInventory(s,other).items[0].stock,77);assert.throws(()=>queryInventory(s,{...other,userId:'actor'}),e=>e.status===403);assert.throws(()=>s.db.prepare('INSERT INTO commercial_stock_balances VALUES(?,?,?,?,?,?)').run(scope.companyId,u.id,'p','1','1',0),/FOREIGN KEY/);});
test('transferência física mantém saldo global e guard recusa mudança de distribuição sem movimento',t=>{const state={products:[{id:'p',name:'Produto',stock:10,priceCents:100,positionBalances:{dep:4}}],customers:[],sales:[],positions:[{id:'dep',code:'DEP',name:'Depósito',active:true,version:1,number:1,date:'2020',history:[]}],transfers:[]},{s,ctx,scope}=fixture(t,state),{positionAction}=require('../positions');let created=executeStateCommand(s,ctx,state=>positionAction(state,'transfers','create',{requestId:'create-transfer-stock',from:'dep',to:'',reason:'Mover mercadoria',items:[{productId:'p',quantity:2}]}));const transfer=created.state.transfers[0],token=require('../public/positions-core').positionToken(created.state.products[0]);const out=executeStateCommand(s,ctx,state=>positionAction(state,'transfers','confirm',{requestId:'confirm-transfer-stock',id:transfer.id,expectedVersion:transfer.version,expectedPositions:{p:token}}));assert.equal(out.state.products[0].stock,10);assert.equal(out.state.products[0].positionBalances.dep,2);assert.equal(out.state.stockMovements,undefined);assert.equal(out.state.positionMovements.length,1);assert.equal(s.db.prepare('SELECT quantity FROM commercial_position_balances').get().quantity,'2');const before=loadState(s,scope);assert.throws(()=>executeStateCommand(s,ctx,state=>{state.products[0].positionBalances.dep++;return state;}),e=>e.code==='POSITION_HISTORY_REQUIRED');assert.deepEqual(loadState(s,scope),before);});
