'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {SqlStore}=require('./sql-store'),{createCompany,createUnit}=require('./entities'),{loadState}=require('./scoped-state'),{writeState}=require('./state-repository');
const {hydrateSuppliers,querySuppliers,getSupplier,normalizeAllCommercial,verifyCommercial}=require('./commercial-store');
function fixture(t,suppliers){const s=new SqlStore(':memory:',{environment:'test'}),c=createCompany(s,{name:'Empresa sintética'}),u=createUnit(s,c.id,{name:'Unidade sintética'}),scope={companyId:c.id,unitId:u.id},state={products:[],customers:[],sales:[],...(suppliers===undefined?{}:{suppliers})};s.transaction(()=>writeState(s,scope,state,0));t.after(()=>s.close());return{s,scope,state};}
test('Fornecedores possuem colunas reais e preservam documento contatos história e extras',t=>{const value=JSON.parse('{"id":"s","name":"Fornecedor","phone":"000","email":"s@example.test","contactName":"Contato","address":"Fictício","commercialId":"0001","document":"00123","notes":"Histórico","active":true,"version":1,"date":"2020","updatedAt":null,"history":[{"declared":"old"}],"custom":{"productId":"reference"},"__proto__":{"preserve":true}}');const{s,scope,state}=fixture(t,[value]),row=s.db.prepare('SELECT * FROM commercial_suppliers').get();assert.equal(row.document,'00123');assert.equal(row.commercial_id,'0001');assert.equal(row.contact_name,'Contato');assert.deepEqual(hydrateSuppliers(s,scope),state.suppliers);assert.deepEqual(loadState(s,scope).state,state);assert.equal(Object.hasOwn(getSupplier(s,scope,'s'),'__proto__'),true);});
test('coleção Fornecedores ausente permanece ausente e difere de lista vazia',t=>{const{s,scope,state}=fixture(t);assert.deepEqual(loadState(s,scope).state,state);assert.equal(Object.hasOwn(loadState(s,scope).state,'suppliers'),false);assert.equal(verifyCommercial(s).units[0].suppliers.present,false);const next={...state,suppliers:[]};s.transaction(()=>writeState(s,scope,next,1));assert.deepEqual(loadState(s,scope).state,next);assert.equal(verifyCommercial(s).units[0].suppliers.present,true);s.transaction(()=>writeState(s,scope,state,2));assert.equal(Object.hasOwn(loadState(s,scope).state,'suppliers'),false);assert.equal(loadState(s,scope).revision,3);});
test('Fornecedor antigo sem situação versão ou documento mantém ausência/null/valor opaco',t=>{const{s,scope,state}=fixture(t,[{id:'s',name:'Antigo',phone:null,document:{old:'opaque'},notes:'Manter'}]);const row=getSupplier(s,scope,'s');assert.deepEqual(loadState(s,scope).state,state);assert.equal(Object.hasOwn(row,'active'),false);assert.equal(Object.hasOwn(row,'version'),false);assert.equal(row.phone,null);assert.deepEqual(row.document,{old:'opaque'});});
test('mesmo ID de Fornecedor entre empresas/unidades não cruza consulta',t=>{const{s,scope}=fixture(t,[{id:'s',name:'Meu fornecedor'}]),c=createCompany(s,{name:'Outra'}),u=createUnit(s,c.id,{name:'Outra'}),other={companyId:c.id,unitId:u.id},u2=createUnit(s,scope.companyId,{name:'Outra unidade'}),same={companyId:scope.companyId,unitId:u2.id};s.transaction(()=>{writeState(s,other,{products:[],customers:[],sales:[],suppliers:[{id:'s',name:'Privado outra empresa'}]},0);writeState(s,same,{products:[],customers:[],sales:[],suppliers:[{id:'s',name:'Privado outra unidade'}]},0);});assert.equal(getSupplier(s,scope,'s').name,'Meu fornecedor');assert.equal(getSupplier(s,other,'s').name,'Privado outra empresa');assert.equal(getSupplier(s,same,'s').name,'Privado outra unidade');assert.equal(querySuppliers(s,scope,{q:'Privado'}).total,0);assert.throws(()=>getSupplier(s,{...scope,userId:'foreign'},'s'),e=>e.status===403);});
test('FK tenant/unidade impede Fornecedor em combinação inválida',t=>{const{s,scope}=fixture(t),c=createCompany(s,{name:'Outra'}),u=createUnit(s,c.id,{name:'Outra'});assert.throws(()=>s.db.prepare("INSERT INTO commercial_suppliers(company_id,unit_id,id,ordinal,name,present_fields,extra_json,search_text,sort_name) VALUES(?,?,'evil',0,'Evil','[]','{}','','')").run(scope.companyId,u.id),/FOREIGN KEY/);});
test('consulta Fornecedores pagina SQL sem snapshot e limita filtros/ordenação',t=>{const{s,scope}=fixture(t,[{id:'b',name:'João',phone:'123'},{id:'a',name:'João',email:'a@example.test'},{id:'c',name:'Outro',active:false}]);s.db.prepare("UPDATE unit_states SET payload='{}'").run();const page=querySuppliers(s,scope,{q:'joao',page:2,pageSize:1});assert.equal(page.total,2);assert.equal(page.items[0].id,'b');assert.equal(querySuppliers(s,scope,{q:'123'}).items[0].id,'b');assert.equal(querySuppliers(s,scope,{status:'inactive'}).total,1);assert.equal(querySuppliers(s,scope,{status:'active'}).total,2);assert.equal(querySuppliers(s,scope,{q:'%'}).total,0);assert.throws(()=>querySuppliers(s,scope,{pageSize:101}),e=>e.status===422);assert.throws(()=>querySuppliers(s,scope,{sort:'DROP TABLE users'}),e=>e.status===422);});
test('ordem de Fornecedores conserva pai usado por FK futura',t=>{const{s,scope,state}=fixture(t,[{id:'s1',name:'Um'},{id:'s2',name:'Dois'}]);s.db.exec('CREATE TABLE future_supplier_ref(company_id TEXT,unit_id TEXT,supplier_id TEXT,FOREIGN KEY(company_id,unit_id,supplier_id) REFERENCES commercial_suppliers(company_id,unit_id,id)) STRICT;');s.db.prepare('INSERT INTO future_supplier_ref VALUES(?,?,?)').run(scope.companyId,scope.unitId,'s1');const next=structuredClone(state);next.suppliers.reverse();next.suppliers[1].name='Atualizado';s.transaction(()=>writeState(s,scope,next,1));assert.deepEqual(hydrateSuppliers(s,scope),next.suppliers);});
test('tamper SQL ou presença da coleção bloqueia sem reparar autoridade',t=>{const{s,scope,state}=fixture(t,[{id:'s',name:'Fornecedor'}]);s.db.prepare("UPDATE commercial_suppliers SET name='corrupt'").run();assert.throws(()=>loadState(s,scope),e=>e.code==='COMMERCIAL_DIVERGENCE');assert.throws(()=>normalizeAllCommercial(s),e=>e.code==='COMMERCIAL_DIVERGENCE');s.db.prepare('UPDATE commercial_suppliers SET name=?').run(state.suppliers[0].name);s.db.exec("UPDATE commercial_normalizations SET collection_present=0 WHERE aggregate='suppliers'");assert.throws(()=>loadState(s,scope),e=>e.code==='COMMERCIAL_DIVERGENCE');});
test('erro posterior à escrita Fornecedores desfaz todos cadastros e snapshot',t=>{const{s,scope,state}=fixture(t,[{id:'s',name:'Fornecedor'}]),next=structuredClone(state);next.suppliers[0].name='Alterado';next.customers.push({id:'c',name:'Cliente'});s.db.exec("CREATE TRIGGER fail_suppliers_snapshot BEFORE UPDATE ON unit_states BEGIN SELECT RAISE(ABORT,'suppliers rollback'); END;");assert.throws(()=>s.transaction(()=>writeState(s,scope,next,1)),/suppliers rollback/);assert.deepEqual(loadState(s,scope).state,state);assert.equal(s.db.prepare('SELECT count(*) n FROM commercial_customers').get().n,0);});
test('normalização Fornecedores é idempotente e conserva ausência original',t=>{const{s,scope,state}=fixture(t);s.db.exec("DELETE FROM commercial_normalizations WHERE aggregate='suppliers'");assert.equal(normalizeAllCommercial(s),1);assert.equal(normalizeAllCommercial(s),0);assert.deepEqual(loadState(s,scope).state,state);assert.equal(Object.hasOwn(loadState(s,scope).state,'suppliers'),false);});
test('editar Fornecedor não reescreve snapshots das compras nem cria novo vínculo',t=>{const{s,scope,state}=fixture(t,[{id:'s',name:'Atual'}]),next=structuredClone(state);next.products.push({id:'p',name:'Produto',stock:1,priceCents:100});next.purchases=[{id:'purchase',supplierId:'s',supplierName:'Nome histórico',version:1,items:[{productId:'p',name:'Produto histórico',quantity:1,unitCostCents:10}],totalCents:10,receipts:[]}];s.transaction(()=>writeState(s,scope,next,1));const changed=structuredClone(next);changed.suppliers[0].name='Novo nome';s.transaction(()=>writeState(s,scope,changed,2));assert.equal(loadState(s,scope).state.purchases[0].supplierName,'Nome histórico');assert.equal(loadState(s,scope).state.purchases[0].supplierId,'s');assert.equal(Object.hasOwn(getSupplier(s,scope,'s'),'principal'),false);});
