'use strict';
// Synthetic fixtures only; no operational database is opened.
const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const fs=require('node:fs'),path=require('node:path');
const {SqlStore}=require('./sql-store'),{createCompany,createUnit}=require('./entities'),{grantCompanyAccess,grantUnitAccess}=require('./access');
const {writeState,executeStateCommand,canonical}=require('./state-repository'),{loadState}=require('./scoped-state');
const {hydrateSales,normalizeSales,querySales,getSale}=require('./sales-store'),{normalizeAllCommercial,verifyCommercial}=require('./commercial-store');
const {sale,change}=require('../server');
function base(){return{products:[{id:'p',name:'Produto atual',stock:10,priceCents:101}],customers:[{id:'c',name:'Cliente atual'}],sales:[]};}
function historical(){const state=base();state.sales=[{id:'old',customerId:'c',customerName:'Cliente histórico',date:'2026-10-02T01:30:00Z',dueDate:null,receivedAt:null,totalCents:400,subtotalCents:404,discountCents:4,discountReason:'Desconto histórico',paymentStatus:'partial',paymentMethod:'cash',accountVersion:2,returnVersion:1,requestId:null,execution:{executedBy:null,authorizedBy:null,executorName:'Nome declarado',unknown:{preserve:true}},items:[{productId:'p',name:'Produto histórico',code:'OLD',quantity:4,priceCents:101,unitCostCents:53,unit:'un',measureUnit:null,priceOrigin:'history',promotion:{id:'promo-old',name:'Snapshot',extra:'preserve'},packages:[{packageId:'old-pack',name:'Caixa antiga',factor:2,count:2,version:1,unknown:true}],stockSources:[{positionId:'',name:'Origem antiga',quantity:4,extra:null}],substitutedFrom:{id:'old-substitute',name:'Nome antigo',code:'ORIG'},unknown:{nested:'retain'}}],receivablePlan:[{id:'a',number:1,amountCents:200,dueDate:null},{id:'b',number:2,amountCents:200,dueDate:'2026-11-01'}],receipts:[{id:'same-id',amountCents:100,paymentMethod:'cash',date:'2026-10-01T15:00:00Z',saleId:'old',cashSessionId:null,tenderedCents:120,changeCents:20,allocations:[{installmentId:'a',amountCents:100,extra:true}]},{id:'same-id',amountCents:50,paymentMethod:'pix',allocations:[{installmentId:'b',amountCents:50}]}],forgivenCents:20,forgiveness:[{date:'2026-10-01T16:00:00Z',amountCents:20,reason:'Declarado',responsible:'Nome declarado',allocations:[{installmentId:'b',amountCents:20}]}],returns:[{date:'2026-10-01T17:00:00Z',totalCents:100,reason:'Histórico',items:[{productId:'p',name:'Produto histórico',quantity:1,restockQuantity:0,restock:false,quarantineQuantity:0,amountCents:100,note:null,extra:'preserve'}]}],refunds:[{id:'refund',amountCents:10,paymentMethod:'pix',date:'2026-10-01T18:00:00Z',paidDate:'2026-10-01',recordedAt:'2026-10-01T18:30:00Z',cashSessionId:null,returnRefund:true,note:'Histórico'}],returnAllocation:[{productId:'p',quantity:4,unitNetCents:101,discountedUnits:4}],storeCreditCents:0,storeCreditRestoredCents:0,storeCreditIssuedCents:0,storeCreditAllocations:[],checkout:{totalCents:400,internalCents:0,receivedCents:150,remainingCents:250,cashCents:100,tenderedCents:120,changeCents:20,status:'partial',recordedAt:'2026-10-01T15:00:00Z',receiptIds:['same-id','same-id'],unknown:'preserve'},pos:{station:'Estação histórica',shift:'Turno histórico',extra:'preserve'},negotiation:{items:[{productId:'p',quantity:4,priceCents:101}],signature:'opaque-historical'},planHistory:[{date:'2026',plan:[]}],custom:JSON.parse('{"__proto__":{"preserve":true},"constructor":"historical"}')}];return state;}
function fixture(t,state=base(),filename=':memory:'){
 const store=new SqlStore(filename,{environment:'test'}),company=createCompany(store,{name:'Empresa sintética'}),unit=createUnit(store,company.id,{name:'Unidade sintética'}),scope={companyId:company.id,unitId:unit.id};t.after(()=>store.close());
 store.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?)').run('actor','Pessoa verificada','sales-fixture-user','synthetic-hash','active','2026','2026');grantCompanyAccess(store,'actor',scope.companyId);grantUnitAccess(store,'actor',scope.companyId,scope.unitId);
 store.transaction(()=>writeState(store,scope,state,0));return{store,scope,state,ctx:{...scope,userId:'actor',sessionId:'synthetic-session'}};
}
function commandInput(extra={}){return{requestId:randomUUID(),customerId:'c',paymentMethod:'pix',paymentStatus:'received',items:[{productId:'p',quantity:1,priceCents:101}],...extra};}

test('Vendas SQL preserva cabeçalho e todos filhos factuais com centavos, ordem e extras',t=>{
 const {store,scope,state}=fixture(t,historical());assert.deepEqual(hydrateSales(store,scope),state.sales);assert.deepEqual(getSale(store,scope,'old'),state.sales[0]);assert.deepEqual(loadState(store,scope).state,state);
 assert.equal(store.db.prepare('SELECT quantity,price_cents,unit_cost_cents FROM commercial_sale_items').get().quantity,'4');assert.equal(store.db.prepare('SELECT count(*) n FROM commercial_sale_receipts').get().n,2);assert.equal(store.db.prepare('SELECT factor_quantity FROM commercial_sale_item_packages').get().factor_quantity,'2');assert.equal(store.db.prepare('SELECT executed_by FROM commercial_sales').get().executed_by,null);
 const checked=verifyCommercial(store).units[0].sales;assert.equal(checked.count,1);assert.equal(checked.items,1);assert.equal(checked.receipts,2);assert.equal(checked.totalCents,'400');assert.equal(checked.centsByPath['sales[].items[].priceCents'],'101');assert.equal(checked.quantitiesByPath['sales[].items[].quantity'],'4');assert.equal(store.db.prepare('PRAGMA foreign_key_check').all().length,0);
});
test('Vendas antigas sem nome, data, unidade, versão ou recibos não ganham fatos inventados',t=>{
 const state=base();state.sales=[{id:'minimal',items:[{productId:'p',quantity:1,priceCents:0}],totalCents:0,paymentStatus:'received'},{id:'empty',items:[],totalCents:0}];const{store,scope}=fixture(t,state);
 assert.deepEqual(hydrateSales(store,scope),state.sales);assert.equal(store.db.prepare('SELECT count(*) n FROM commercial_sale_receipts').get().n,0);assert.equal(Object.hasOwn(getSale(store,scope,'minimal'),'receipts'),false);assert.equal(Object.hasOwn(getSale(store,scope,'empty'),'customerName'),false);assert.equal(Object.hasOwn(getSale(store,scope,'empty'),'execution'),false);
});
test('Vendas conserva ausência, null, listas vazias e valores opcionais antigos incompatíveis',t=>{
 const state=base();state.sales=[{id:'nulls',customerId:'',customerName:{historical:true},date:null,receivedAt:null,items:[{productId:'p',quantity:1,priceCents:0,unit:null,packages:[],stockSources:null}],totalCents:0,receipts:null,receivablePlan:null,returns:[],refunds:[],checkout:null,pos:null,execution:null,activeAgreementId:{opaque:true},unknown:null}];const{store,scope}=fixture(t,state);assert.deepEqual(getSale(store,scope,'nulls'),state.sales[0]);assert.equal(store.db.prepare('SELECT customer_id FROM commercial_sales').get().customer_id,null);assert.deepEqual(loadState(store,scope).state,state);
});
test('IDs ausentes ou repetidos nos filhos são ordinais técnicos e nunca UUID históricos novos',t=>{
 const state=historical(),{store,scope}=fixture(t,state),reloaded=getSale(store,scope,'old');assert.equal(Object.hasOwn(reloaded.items[0],'id'),false);assert.equal(Object.hasOwn(reloaded.returns[0],'id'),false);assert.deepEqual(reloaded.receipts.map(r=>r.id),['same-id','same-id']);assert.deepEqual(store.db.prepare('SELECT ordinal,id FROM commercial_sale_receipts ORDER BY ordinal').all().map(r=>({...r})),[{ordinal:0,id:'same-id'},{ordinal:1,id:'same-id'}]);
});
test('Centavos seguros e quantidades TEXT sobrevivem ao limite sem habilitar venda fracionada',t=>{
 const state=base();state.sales=[{id:'limit',items:[{productId:'p',quantity:Number.MAX_SAFE_INTEGER,priceCents:1}],totalCents:Number.MAX_SAFE_INTEGER,receipts:[]}];const{store,scope}=fixture(t,state);assert.equal(store.db.prepare('SELECT quantity FROM commercial_sale_items').get().quantity,String(Number.MAX_SAFE_INTEGER));assert.deepEqual(getSale(store,scope,'limit'),state.sales[0]);assert.throws(()=>sale(base(),commandInput({items:[{productId:'p',quantity:0.5}]})),/Quantidade/);store.db.exec("UPDATE commercial_sale_items SET quantity='0.5'");assert.throws(()=>loadState(store,scope),e=>e.code==='COMMERCIAL_DIVERGENCE');
});
test('Cliente e produto atuais não reescrevem snapshots históricos da venda',t=>{
 const{store,scope}=fixture(t,historical()),current=loadState(store,scope),next=structuredClone(current.state);next.products[0].name='Produto atualizado';next.products[0].priceCents=999;next.customers[0].name='Cliente atualizado';store.transaction(()=>writeState(store,scope,next,current.revision));assert.equal(getSale(store,scope,'old').items[0].name,'Produto histórico');assert.equal(getSale(store,scope,'old').items[0].priceCents,101);assert.equal(getSale(store,scope,'old').customerName,'Cliente histórico');
});
test('Sync em lote não apaga filhos de venda inalterada e UPSERT preserva pai referenciado',t=>{
 const{store,scope}=fixture(t,historical()),before=loadState(store,scope);store.db.exec("CREATE TRIGGER keep_old_sale_item BEFORE DELETE ON commercial_sale_items WHEN OLD.sale_id='old' BEGIN SELECT RAISE(ABORT,'unchanged child was rewritten'); END;");store.db.exec('CREATE TABLE future_sale_reference(company_id TEXT,unit_id TEXT,sale_id TEXT,FOREIGN KEY(company_id,unit_id,sale_id) REFERENCES commercial_sales(company_id,unit_id,id)) STRICT;');store.db.prepare('INSERT INTO future_sale_reference VALUES(?,?,?)').run(scope.companyId,scope.unitId,'old');
 const next=structuredClone(before.state);next.sales.push({id:'new',items:[{productId:'p',quantity:1,priceCents:101}],totalCents:101});store.transaction(()=>writeState(store,scope,next,before.revision));assert.equal(store.db.prepare('SELECT count(*) n FROM future_sale_reference').get().n,1);const now=loadState(store,scope);now.state.sales.reverse();store.transaction(()=>writeState(store,scope,now.state,now.revision));assert.deepEqual(hydrateSales(store,scope).map(s=>s.id),['new','old']);assert.equal(getSale(store,scope,'old').receipts.length,2);
});
test('Normalização sales é idempotente e não altera revisão quando converte representação',t=>{
 const{store,scope,state}=fixture(t,historical()),before=loadState(store,scope);store.transaction(()=>{store.db.exec("DELETE FROM commercial_normalizations WHERE aggregate='sales'");for(const row of store.db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND (name='commercial_sales' OR name LIKE 'commercial_sale_%')").all())store.db.exec('DELETE FROM '+row.name);});assert.equal(normalizeAllCommercial(store),1);assert.equal(normalizeAllCommercial(store),0);assert.equal(loadState(store,scope).revision,before.revision);assert.deepEqual(loadState(store,scope).state,state);assert.throws(()=>normalizeSales(store,scope,state,before.revision),/transa/i);
});
test('SQL/espelho/hash/revisão divergentes bloqueiam sem reparar autoridade SQL',t=>{
 const{store,scope}=fixture(t,historical());store.db.exec('UPDATE commercial_sale_items SET price_cents=102');assert.throws(()=>loadState(store,scope),e=>e.code==='COMMERCIAL_DIVERGENCE');assert.throws(()=>normalizeAllCommercial(store),e=>e.code==='COMMERCIAL_DIVERGENCE');assert.equal(store.db.prepare('SELECT price_cents FROM commercial_sale_items').get().price_cents,102);store.db.exec('UPDATE commercial_sale_items SET price_cents=101');
 const old=store.db.prepare('SELECT payload FROM unit_states').get().payload,next=JSON.parse(old);next.sales[0].customerName='Espelho adulterado';store.db.prepare('UPDATE unit_states SET payload=?').run(JSON.stringify(next));assert.throws(()=>loadState(store,scope),e=>e.code==='COMMERCIAL_DIVERGENCE');store.db.prepare('UPDATE unit_states SET payload=?').run(old);store.db.exec("UPDATE commercial_normalizations SET source_revision=99 WHERE aggregate='sales'");assert.throws(()=>querySales(store,scope),e=>e.code==='COMMERCIAL_DIVERGENCE');
});
test('Queries de Vendas leem SQL com filtro/count/página e somente itens da página',t=>{
 const state=base();state.sales=Array.from({length:121},(_,i)=>({id:'s'+String(i).padStart(3,'0'),customerId:'c',customerName:i%2?'João histórico':'Outro',date:'2026-10-02T15:00:00Z',items:[{productId:'p',quantity:1,priceCents:101}],totalCents:101,receipts:[],...(i===120?{cancelledAt:'2026-10-02T16:00:00Z'}:{})}));const{store,scope}=fixture(t,state);store.db.exec("UPDATE unit_states SET payload='{}'");
 const original=store.db.prepare.bind(store.db),seen=[];store.db.prepare=sql=>{seen.push(sql);return original(sql);};const page=querySales(store,scope,{q:'joao',page:2,pageSize:25});store.db.prepare=original;assert.equal(page.total,60);assert.equal(page.items.length,25);assert.equal(page.items[0].id,'s051');assert.equal(page.items[0].receipts,undefined);assert.ok(seen.some(sql=>sql.includes('commercial_sale_items')&&sql.includes('IN (')));assert.equal(seen.some(sql=>sql.includes('commercial_sale_receipts')),false);assert.equal(seen.some(sql=>sql.includes('payload')),false);assert.equal(querySales(store,scope,{cancelled:'cancelled'}).items[0].id,'s120');assert.equal(querySales(store,scope,{q:'%'}).total,0);
});
test('Período deriva dia São Paulo sem cortar UTC; cliente/executor/unidade são validados',t=>{
 const state=base();state.sales=[{id:'before-midnight',customerId:'c',customerName:'Z',date:'2026-10-02T01:30:00Z',items:[],totalCents:0,execution:{executedBy:'actor',executorName:'Snapshot',executedAt:'2026-10-02T01:30:00Z'}},{id:'after-midnight',date:'2026-10-02T03:30:00Z',items:[],totalCents:0},{id:'undated',date:'historical-opaque',items:[],totalCents:0}];const{store,scope}=fixture(t,state);assert.deepEqual(querySales(store,scope,{from:'2026-10-01',to:'2026-10-01'}).items.map(s=>s.id),['before-midnight']);assert.deepEqual(querySales(store,scope,{from:'2026-10-02',to:'2026-10-02'}).items.map(s=>s.id),['after-midnight']);assert.equal(querySales(store,scope,{customerId:'c',executorId:'actor',unitId:scope.unitId}).total,1);assert.throws(()=>querySales(store,scope,{unitId:'other-unit'}),e=>e.status===403);for(const options of [{from:'2026-02-30'},{from:'2026-10-02',to:'2026-10-01'},{pageSize:101},{sort:'totalCents'},{cancelled:'injected'}])assert.throws(()=>querySales(store,scope,options),e=>e.status===422);
});
test('Mesmo ID entre empresas/unidades não cruza detalhe, páginas ou FKs',t=>{
 const{store,scope}=fixture(t,historical()),otherCompany=createCompany(store,{name:'Outra sintética'}),otherUnit=createUnit(store,otherCompany.id,{name:'Outra sintética'}),sibling=createUnit(store,scope.companyId,{name:'Irmã sintética'}),other={companyId:otherCompany.id,unitId:otherUnit.id},sister={companyId:scope.companyId,unitId:sibling.id};const a=historical(),b=historical();a.sales[0].customerName='Outra empresa';b.sales[0].customerName='Outra unidade';store.transaction(()=>{writeState(store,other,a,0);writeState(store,sister,b,0);});assert.equal(getSale(store,scope,'old').customerName,'Cliente histórico');assert.equal(getSale(store,other,'old').customerName,'Outra empresa');assert.equal(getSale(store,sister,'old').customerName,'Outra unidade');assert.throws(()=>getSale(store,{...other,userId:'actor'},'old'),e=>e.status===403);assert.throws(()=>getSale(store,scope,'foreign-sale'),e=>e.status===404);
 const current=loadState(store,scope),bad=structuredClone(current.state);bad.sales[0].customerId='foreign-customer';assert.throws(()=>store.transaction(()=>writeState(store,scope,bad,current.revision)),/FOREIGN KEY/);assert.deepEqual(loadState(store,scope),current);
});
test('Unidade vazia retorna página vazia sem GET gravar; marcador ausente falha fechado',t=>{
 const{store,scope}=fixture(t),unit=createUnit(store,scope.companyId,{name:'Vazia'}),empty={companyId:scope.companyId,unitId:unit.id},before=store.db.prepare('SELECT count(*) n FROM commercial_normalizations').get().n;assert.equal(querySales(store,empty).total,0);assert.equal(store.db.prepare('SELECT count(*) n FROM commercial_normalizations').get().n,before);store.db.exec("DELETE FROM commercial_normalizations WHERE aggregate='sales'");assert.throws(()=>querySales(store,scope),e=>e.status===503);
});
test('Venda, estoque, recibo e auditoria ficam SQL atômicos e replay é uma venda',t=>{
 const{store,scope,ctx}=fixture(t),input=commandInput(),first=executeStateCommand(store,ctx,state=>sale(state,input)),events=store.db.prepare('SELECT count(*) n FROM audit_events').get().n;assert.equal(getSale(store,scope,first.state.sales[0].id).execution.executedBy,'actor');assert.equal(getSale(store,scope,first.state.sales[0].id).receipts[0].amountCents,101);const again=executeStateCommand(store,ctx,state=>sale(state,input));assert.equal(again.revision,first.revision);assert.equal(querySales(store,scope).total,1);assert.equal(store.db.prepare('SELECT count(*) n FROM audit_events').get().n,events);assert.throws(()=>executeStateCommand(store,ctx,state=>sale(state,{...input,items:[{productId:'p',quantity:2,priceCents:101}]})),/outros dados/);
});
test('Falha SQL em filho reverte venda, estoque, recibo, revisão e auditoria',t=>{
 const{store,scope,ctx}=fixture(t),before=loadState(store,scope);store.db.exec("CREATE TRIGGER deny_sale_item BEFORE INSERT ON commercial_sale_items BEGIN SELECT RAISE(ABORT,'synthetic sales child failure'); END;");assert.throws(()=>executeStateCommand(store,ctx,state=>sale(state,commandInput())),/synthetic/);assert.deepEqual(loadState(store,scope),before);assert.equal(store.db.prepare('SELECT count(*) n FROM commercial_sales').get().n,0);assert.equal(store.db.prepare('SELECT count(*) n FROM commercial_sale_receipts').get().n,0);assert.equal(store.db.prepare('SELECT count(*) n FROM commercial_stock_movements').get().n,0);assert.equal(store.db.prepare('SELECT count(*) n FROM audit_events').get().n,0);
});
test('Recebimento, parcelamento, alocação e perdão mantêm fatos SQL sem segunda baixa',t=>{
 const{store,scope,ctx}=fixture(t),created=executeStateCommand(store,ctx,state=>sale(state,commandInput({paymentStatus:'pending',items:[{productId:'p',quantity:2,priceCents:101}]}))),id=created.state.sales[0].id,{accountAction}=require('../accounts');let current=executeStateCommand(store,ctx,state=>accountAction(state,'plan',{requestId:randomUUID(),saleId:id,expectedVersion:0,expectedReturnVersion:0,dueDates:['2026-11-01','2026-12-01']}));const installment=current.state.sales[0].receivablePlan[0];current=executeStateCommand(store,ctx,state=>accountAction(state,'receive',{requestId:randomUUID(),saleId:id,expectedVersion:1,expectedReturnVersion:0,installmentId:installment.id,value:'0.50',paymentMethod:'pix',expectedRemainingCents:202}));current=executeStateCommand(store,ctx,state=>accountAction(state,'forgive',{requestId:randomUUID(),saleId:id,expectedVersion:2,expectedReturnVersion:0,value:'0.20',reason:'Sintético',expectedRemainingCents:152}));const sql=getSale(store,scope,id);assert.equal(sql.receivablePlan.length,2);assert.equal(sql.receipts[0].allocations[0].amountCents,50);assert.equal(sql.forgiveness[0].amountCents,20);assert.equal(current.state.products[0].stock,8);assert.equal(current.state.stockMovements.length,1);
});
test('Cancelamento e devolução parcial/restituição preservam SQL, origens e efeitos únicos',t=>{
 const{store,scope,ctx}=fixture(t),input=commandInput({items:[{productId:'p',quantity:2,priceCents:101}]}),created=executeStateCommand(store,ctx,state=>sale(state,input)),id=created.state.sales[0].id,{returnAction}=require('../workflows');let current=executeStateCommand(store,ctx,state=>returnAction(state,'create',{requestId:randomUUID(),saleId:id,expectedVersion:0,reason:'Devolução sintética',items:[{productId:'p',quantity:1,restockQuantity:1}]}));assert.equal(getSale(store,scope,id).returns[0].items[0].quantity,1);assert.equal(current.state.products[0].stock,9);const returned=current.state.sales[0].returns[0].totalCents;current=executeStateCommand(store,ctx,state=>returnAction(state,'refund',{requestId:randomUUID(),saleId:id,expectedVersion:1,value:String(returned/100),paymentMethod:'pix',paidDate:'2026-10-01',expectedRefundCents:returned,reason:'Restituição sintética'}));assert.equal(getSale(store,scope,id).refunds[0].amountCents,returned);assert.equal(current.state.stockMovements.length,2);assert.equal(current.state.expenses,undefined);assert.throws(()=>executeStateCommand(store,ctx,state=>change(state,'/api/sales/cancel',{id})),/devolução parcial/);
});
test('Duas conexões disputando última unidade mantêm somente uma venda SQL',async t=>{
 const dir=path.resolve(__dirname,'../.qa/foundation-v1.2/sales-tests');fs.mkdirSync(dir,{recursive:true});const filename=path.join(dir,'concurrency-'+randomUUID()+'.sqlite'),state=base();state.products[0].stock=1;const{store,scope,ctx}=fixture(t,state,filename),second=new SqlStore(filename,{environment:'test'});t.after(()=>second.close());t.after(()=>{for(const suffix of ['','-wal','-shm'])if(fs.existsSync(filename+suffix))fs.unlinkSync(filename+suffix);});
 const responses=await Promise.allSettled([Promise.resolve().then(()=>executeStateCommand(store,ctx,next=>sale(next,commandInput()))),Promise.resolve().then(()=>executeStateCommand(second,ctx,next=>sale(next,commandInput())))]);assert.equal(responses.filter(r=>r.status==='fulfilled').length,1);assert.equal(loadState(store,scope).state.products[0].stock,0);assert.equal(querySales(second,scope).total,1);assert.equal(loadState(second,scope).state.stockMovements.length,1);
});
