'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{randomBytes,randomUUID}=require('node:crypto');
const {SqlStore,hash}=require('./sql-store'),{Identity,hashPassword}=require('./identity'),{createCompany,createUnit}=require('./entities'),{grantCompanyAccess,grantUnitAccess}=require('./access'),{seedPermissions,createRole,assignRole,setRolePermissions}=require('./rbac'),{loadState}=require('./scoped-state'),{writeState,saveBusinessState}=require('./state-repository'),{requestContext}=require('./request-context'),{appendAudit,verifyAuditChain}=require('./audit');
const A=require('./inactive-sale-approval');
const password='Senha sintética 123!';let encodedPromise;
async function fixture(t,rights=['sales.authorize_inactive']){
 const encoded=await(encodedPromise||=hashPassword(password)),store=new SqlStore(':memory:',{environment:'test'}),company=createCompany(store,{name:'Empresa sintética'}),unit=createUnit(store,company.id,{name:'Unidade sintética'}),scope={companyId:company.id,unitId:unit.id};seedPermissions(store);
 let time=Date.parse('2026-10-02T12:00:00Z');const identity=new Identity(store,{now:()=>time}),runtime={store,identity},token=randomBytes(32).toString('base64url');identity.dummy=encoded;
 for(const[id,name,login]of [['u','Executor','executor'],['a','Autorizador','approver']]){store.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?)').run(id,name,login,encoded,'active','t','t');grantCompanyAccess(store,id,scope.companyId);grantUnitAccess(store,id,scope.companyId,scope.unitId);}
 const seller=createRole(store,scope.companyId,{name:'Vendedor',permissions:['catalog.view','sales.view','sales.create']}),approver=createRole(store,scope.companyId,{name:'Autorizador',permissions:rights});assignRole(store,'u',scope.companyId,scope.unitId,seller.id);assignRole(store,'a',scope.companyId,scope.unitId,approver.id);
 const date=new Date(time).toISOString();store.db.prepare('INSERT INTO sessions VALUES(?,?,?,?,?,?,?,?,NULL)').run('session',hash(token),'u',scope.companyId,scope.unitId,date,new Date(time+3600000).toISOString(),date);
 const headers={host:'127.0.0.1:3215',origin:'http://127.0.0.1:3215','content-type':'application/json',cookie:'foundation_session='+token,'x-csrf-token':identity.sessionCsrf(hash(token),scope.companyId,scope.unitId),'x-company-id':scope.companyId,'x-unit-id':scope.unitId};
 const req={method:'POST',url:'/api/commercial/sales',headers,socket:{remoteAddress:'127.0.0.1'}};
 const state={products:[{id:'p',name:'Desativado',active:false,version:1,stock:10,priceCents:100},{id:'q',name:'Ativo',active:true,version:1,stock:10,priceCents:200}],customers:[],sales:[]};store.transaction(()=>writeState(store,scope,state,0));
 const draft={requestId:randomUUID(),items:[{productId:'p',quantity:1,priceCents:100},{productId:'q',quantity:1,priceCents:200}],paymentMethod:'cash',paymentStatus:'received',expectedCashSessionId:null};
 const approve=(overrides={})=>A.approveInactiveSale(runtime,req,{saleDraft:draft,approverLogin:'approver',approverPassword:password,reason:'Liberação consciente',...overrides});
 const ctx=()=>requestContext(identity,req,{write:true});t.after(()=>store.close());
 return{store,runtime,identity,scope,req,state,draft,approve,ctx,approver,seller,advance:n=>time+=n};
}
function complete(f,grant){return f.store.transaction(()=>{const ctx=f.ctx(),{state,revision}=loadState(f.store,ctx),input={...f.draft,approvalToken:grant.approvalToken},proof=A.consumeInactiveApproval(f.store,ctx,state,input),next=require('../server').sale(state,input,null,proof),sale=next.sales[0];sale.commercialCommandFingerprint=A.draftFingerprint(input);A.bindSaleProof(f.store,ctx,proof,sale);return saveBusinessState(f.store,ctx,state,next,revision,input,'/api/commercial/sales',proof);});}
test('grant hash-only não grava senha/token e exige motivo/DTO explícito',async t=>{const f=await fixture(t);await assert.rejects(f.approve({reason:' '}),e=>e.code==='APPROVAL_REASON_REQUIRED');await assert.rejects(f.approve({saleDraft:{...f.draft,authorizedBy:'a'}}),e=>e.code==='INVALID_SALE_DRAFT');const grant=await f.approve(),row=f.store.db.prepare('SELECT * FROM inactive_sale_approvals').get();assert.equal(row.token_hash,hash(grant.approvalToken));assert.notEqual(row.token_hash,grant.approvalToken);assert.equal(row.authorizer_id,'a');assert.equal(row.executor_id,'u');assert.equal(Date.parse(grant.expiresAt)-Date.parse(row.created_at),120000);const audit=JSON.stringify(f.store.db.prepare('SELECT * FROM audit_events').all());assert.equal(audit.includes(password),false);assert.equal(audit.includes(grant.approvalToken),false);assert.equal(verifyAuditChain(f.store),true);});
test('senha errada/inexistente/inativa/sem direito produz mesma resposta sem grant',async t=>{const f=await fixture(t,[]);const errors=[];for(const override of [{approverPassword:'errada'},{approverLogin:'missing'},{}]){try{await f.approve(override);}catch(e){errors.push([e.status,e.code,e.message]);}}f.store.db.exec("UPDATE users SET status='inactive' WHERE id='a'");try{await f.approve();}catch(e){errors.push([e.status,e.code,e.message]);}assert.equal(errors.length,4);for(const e of errors)assert.deepEqual(e,errors[0]);assert.equal(f.store.db.prepare('SELECT count(*) n FROM inactive_sale_approvals').get().n,0);assert.equal(f.store.db.prepare("SELECT count(*) n FROM audit_events WHERE action='INACTIVE_APPROVAL_DENIED'").get().n,4);});
test('próprio executor pode confirmar identidade se possui direito explícito',async t=>{const f=await fixture(t);setRolePermissions(f.store,f.scope.companyId,f.seller.id,['catalog.view','sales.view','sales.create','sales.authorize_inactive']);const grant=await f.approve({approverLogin:'executor'});assert.equal(f.store.db.prepare('SELECT authorizer_id FROM inactive_sale_approvals WHERE id=?').get(grant.approvalId).authorizer_id,'u');});
test('fingerprint inclui caixa e conteúdo mas exclui token/responsável declarado',async t=>{const f=await fixture(t),fingerprint=A.draftFingerprint(f.draft);assert.equal(A.draftFingerprint({...f.draft,responsible:'qualquer',approvalToken:'token'}),fingerprint);assert.notEqual(A.draftFingerprint({...f.draft,expectedCashSessionId:'other'}),fingerprint);assert.notEqual(A.draftFingerprint({...f.draft,items:[{productId:'p',quantity:2}]}),fingerprint);assert.throws(()=>A.validateSaleDraft({...f.draft,items:[{productId:'p',quantity:1,authorizedBy:'a'}]}));});
test('consumo venda estoque e auditoria registram aprovador só dos itens inativos',async t=>{const f=await fixture(t),grant=await f.approve(),out=complete(f,grant),sale=out.state.sales[0];assert.equal(out.state.products[0].active,false);assert.equal(out.state.products[0].stock,9);assert.equal(sale.execution.executedBy,'u');assert.equal(sale.execution.authorizedBy,'a');assert.equal(sale.execution.approverName,'Autorizador');assert.equal(sale.execution.approvalReason,'Liberação consciente');assert.deepEqual(sale.execution.inactiveProductIds,['p']);assert.equal(out.state.stockMovements.find(m=>m.productId==='p').execution.authorizedBy,'a');assert.equal(out.state.stockMovements.find(m=>m.productId==='q').execution.authorizedBy,null);const audit=f.store.db.prepare("SELECT * FROM audit_events WHERE entity='sales'").get();assert.equal(audit.authorized_by,'a');assert.equal(verifyAuditChain(f.store),true);const row=f.store.db.prepare('SELECT * FROM inactive_sale_approvals').get();assert.equal(row.sale_id,sale.id);assert.ok(row.consumed_at);assert.equal(JSON.stringify(out.state).includes(grant.approvalToken),false);assert.equal(JSON.stringify(out.state).includes(password),false);});
test('grant é rejeitado por outro request/conteúdo/sessão/contexto e continua não consumido',async t=>{const f=await fixture(t),grant=await f.approve();for(const override of [{requestId:'other'},{expectedCashSessionId:'changed'},{items:[{productId:'p',quantity:2}]}])assert.throws(()=>f.store.transaction(()=>A.consumeInactiveApproval(f.store,f.ctx(),f.state,{...f.draft,...override,approvalToken:grant.approvalToken})),e=>e.code==='INACTIVE_APPROVAL_INVALID');assert.throws(()=>f.store.transaction(()=>A.consumeInactiveApproval(f.store,{...f.ctx(),sessionId:'other'},f.state,{...f.draft,approvalToken:grant.approvalToken})),e=>e.code==='INVALID_SESSION');assert.equal(f.store.db.prepare('SELECT consumed_at FROM inactive_sale_approvals').get().consumed_at,null);});
test('estoque preço versão/situação alterados rejeitam a autorização antiga',async t=>{const f=await fixture(t),grant=await f.approve();for(const fields of [{stock:9},{priceCents:101},{version:2},{active:true}]){const changed=structuredClone(f.state);Object.assign(changed.products[0],fields);assert.throws(()=>f.store.transaction(()=>A.consumeInactiveApproval(f.store,f.ctx(),changed,{...f.draft,approvalToken:grant.approvalToken})),e=>e.code==='INACTIVE_APPROVAL_INVALID');}assert.equal(f.store.db.prepare('SELECT consumed_at FROM inactive_sale_approvals').get().consumed_at,null);});
test('expiração e revogação de direito após grant impedem consumo',async t=>{const f=await fixture(t),grant=await f.approve();setRolePermissions(f.store,f.scope.companyId,f.approver.id,[]);assert.throws(()=>complete(f,grant),e=>e.code==='INACTIVE_APPROVAL_INVALID');setRolePermissions(f.store,f.scope.companyId,f.approver.id,['sales.authorize_inactive']);f.advance(120000);assert.throws(()=>complete(f,grant),e=>e.code==='INACTIVE_APPROVAL_INVALID');assert.equal(loadState(f.store,f.scope).state.products[0].stock,10);});
test('revogação durante await da senha é revalidada antes de emitir grant',async t=>{const f=await fixture(t),kdf=f.identity.kdf.bind(f.identity);f.identity.kdf=async fn=>{const result=await kdf(fn);setRolePermissions(f.store,f.scope.companyId,f.approver.id,[]);return result;};await assert.rejects(f.approve(),e=>e.code==='APPROVAL_DENIED');assert.equal(f.store.db.prepare('SELECT count(*) n FROM inactive_sale_approvals').get().n,0);});
test('prova forjada ou de transação encerrada não libera item nem auditoria',async t=>{const f=await fixture(t),grant=await f.approve();assert.equal(A.isInactiveApproved({},f.state.products[0]),false);const proof=f.store.transaction(()=>A.consumeInactiveApproval(f.store,f.ctx(),f.state,{...f.draft,approvalToken:grant.approvalToken}));assert.equal(A.isInactiveApproved(proof,f.state.products[0]),false);f.store.transaction(()=>assert.throws(()=>A.approvalMetadata(f.store,f.ctx(),proof),e=>e.code==='APPROVAL_REQUIRED'));f.store.transaction(()=>assert.throws(()=>appendAudit(f.store,{...f.ctx(),action:'CREATE',entity:'sales',recordId:'s',authorizedBy:'a',approvalProof:{},after:{id:'s'}}),e=>e.code==='APPROVAL_REQUIRED'));});
test('falha após consumo desfaz grant venda e estoque permitindo retry',async t=>{const f=await fixture(t),grant=await f.approve();f.store.db.exec("CREATE TRIGGER approval_rollback BEFORE INSERT ON audit_events WHEN NEW.entity='sales' BEGIN SELECT RAISE(ABORT,'sale audit rollback'); END;");assert.throws(()=>complete(f,grant),/sale audit rollback/);assert.equal(f.store.db.prepare('SELECT consumed_at FROM inactive_sale_approvals').get().consumed_at,null);assert.equal(loadState(f.store,f.scope).state.sales.length,0);assert.equal(loadState(f.store,f.scope).state.products[0].stock,10);f.store.db.exec('DROP TRIGGER approval_rollback');assert.equal(complete(f,grant).state.sales.length,1);assert.throws(()=>complete(f,grant),e=>e.code==='INACTIVE_APPROVAL_INVALID');});
test('migração concede uma vez apenas ao papel com os18 direitos explícitos e registra origem técnica',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'inactive-upgrade-'));for(const file of fs.readdirSync(path.join(__dirname,'migrations')).filter(n=>/^00[1-6]_/.test(n)))fs.copyFileSync(path.join(__dirname,'migrations',file),path.join(dir,file));const s=new SqlStore(':memory:',{environment:'test',migrationsDir:dir});t.after(()=>s.close());const c=createCompany(s,{name:'Sintética'}),u=createUnit(s,c.id,{name:'Sintética'}),previous=['catalog.view','catalog.manage','inventory.view','inventory.adjust','sales.view','sales.create','sales.cancel','purchases.manage','financial.view','financial.manage','cash.manage','operations.view','operations.manage','users.manage','roles.manage','companies.manage','units.manage','audit.view'];for(const p of previous)s.db.prepare('INSERT INTO permissions VALUES(?,?)').run(p,p);const full=createRole(s,c.id,{name:'Qualquer nome',permissions:previous}),partial=createRole(s,c.id,{name:'Proprietário',permissions:['sales.create']});s.migrate(path.join(__dirname,'migrations'));assert.equal(s.db.prepare("SELECT count(*) n FROM role_permissions WHERE role_id=? AND permission_code='sales.authorize_inactive'").get(full.id).n,1);assert.equal(s.db.prepare("SELECT count(*) n FROM role_permissions WHERE role_id=? AND permission_code='sales.authorize_inactive'").get(partial.id).n,0);seedPermissions(s);seedPermissions(s);assert.equal(s.db.prepare("SELECT count(*) n FROM audit_events WHERE action='PERMISSION_UPGRADE'").get().n,1);const row=s.db.prepare('SELECT * FROM audit_events').get();assert.equal(row.user_id,null);assert.equal(row.executed_by,null);assert.equal(row.company_id,null);assert.equal(row.authorized_by,null);setRolePermissions(s,c.id,full.id,previous);seedPermissions(s);assert.equal(s.db.prepare("SELECT count(*) n FROM role_permissions WHERE permission_code='sales.authorize_inactive'").get().n,0);assert.equal(verifyAuditChain(s),true);});
