'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {SqlStore}=require('./sql-store');
test('migrations aplicam uma vez e constraints ficam ativas',()=>{const expected=fs.readdirSync(path.join(__dirname,'migrations')).filter(n=>/^\d+_[a-z0-9_]+\.sql$/.test(n)).sort(),s=new SqlStore(':memory:');try{assert.deepEqual(s.db.prepare('SELECT version FROM schema_migrations ORDER BY version').all().map(r=>r.version),expected);s.migrate(path.join(__dirname,'migrations'));assert.deepEqual(s.db.prepare('SELECT version FROM schema_migrations ORDER BY version').all().map(r=>r.version),expected);assert.equal(s.db.prepare('PRAGMA foreign_keys').get().foreign_keys,1);assert.throws(()=>s.db.prepare('INSERT INTO units VALUES(?,?,?,?,?,?)').run('inexistente','u','Loja','active','t','t'));}finally{s.close();}});
test('falha SQL faz rollback e impede callback assíncrono',()=>{const s=new SqlStore(':memory:');try{assert.throws(()=>s.transaction(()=>{s.setMeta('x','1');throw Error('falha');}));assert.equal(s.meta('x'),undefined);assert.throws(()=>s.transaction(()=>Promise.resolve()));assert.equal(s.inTransaction,false);}finally{s.close();}});
test('migration aplicada alterada é rejeitada sem seguir silenciosamente',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'foundation-migrations-')),sql=path.join(dir,'001_test.sql');fs.writeFileSync(sql,'CREATE TABLE x(id TEXT);');const s=new SqlStore(':memory:',{migrationsDir:dir});try{fs.writeFileSync(sql,'CREATE TABLE y(id TEXT);');assert.throws(()=>s.migrate(dir),/alterada/);assert.equal(s.db.prepare("SELECT count(*) n FROM sqlite_master WHERE name='y'").get().n,0);}finally{s.close();}});
test('migration removida/desconhecida ou inserida antes da aplicada bloqueia avanço',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'foundation-order-'));fs.writeFileSync(path.join(dir,'002_test.sql'),'CREATE TABLE x(id TEXT);');const s=new SqlStore(':memory:',{migrationsDir:dir});try{fs.writeFileSync(path.join(dir,'001_prior.sql'),'CREATE TABLE y(id TEXT);');assert.throws(()=>s.migrate(dir),/fora de ordem/);const dir2=fs.mkdtempSync(path.join(os.tmpdir(),'foundation-empty-'));assert.throws(()=>s.migrate(dir2),/ausente/);assert.equal(s.db.prepare("SELECT count(*) n FROM sqlite_master WHERE name='y'").get().n,0);}finally{s.close();}});
test('configuração e store rejeitam banco operacional em teste antes de abrir arquivo',()=>{const{configuration}=require('./config');const file=path.join(__dirname,'../data/foundation.sqlite');assert.throws(()=>configuration({environment:'test',filename:file}));assert.throws(()=>new SqlStore(file,{environment:'test'}));if(process.platform==='win32')assert.throws(()=>configuration({environment:'test',filename:file.toUpperCase()}));assert.equal(configuration({environment:'test',filename:':memory:'}).filename,':memory:');});
test('callback async não é invocado e nenhuma escrita continua após rollback',async()=>{const s=new SqlStore(':memory:');try{let invoked=false;assert.throws(()=>s.transaction(async()=>{invoked=true;await Promise.resolve();s.setMeta('late','outside');}));await Promise.resolve();assert.equal(invoked,false);assert.equal(s.meta('late'),undefined);assert.throws(()=>s.setMeta('outside','write'));}finally{s.close();}});
